### ISSUE TITLE
Want to understand , is Spring Openfeign is in Deprecated path

### ISSUE THREAD

**Issue by RAMPRASATH123** [spring-cloud/spring-cloud-openfeign#1007]
Hi Team , 

We saw a thread which talks about using [Spring Interface Clients](https://docs.spring.io/spring-framework/docs/6.0.6-SNAPSHOT/reference/html/integration.html#rest-http-interface) instead of Open feign . 

Just wanted to understand that is Spring Open feign is in deprecating and what shared above is the alternate for the same.

Thanks,
Ram

**Comment by amjathsharief** [comment]
If its in feature complete mode, then why spring team is creating one more client framework? Its really confusing. Someone MUST clarify it.

**Comment by OlgaMaciaszek** [comment]
Exactly that's why - it's feature complete, we're not adding new stuff. We're actively developing Interface Clients to provide better support also for features not supported by Feign, such as reactive calls with WebClient.

**Comment by Ed42** [comment]
Please can you confirm it will NOT be deprecated. We have a sizeable investment in Spring Cloud Openfeign, and have no need for reactive/WebClient.

**Comment by OlgaMaciaszek** [comment]
@Ed42  I cannot confirm it will never be deprecated, as these kind of decisions are taken after periodic project reviews, and it can't be said about any other project either, however, we do not have any plans of doing it at this point. At the same time, it is in maintenance only mode, so  we don't really plan doing much future work on it other than some important bugfixes and security upgrades.
