### ISSUE TITLE
NullPointerException in  RetryableFeignLoadBalancer because of null retryPolicy

### ISSUE THREAD

**Issue by florian-perrotti** [spring-cloud/spring-cloud-openfeign#101]
Hello,

When using `RetryableFeignLoadBalancer`, I am getting a NullPointerException on `retryPolicy` at the line below.
https://github.com/spring-cloud/spring-cloud-openfeign/blob/c1bbb9cbb305c9ba9242b9c28de0c85a2a0957a9/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/ribbon/RetryableFeignLoadBalancer.java#L104

This `retryPolicy` we get it from here:
https://github.com/spring-cloud/spring-cloud-openfeign/blob/c1bbb9cbb305c9ba9242b9c28de0c85a2a0957a9/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/ribbon/RetryableFeignLoadBalancer.java#L78

In my case here, it comes `loadBalancedRetryFactory` being a mock in a test, it returns null so I can easily add a behavior to my mock but I am wondering if a null check before calling `retryableStatusCode` method.

The way I understand it (it might be completely wrong and if that is the case I apologize for wasting your time :/ ), the `doWithRetry` method of the `RetryCallback` will always be called (at least once) and when setting the `retryTemplate`'s retryPolicy here
https://github.com/spring-cloud/spring-cloud-openfeign/blob/c1bbb9cbb305c9ba9242b9c28de0c85a2a0957a9/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/ribbon/RetryableFeignLoadBalancer.java#L86
we are checking that `retryPolicy` object can be null so we know it can happen. 

Shouldn't we make a check inside the `doWithRetry` as well or use a default behaviour? Does this make sense or am I missing something?

Thanks!

**Comment by ryanjbaxter** [comment]
There should always be a retry policy present.  If nothing is configured is it `NeverRetryPolicy`.  I suggest you mock this behavior in your test.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by florian-perrotti** [comment]
Thanks @ryanjbaxter , I do agree and that's what I did for test and it works. I just wanted to point out that it might happen. To me it would makes sense to check for `retryPolicy` nullity: I mean the `RetryPolicy` passed to the `retryTemplate` is set there: 
https://github.com/spring-cloud/spring-cloud-openfeign/blob/c1bbb9cbb305c9ba9242b9c28de0c85a2a0957a9/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/ribbon/RetryableFeignLoadBalancer.java#L86

so this is where we set the `NeverRetryPolicy`. The check could be done there 
https://github.com/spring-cloud/spring-cloud-openfeign/blob/c1bbb9cbb305c9ba9242b9c28de0c85a2a0957a9/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/ribbon/RetryableFeignLoadBalancer.java#L104
to be sure to use `NeverRetryPolicy` if the object `retryPolicy` is null.
Unless you tell me that there 
https://github.com/spring-cloud/spring-cloud-openfeign/blob/c1bbb9cbb305c9ba9242b9c28de0c85a2a0957a9/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/ribbon/RetryableFeignLoadBalancer.java#L78

we cannot get a null object I believe if the check is done once, it should be done a second time no?
Thanks in advance and sorry for the delay.

**Comment by ryanjbaxter** [comment]
Closed via a693c30
