### ISSUE TITLE
Feign client as fallback for Feign client

### ISSUE THREAD

**Issue by gnupinguin** [spring-cloud/spring-cloud-openfeign#102]
I'm trying to create feign client with the fallback that is feign client. But I'm getting the exception:
> Fallback class must implement the interface annotated by @FeignClient

Example:
`@FeignClient(name = "MyClient", url = "http://localhost:8080",
        configuration = ClientConfiguration.class,
        decode404 = true, fallback = FallbackClient.class)
public interface MyClient {
     //some methods
}`

`@FeignClient(name =  "FallBackClient", url = "http://localhost:8080",
        configuration = FallbackClient.class,
        decode404 = true)
public interface FallbackClient extends MyClient {
     //some methods
}`

I'm using Spring Boot 2.1.1.RELEASE  and Spring Cloud 2.0.2.RELEASE . In previous versions of spring boot it works perfectly.

**Comment by spencergibb** [comment]
Closing as answered
