### ISSUE TITLE
[Question]: Why was spring-boot-starter-aop removed from dependencies?

### ISSUE THREAD

**Issue by maxl2287** [spring-cloud/spring-cloud-openfeign#1035]
Hi together,

just a short question. 
We are using resilience4j, which needs:

```xml
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-aop</artifactId>
</dependency>
```
With upgrading spring-cloud-dependencies to the latest version `2023.0.2`, we faced issues that our Retry-mechanism was not working anymore.
Then we analyzed the dependencies and saw that you have removed the aop-dependency from spring-cloud-openfeign-core (https://github.com/spring-cloud/spring-cloud-openfeign/commit/6084609de0705f24ba418704769e545a0d820d70).

As a change we just have included aop by ourself, but we just wanted to know what was the intention of removing this. 

Thanks in advance! :)

**Comment by jjlharrison** [comment]
Just to confirm that this issue affecting multiple dependent projects. We have added the dependency directly to resolve the issue.

It would be good to know why the dependency was removed and why it was there in the first place. Unfortunately, the Resilience4J annotations are just silently ignored without it (unless you have tests verifying their behaviour, which we fortunately had).

Thanks 🙂

**Comment by maxl2287** [comment]
> Just to confirm that this issue affecting multiple dependent projects. We have added the dependency directly to resolve the issue.
> 
> It would be good to know why the dependency was removed and why it was there in the first place. Unfortunately, the Resilience4J annotations are just silently ignored without it (unless you have tests verifying their behaviour, which we fortunately had).
> 
> Thanks 🙂

@jjlharrison Exactly we had the same issue. This issue only came up by having verification tests, which did not trigger retries at all after upgrading spring-cloud-dependencies :)

**Comment by mgimenoromanadevinta** [comment]
Hello
Are there any news on this topic?
Thanks

**Comment by OlgaMaciaszek** [comment]
Hi all, we have discover that `spring-boot-starter-aop` was a legacy dependency in Spring Cloud OpenFeign. The project hasn't used it for a long time and hence it should not be there anymore. Additionally, it was causing an AOT issue (https://github.com/spring-projects/spring-data-mongodb/issues/4637#issuecomment-2034911106) that was in no way related to SC OpenFeign. If the dependency is required by other projects, the users should add it directly if not provided.

**Comment by boris-faniuk-n26** [comment]
Hello, @OlgaMaciaszek ! 
Thanks for the explanation, we had a similar issue.
As a suggestion, maybe it worth updating at least minor version in case you modify the structure of dependencies.
We have dependabot grouping patch updates and PR with 10 different failed. 
It would be easier to find this thread, if we knew that openfeign update was the reason.

**Comment by OlgaMaciaszek** [comment]
I agree that it would be preferable, however, we do a major/minor release usually just once a year and given the AOT bug, it would have been problematic to wait that much, so since it was a bugfix, we decided to go ahead with it. We're sorry for any inconvenience this might have caused.

**Comment by lazee** [comment]
As other says, this goes for all the starters, that are removed. The documentation should at least be updated, as it is clearly wrong pt. (eg https://spring.io/projects/spring-cloud-sleuth)

**Comment by OlgaMaciaszek** [comment]
@lazee  Spring Cloud Sleuth is a separate project. If you've found any other problem in Spring Cloud OpenFeign docs, please create a separate GH issue and we'll fix it.
