### ISSUE TITLE
@EnableFeignClients does not detect feign bean in multi-module.

### ISSUE THREAD

**Issue by young0264** [spring-cloud/spring-cloud-openfeign#1053]
**Describe the bug**

1. **open feign version**

```
	implementation 'org.springframework.cloud:spring-cloud-starter-openfeign:4.1.1'
```

2. It is assumed that the package structure is the same across modules.

---

Hi, I have discovered issue.
In a multi-module Spring Boot project, when @EnableFeignClients is configured in the main application class, it does not detect Feign clients implementing other modules.

```shell
implementation project(':common-lib')

``` 

In a situation where a module references a library module like common-lib using implementation project(':common-lib'), the beans are not being detected.(Assuming the module package structure is the same)

However, when explicitly setting the package path in @EnableFeignClients(ex: @EnableFeignClients("org.project")), it successfully scans and registers Feign client beans from other modules.

I'm curious whether this is the intended behavior or if it might be an issue.

If this behavior is not intentional, it would be helpful to document it in the related documentation. (Should I be the one to register it? I also want to be a contributor.)

```java
    // The results will vary depending on whether you use @EnableFeignClients("org.project") or just @EnableFeignClients.
    @Test
    void isThereBeanImplementedMultiModule() {
        String feignBeanName = "alarmCommonFeignClient";
        String[] beanNames = applicationContext.getBeanDefinitionNames();
        for (String beanName : beanNames) {
            boolean contains = beanName.contains(feignBeanName);
            if (contains) {
                assertThat(contains).isEqualTo(true);
            }
        }
    }
```

```bash
# console
beanName: alarmCommonFeignClient.FeignClientSpecification
```

<img width="281" alt="스크린샷 2024-09-04 13 22 54" src="https://github.com/user-attachments/assets/3817d921-7fd9-45c6-bd38-a129c3d170e9">

**Comment by OlgaMaciaszek** [comment]
Hello @young0264. We have discussed it as a team: this is by design and we're not planning on changing it at this point.

**Comment by young0264** [comment]
Thank you for your response. What I'm curious about is, if that's how it was intentionally designed, shouldn't the official documentation mention something like "In order to read Feign beans in a multi-module setup, you need to specify the path directly"? What do you think?

**Comment by young0264** [comment]
> Hello @young0264. We have discussed it as a team: this is by design and we're not planning on changing it at this point.

Thank you for your response. What I'm curious about is, if that's how it was intentionally designed, shouldn't the official documentation mention something like "In order to read Feign beans in a multi-module setup, you need to specify the path directly"? What do you think?

**Comment by OlgaMaciaszek** [comment]
Right, I'll add the missing info to the documentation.

**Comment by Gnllsn** [comment]
hello , anyone has link to that original documentation for this , thanks

**Comment by Lasko93** [comment]
> hello , anyone has link to that original documentation for this , thanks

https://github.com/spring-cloud/spring-cloud-openfeign/commit/187034dcc2c6d53be4ffbb40f40ebcffac6a09ca
