### ISSUE TITLE
Unable to decode application/json response

### ISSUE THREAD

**Issue by Saranpjs727** [spring-cloud/spring-cloud-openfeign#1072]
The Feign client fails to decode a JSON response, but it works fine after adding an interceptor (even if the interceptor does nothing). We also added `Accept: application/json` in the request headers, but it didn't work.

In the interceptor, we used:

```
JacksonDecoder delegate = new JacksonDecoder();
delegate.decode(response);
```

**Comment by OlgaMaciaszek** [comment]
Hi @Saranpjs727, thanks for reporting the issue. 
Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/). 
Please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by Saranpjs727** [comment]
thanks OlgaMaciaszek
