### ISSUE TITLE
Custom AnnotatedParameterProcessor is replace DefaultAnnotatedArgumentsProcessors?

### ISSUE THREAD

**Issue by liudaomanbu** [spring-cloud/spring-cloud-openfeign#111]
version:1.4.5

I try to add a Custom AnnotatedParameterProcessor to solve the problem that feign use get method type to  transfer Object param.
Then i found that IllegalStateException: Method has too many Body parameters occurred at startup.
This reason is SpringMvcContract construct
```
		List<AnnotatedParameterProcessor> processors;
		if (!annotatedParameterProcessors.isEmpty()) {
			processors = new ArrayList<>(annotatedParameterProcessors);
		}
		else {
			processors = getDefaultAnnotatedArgumentsProcessors();
		}
		this.annotatedArgumentProcessors = toAnnotatedArgumentProcessorMap(processors);
```
When Custom AnnotatedParameterProcessors exist,DefaultAnnotatedArgumentsProcessors is not obtained.

Generally speaking,for multiple objects that can exist in spring container,custom a object to spring container mean that add a custom object instead of replace default objects.

I think this is a bug?
Otherwise,how to keep the default setting and add a my AnnotatedParameterProcessor In this condition?

**Comment by brunneng** [comment]
As a workaround you can define this 4 default parameter processors as beans in configuration, corresponding to your feign client:
    ```
@Bean
    public AnnotatedParameterProcessor pathVariableParameterProcessor() {
        return new PathVariableParameterProcessor();
    }

    @Bean
    public AnnotatedParameterProcessor requestParamParameterProcessor() {
        return new RequestParamParameterProcessor();
    }

    @Bean
    public AnnotatedParameterProcessor requestHeaderParameterProcessor() {
        return new RequestHeaderParameterProcessor();
    }

    @Bean
    public AnnotatedParameterProcessor queryMapParameterProcessor() {
        return new QueryMapParameterProcessor();
    }
```
