### ISSUE TITLE
Build and test for Linux/ARM64

### ISSUE THREAD

**Issue by odidev** [spring-cloud/spring-cloud-openfeign#1112]
## Description 

For aarch64 platform, I have built "Spring-Cloud-Openfeign" from source. 

  

## Steps  

Following [STEPS](https://github.com/spring-cloud/spring-cloud-openfeign?tab=readme-ov-file#basic-compile-and-test) were used for the building and installation: 

  
~~~
$ git clone https://github.com/spring-cloud/spring-cloud-openfeign.git && cd spring-cloud-openfeign 

$ git checkout v2.0.0.M1 

$ Install JDK and setup JAVA_HOME. 

$ ./mvnw install 
~~~
  

## Outcome 

Maven build, test and install is successful. 

  

All this information is also added to [Software Ecosystem Dashboard for Arm](https://www.arm.com/developer-hub/ecosystem-dashboard/).

**Comment by OlgaMaciaszek** [comment]
Thanks a lot @odidev .
