### ISSUE TITLE
Spring Cloud OpenFeign 4.1.4 and below is not compatible with Spring Boot 3.4.0

### ISSUE THREAD

**Issue by gexge** [spring-cloud/spring-cloud-openfeign#1132]
**Describe the bug**
Having the following:

```
<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>3.4.0</version>
    <relativePath/> <!-- lookup parent from repository -->
</parent>

<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-openfeign</artifactId>
    <version>4.1.4</version>            
</dependency>
```

**Sample**
```
Caused by: org.springframework.cloud.configuration.CompatibilityNotMetException: Spring Cloud/ Spring Boot version compatibility checks have failed: [[VerificationResult@7ffd4cea description = 'Spring Boot [3.4.0] is not compatible with this Spring Cloud release train', action = 'Change Spring Boot version to one of the following versions [3.2.x, 3.3.x] .
You can find the latest Spring Boot versions here [https://spring.io/projects/spring-boot#learn].
```

**Comment by rhengeveld** [comment]
I have the same issue. 

This can be traced to the `SpringBootVersionVerifier` in [spring-cloud-commons v4.1.5](https://github.com/spring-cloud/spring-cloud-commons/blob/v4.1.5/spring-cloud-commons/src/main/java/org/springframework/cloud/configuration/SpringBootVersionVerifier.java#L39). This has already been fixed [in this commit](https://github.com/spring-cloud/spring-cloud-commons/commit/bf7ddb17f581c9130318e7e945d0e952ba9387bb) tied to v4.2.0-RC1 and can be found on the [main branch](https://github.com/spring-cloud/spring-cloud-commons/blob/main/spring-cloud-commons/src/main/java/org/springframework/cloud/configuration/SpringBootVersionVerifier.java#L38). 

So I'm thinking we need to wait for a `spring-cloud-common` v4.2.0 release

**Comment by JanMosigItemis** [comment]
FYI you may want to include

```
<repositories>
    <repository> 
        <id>repository.spring.milestone</id> 
        <name>Spring Milestone Repository</name> 
        <url>http://repo.spring.io/milestone</url> 
    </repository>
</repositories>
```
and

```
<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
            <version>4.2.0-RC1</version><!--$NO-MVN-MAN-VER$-->
        </dependency>
```

into your build for the time being.

The final release is planned for Dec 5th.
```
