### ISSUE TITLE
Feign: trigger early initialization of Feign clients

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-openfeign#119]
Although Feign client proxy are created during bootstrap, the actual handling chain behind them is created lazily the first time the Feign proxy/client is actually used, i.e. at _runtime_. This lazy init is performed by `CachingLBClientFactory` --> `SpringLBClientFactorty` --> `SpringClientFactory`.

The runtime init may fail because of bad configuration parameters, so I'd like to trigger it early during startup to avoid issues at runtime.
The only solution I found so far is to:
- find beans in the context with the @FeignClient annotation
- get the corresponding serviceId (duplicating the logic found in `FeignClientRegistrar`
- call `CachingLBClientFactory.create(<serviceId>)

Is there any easiest/cleaner way to do it?

**Comment by hqxy** [comment]
Will Springcloud.Finchley.RELEASE still have this problem?

**Comment by OlgaMaciaszek** [comment]
Spring Cloud Finchley is no longer supported and we strongly support upgrading it to Hoxton (Greenwich is no longer supported either). @hqxy Please verify if the issue still occurs in `Hoxton.SR3` (you can also switch to a different LoadBalancer implementation then and, thus, different way of creating Feign LB clients by setting `spring.cloud.loadbalancer.ribbon.enabled` to `false` ). Let me know if that helps.

**Comment by ffyyhh995511** [comment]
i am facing same issue.  my project info is Hoxton.SR9、Supported Boot Version: 2.3.5.RELEASE

**Comment by ffyyhh995511** [comment]
> feign.ribbon.warmup=true

it does not work by spring cloud Hoxton.SR9 and springboot 2.3.5.RELEASE

**Comment by OlgaMaciaszek** [comment]
Closing as issue related to Ribbon, which is no longer supported.
