### ISSUE TITLE
Provide an attribute to ignore certain exceptions for Feign Hystrix support

### ISSUE THREAD

**Issue by asarkar** [spring-cloud/spring-cloud-openfeign#121]
The `@FeignClient` annotation has an attribute `fallback`, named appropriately. It'd be nice to have an attribute `Class<? extends Throwable>[] ignoreExceptions() default {}` that doesn't open the circuit for the exceptions listed. Currently, the workaround is to disable feign support (`feign.hystrix.enabled=false` will do it globally) and annotate the caller of the feign client with `com.netflix.hystrix.contrib.javanica.annotation.HystrixCommand`. This is more code to implement what I assume is a common use case.
Also, if any `ErrorDocoder` is present, `ignoreExceptions` should honor it, that is give the decoder a chance to translate HTTP status code to exceptions.

See the SO thread [here](http://stackoverflow.com/questions/39499973/how-to-fine-tune-the-spring-cloud-feign-client/39517091#39517091) for background.

**Comment by WoojinAhn** [comment]
++

**Comment by spencergibb** [comment]
Hystrix has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
