### ISSUE TITLE
Feign: use parameter name as default for @PathVariable

### ISSUE THREAD

**Issue by chrylis** [spring-cloud/spring-cloud-openfeign#122]
The Feign integration currently requires explicitly specifying the name of an `@PathVariable`. Since interfaces will usually use the same identifier in the URI template and the method signature, it would be convenient to support MVC's behavior of defaulting the `@PathVariable` (and `@RequestParam`) template variables to the parameter name.

**Comment by spencergibb** [comment]
Closing as fixed
