### ISSUE TITLE
Passing decode404 configuration globally using Configuration

### ISSUE THREAD

**Issue by tanmaybinaykiya** [spring-cloud/spring-cloud-openfeign#124]
Is there a way to pass the decode404 property to all FeignClients by instantiating a bean through a configuration class, like it is possible for ErrorDecoder or Contract etc?

**Comment by OlgaMaciaszek** [comment]
@tanmaybinaykiya @matt62king as discussed in https://github.com/spring-cloud/spring-cloud-openfeign/pull/267 what is the use case where that makes more sense as opposed to using the existing `decode404` config property?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by tanmaybinaykiya** [comment]
It's been 3 years since I created the issue. I can't remember what the use case was.
