### ISSUE TITLE
question: Do we need Feign retry?

### ISSUE THREAD

**Issue by eacdy** [spring-cloud/spring-cloud-openfeign#129]
In this post: https://github.com/spring-cloud/spring-cloud-netflix/issues/467 . 

Since we've eliminated the feign retry with our ribbon retry, Do we still need the property below?

    feign:
      client:
        config:
          feignName:
            retryer: com.example.SimpleRetryer

This property is from http://cloud.spring.io/spring-cloud-static/Edgware.M1/#spring-cloud-feign-overriding-defaults .

I think we should delete this property.

ping @spencergibb

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
