### ISSUE TITLE
spring-cloud-starter-openfeign not spring-cloud-openfeign-core dependency

### ISSUE THREAD

**Issue by dragontree101** [spring-cloud/spring-cloud-openfeign#13]
i use `spring-cloud-starter-openfeign` 2.0.0.m2 version

but i not found `spring-cloud-openfeign-core` dependency

mvn dependency:tree

```
[INFO] +- org.springframework.cloud:spring-cloud-starter-openfeign:jar:2.0.0.M2:compile
[INFO] |  +- org.springframework.cloud:spring-cloud-starter:jar:2.0.0.M9:compile
[INFO] |  |  +- org.springframework.cloud:spring-cloud-context:jar:2.0.0.M9:compile
[INFO] |  |  \- org.springframework.security:spring-security-rsa:jar:1.0.5.RELEASE:compile
[INFO] |  |     \- org.bouncycastle:bcpkix-jdk15on:jar:1.56:compile
[INFO] |  +- org.springframework.cloud:spring-cloud-netflix-core:jar:2.0.0.M8:compile
[INFO] |  +- org.springframework.cloud:spring-cloud-commons:jar:2.0.0.M9:compile
[INFO] |  |  +- org.springframework.security:spring-security-crypto:jar:5.0.3.RELEASE:compile
[INFO] |  |  \- org.apache.httpcomponents:httpclient:jar:4.5.5:compile
[INFO] |  |     \- org.apache.httpcomponents:httpcore:jar:4.4.9:compile
[INFO] |  +- io.github.openfeign:feign-core:jar:9.5.1:compile
[INFO] |  +- io.github.openfeign:feign-slf4j:jar:9.5.1:compile
[INFO] |  +- io.github.openfeign:feign-hystrix:jar:9.5.1:compile
[INFO] |  |  +- com.netflix.archaius:archaius-core:jar:0.7.5:compile
[INFO] |  |  |  \- com.google.code.findbugs:jsr305:jar:3.0.1:runtime
[INFO] |  |  \- com.netflix.hystrix:hystrix-core:jar:1.5.12:compile
```

spring-cloud-starter-openfeign's pom.xml
```
<parent>
		<groupId>org.springframework.cloud</groupId>
		<artifactId>spring-cloud-starter-netflix</artifactId>
		<version>2.0.0.M2</version>
	</parent>
	<artifactId>spring-cloud-starter-openfeign</artifactId>
	<name>Spring Cloud Starter OpenFeign</name>
	<description>Spring Cloud Starter OpenFeign</description>
	<url>https://projects.spring.io/spring-cloud</url>
	<organization>
		<name>Pivotal Software, Inc.</name>
		<url>https://www.spring.io</url>
	</organization>
	<properties>
		<main.basedir>${basedir}/../../..</main.basedir>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-netflix-core</artifactId>
		</dependency>
  ...
```

**Comment by ryanjbaxter** [comment]
Seems to be there to me https://github.com/spring-cloud/spring-cloud-openfeign/blob/v2.0.0.M2/spring-cloud-starter-openfeign/pom.xml#L28

**Comment by dragontree101** [comment]
it is real wried, i found pom.xml from my mvn repository

```
cat ~/.m2/repository/org/springframework/cloud/spring-cloud-starter-openfeign/2.0.0.M2/spring-cloud-starter-openfeign-2.0.0.M2.pom
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.cloud</groupId>
		<artifactId>spring-cloud-starter-netflix</artifactId>
		<version>2.0.0.M2</version>
	</parent>
	<artifactId>spring-cloud-starter-openfeign</artifactId>
	<name>Spring Cloud Starter OpenFeign</name>
	<description>Spring Cloud Starter OpenFeign</description>
	<url>https://projects.spring.io/spring-cloud</url>
	<organization>
		<name>Pivotal Software, Inc.</name>
		<url>https://www.spring.io</url>
	</organization>
	<properties>
		<main.basedir>${basedir}/../../..</main.basedir>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-netflix-core</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-commons</artifactId>
		</dependency>
		<dependency>
			<groupId>io.github.openfeign</groupId>
			<artifactId>feign-core</artifactId>
		</dependency>
		<dependency>
			<groupId>io.github.openfeign</groupId>
			<artifactId>feign-slf4j</artifactId>
		</dependency>
		<dependency>
			<groupId>io.github.openfeign</groupId>
			<artifactId>feign-hystrix</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-netflix-ribbon</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-netflix-archaius</artifactId>
		</dependency>
	</dependencies>
</project>
```

**Comment by ryanjbaxter** [comment]
Not sure what we can do about it

**Comment by dragontree101** [comment]
i don't know why this pom.xml is error 
different from  https://github.com/spring-cloud/spring-cloud-openfeign/blob/v2.0.0.M2/spring-cloud-starter-openfeign/pom.xml

**Comment by ryanjbaxter** [comment]
There might be some weird caching stuff going on locally.  The starter existed as part of the netflix project before we separated things out and there was an M2 release when it was part of the netflix project.  Now there has been an M2 release since it was separated out.

I just checked the repo on repo.spring.io and it exists there and looks good
http://repo.spring.io/libs-milestone-local/org/springframework/cloud/spring-cloud-starter-openfeign/2.0.0.M2/spring-cloud-starter-openfeign-2.0.0.M2.pom

I suggest clearing your local maven repo and pulling down the dependencies again.

**Comment by dragontree101** [comment]
maybe my nexus repo has some bug， pom.xml down load from my nexus repo， and nexus repo has error pom.xml ， i remove my nexus repo, build is ok

thanks!

**Comment by gamb79** [comment]
For people coming here for the same fault. There is a wrong artifact in the JBoss Nexus repo: http://repository.jboss.org/nexus/content/groups/public
Make sure U use the Spring Milestones repo.

**Comment by travellertime** [comment]
I got same problem when i use other repo. Issue will be fixed after remove it and download from official repo again. It's repo issue, but not an issue of openfeign.

**Comment by hazsetata** [comment]
Ran into this same problem, and I'm not using JBoss's repo. For me the spring-cloud-starter-openfeign-2.0.0.M2.jar comes from here, and it contains the wrong POM file: 

http://repo.spring.io/libs-release/org/springframework/cloud/spring-cloud-starter-openfeign/2.0.0.M2/spring-cloud-starter-openfeign-2.0.0.M2.jar

According to http://repo.spring.io the two files in libs-release and in libs-milestone are different (different hashes). I use the following Gradle setup:
    repositories {
        jcenter()
        maven { url "http://repo.spring.io/libs-release" }
        maven { url "http://repo.spring.io/libs-milestone" }
        maven { url "http://repo.spring.io/libs-snapshot" }
        maven { url "https://repo.spring.io/milestone" }
        maven { url "https://repo.spring.io/snapshot" }
    }
... which prefers libs-release over libs-milestone (as it should be in my opinion). As it is a milestone release, could it be removed from lib-release?

**Comment by ryanjbaxter** [comment]
Should be removed now

**Comment by hazsetata** [comment]
@ryanjbaxter Yes it works now. Thanks a lot for your help!

**Comment by Akshatha-M-B** [comment]
I encountered this error its easy to remove that
just right click on springbootproject-->spring-->addstarters-->checkon openfeign.
