### ISSUE TITLE
@FeignClient should support ignoreExceptions 

### ISSUE THREAD

**Issue by vasilievip** [spring-cloud/spring-cloud-openfeign#130]
If I use status 400 to handle "invalid input", with @HystrixCommand I'm able to specify set of exceptions (assuming custom error decoder) to be treated as "handled" and they won't break the circuit. With use of  HystrixFeign.builder I have to remove @HystrixCommand and I do not see the way to specify my custom exceptions as well as how to specify that http 400 should not break circuit.

**Comment by OlgaMaciaszek** [comment]
Closing as Hystrix is no longer supported.
