### ISSUE TITLE
Unable to set RetryHandler for LBClient when using Feign

### ISSUE THREAD

**Issue by marcolenzo** [spring-cloud/spring-cloud-openfeign#131]
I want to be able to set the `MaxAutoRetriesNextServer`  which is used when executing a `LoadBalancerCommand`. In my scenario, several instances of the same service might be put out of rotation simultaneously and I want the software load balancer to keep retrying until it finds an available server. 

My target service name is _quote-service_ and in my `application.yml` I have the following properties (inflated on purpose):

```
quote-service:
  ribbon:
    OkToRetryOnAllOperations: true
    MaxAutoRetriesNextServer: 50
    MaxAutoRetries: 50
```

Whenever I invoke my feign client instance, the `feign.ribbon.RibbonClient.execute(Request, Options)` is eventually invoked which in turn requests a vanilla `LBClient`. This is fetched through the Spring Cloud factories `CachingLBClientFactory` and `SpringLBClientFactory`.

The problem I see here is that LBClient constructor always sets a default RetryHandler.

``` java
LBClient(ILoadBalancer lb, IClientConfig clientConfig) {
        super(lb, clientConfig);
    this.setRetryHandler(RetryHandler.DEFAULT);
    this.clientConfig = clientConfig;
    connectTimeout = clientConfig.get(CommonClientConfigKey.ConnectTimeout);
    readTimeout = clientConfig.get(CommonClientConfigKey.ReadTimeout);
  }
```

The default retry handler is eventually fetched when trying to get a request specific retry handler (as done in `com.netflix.client.AbstractLoadBalancerAwareClient.executeWithLoadBalancer(S, IClientConfig)` and client configuration is completely ignored:

``` java
  @Override
  public RequestSpecificRetryHandler getRequestSpecificRetryHandler(
      RibbonRequest request, IClientConfig requestConfig) {
    if (clientConfig.get(CommonClientConfigKey.OkToRetryOnAllOperations, false)) {
      return new RequestSpecificRetryHandler(true, true, this.getRetryHandler(), requestConfig);
    }
    if (!request.toRequest().method().equals("GET")) {
      return new RequestSpecificRetryHandler(true, false, this.getRetryHandler(), requestConfig);
    } else {
      return new RequestSpecificRetryHandler(true, true, this.getRetryHandler(), requestConfig);
    }
  }
```

I tried to overcome this issues by defining my own `@RibbonClient` but it is completely ignored. I honestly have no idea how to address this. I assume I should somehow be able to populate the `CachingLBClientFactory` with global or service specific LBClient but I don't see a way to achieve this.

**Comment by ryanjbaxter** [comment]
Can you please try with the latest Spring Cloud release?  The retry functionality has been completely rewritten since this issue was opened?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
