### ISSUE TITLE
Ability to configure Target implementation used by FeignClientFactoryBean

### ISSUE THREAD

**Issue by xyloman** [spring-cloud/spring-cloud-openfeign#133]
We have a few use cases where a custom Target implementation would be necessary to gain access to the Request to add a header.  We found that using the feign.RequestInterceptor had a short coming in that it does not expose the target url that is either load balanced to or hard coded until after the apply is executed line 164 in the SynchronousMethodHandler.  We are requiring the full URL in order to generate an OAuth 1.0a secured request to populate the Authorization header.   We were able to work around this issue by using the Feign builder with a custom implementation of Target (see https://github.com/Netflix/feign#multiple-interfaces) explicitly instead of the annotation + FeignClientFactoryBean.  I am not completely familiar with the FeignClientFactoryBean but it does appear that it could expose an additional autowired bean for the target to use but I might be over looking a different approach.  I found a conversation on the feign github that is similar https://github.com/Netflix/feign/issues/214.

**Comment by ryanjbaxter** [comment]
Is this solved by this? http://cloud.spring.io/spring-cloud-static/Greenwich.RELEASE/single/spring-cloud.html#_creating_feign_clients_manually

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
