### ISSUE TITLE
Upgrade to openfeign 10.2.3

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-openfeign#136]
https://github.com/OpenFeign/feign/releases/tag/10.2.0

**Comment by spencergibb** [comment]
Minor needs to wair for Hoxton

**Comment by JBertaux** [comment]
`feign-core` in version 10.2.0 fixes a [bug](https://github.com/OpenFeign/feign/pull/882) for the encoding of some characters like the '+'. Have you an idea of when you will upgrade ? Thanks

**Comment by ryanjbaxter** [comment]
It will be part of our Hoxton Release, for release dates please see https://github.com/spring-cloud/spring-cloud-release/milestones

**Comment by kdavisk6** [comment]
@spencergibb  and @ryanjbaxter, we just release 10.2.3, with additional bug fixes reported by @OlgaMaciaszek.  I recommend using that version.

https://github.com/OpenFeign/feign/releases/tag/10.2.3

**Comment by OlgaMaciaszek** [comment]
Yes @kdavisk6 , I am planning on upgrading it this week. It will fix https://github.com/spring-cloud/spring-cloud-openfeign/issues/143

**Comment by OlgaMaciaszek** [comment]
Done in gh-185.
