### ISSUE TITLE
Method SpringMvcContract.addTemplatedParam  not found

### ISSUE THREAD

**Issue by Ravis22** [spring-cloud/spring-cloud-openfeign#138]
I am using spring boot 2.0.1.RELEASE with <spring-cloud.version>Finchley.RC1</spring-cloud.version>
When using FeignClient with below definition it throws error:
void registerUser(@RequestBody Object dto, @RequestHeader("X-Token") String token);

It throws error:
Caused by: java.lang.NoSuchMethodError: org.springframework.cloud.openfeign.support.SpringMvcContract.addTemplatedParam(Ljava/util/Collection;Ljava/lang/String;)Ljava/util/Collection;

I saw another [issue](https://github.com/spring-cloud/spring-cloud-openfeign/issues/87)  where similar issue is reported. But this is related to version 2.1.0. Whereas I am using 2.0.1.

Kindly suggest.

**Comment by spencergibb** [comment]
Please try with Finchley.SR2

**Comment by Ravis22** [comment]
I found the issue was Introduced after adding a new dependence of open-feign v3.5. That internally had dependency on feign-core10.x. After lowering the version of open-feign. The error was resolved. 

Thanks for your thouhgts.
