### ISSUE TITLE
Get the integer type of LinkedHashMap from the long type of HashMap ?

### ISSUE THREAD

**Issue by wangnanyang** [spring-cloud/spring-cloud-openfeign#139]
I use Edgware.SR5 version of spring cloud framework, 1.5.9.RELEASE version of spring boot framework, and the service provider interacts with consumers using the List < Map < String, Object > return value result set. The problem is that the long in map < String, Object > is converted to integer, that is, result. get (0). get ("count"). getClass () is the integer type from the long at the service provider to the service consumer. How can I solve this problem? Thank you!
```
@GetMapping("/report/common/data/search")
public List<Map<String, Object>> searchSaleReport(@RequestParam("param") String param) {
return saleReportService.searchSaleReport(param);
}

@FeignClient("${sale.feign.name}")
public interface SaleReportService {
@GetMapping("/report/common/data/search")
List<Map<String, Object>> searchSaleReport(@RequestParam("param") String param);
}
```

**Comment by spencergibb** [comment]
I'm not sure there is anything we can do here. This is all done by spring framework codecs. Because you don't have specific types and are using a map, it's making a guess. To work around this use a specific type rather than map.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
