### ISSUE TITLE
replace FeignClientsRegistrar implement

### ISSUE THREAD

**Issue by EightMonth** [spring-cloud/spring-cloud-openfeign#169]
hi 
  I have a problem: I want to use spring-cloud-openfeign and customize feign client. but i cant make it now. because i cant replace FeignClientsRegistrar  in  @EnabledFeignClients with my FeignClientsRegistrar . so maybe you can provider a way to do it.

Best Regards
Eightmonth

**Comment by spencergibb** [comment]
That class isn't replaceable. Either [create feign clients manually](https://cloud.spring.io/spring-cloud-static/Greenwich.RELEASE/single/spring-cloud.html#_creating_feign_clients_manually) or create your own annotation instead of `@EnabledFeignClients`.

**Comment by EightMonth** [comment]
yes, i think so , but its so hard to do this solution in company.

**Comment by spencergibb** [comment]
So, lets back up and tell me why you want your own `FeignClientsRegistrar`?

**Comment by EightMonth** [comment]
i want to customize feign client and use spring-cloud-openfeign

**Comment by spencergibb** [comment]
We have all sorts of ways to customize feign clients, you'll have to be more specific.

**Comment by EightMonth** [comment]
Enhance zipkin trace to method level
feign request url just known the url which one is the service
but dont know which method to be call.
i wannna init method info to feign client when building feign client
