### ISSUE TITLE
Spring Data Pageable is not working when using SNAKE_CASE as property naming strategy

### ISSUE THREAD

**Issue by hello-xhemajl** [spring-cloud/spring-cloud-openfeign#170]
It is nice to see that feign now includes support for Spring Data Pageable. However, on our team we have set `SNAKE_CASE` as the jackson property naming strategy, for the whole app, and the feature does not work correctly because of it.

I have tried to write a minimal, complete and verifiable example to reproduce the problem.
The example includes "mapping `totalElements` attribute of `Page`" test, that fail when  `SNAKE_CASE` naming strategy is used:
https://github.com/hello-xhemajl/feign-page-mapping-tests.git

It would be appreciated if feign would also support this case.

**Comment by ryanjbaxter** [comment]
I wonder if you are setting the naming strategy too late, can you try setting the property `spring.jackson.property-naming-strategy` instead and see if that works?

**Comment by hello-xhemajl** [comment]
No, even if the property naming strategy is set using `spring.jackson.property-naming-strategy`   at application.properties, mapping of `total_elements` attribute fails.

Looking at `SimplePageImpl`, at #103, I can see `@JsonProperty("totalElements") long totalElements`
Does this mean that this does only handle mapping for `spring.jackson.property-naming-strategy=LOWER_CAMEL_CASE`?
