### ISSUE TITLE
hystrix: can not get the right fallback instance

### ISSUE THREAD

**Issue by jojo921** [spring-cloud/spring-cloud-openfeign#173]
```version: 2.1.0```
```feign.hystrix.enabled: true```

```
@FeignClient(contextId = "foo-FooClient", name = "foo",
    configuration = FooClientConfiguration.class, fallback = FooClientFallback.class)
public interface FooClient {

  @GetMapping("foo")
  String foo();

}


@Configuration  // here configuration only be loaded into ApplicationContext corresponding to the contextId
public class FooClientConfiguration {

  @Bean
  public FooClientFallback fooClientFallback(){
    return new FooClientFallback();
  }

}


public class FooClientFallback implements FooClient {

  @Override
  public String foo() {
    return "foo:fallback";
  }
}
```

Caused by: java.lang.IllegalStateException: No fallback instance of type class outside.client.FooClientFallback found for feign client foo

I am trying to diagnose this problem. I find contextId attribute of the @FeignClient annotationis has changed the name of the ApplicationContext ensemble after upgrading to 2.1.0,
but the corresponding target function in  HystrixTargeter.class still use the ApplicationContext expressed by the name attribute of the @FeignClient to get fallback instance.

source code：https://github.com/spring-cloud/spring-cloud-openfeign/blob/aba2abba8a0c651e3c539123e43429bf2083bb50/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/HystrixTargeter.java#L46

 ```

@Override
	public <T> T target(FeignClientFactoryBean factory, Feign.Builder feign, FeignContext context,
						Target.HardCodedTarget<T> target) {
		if (!(feign instanceof feign.hystrix.HystrixFeign.Builder)) {
			return feign.target(target);
		}
		feign.hystrix.HystrixFeign.Builder builder = (feign.hystrix.HystrixFeign.Builder) feign;
		SetterFactory setterFactory = getOptional(factory.getName(), context,
			SetterFactory.class);
		if (setterFactory != null) {
			builder.setterFactory(setterFactory);
		}
		Class<?> fallback = factory.getFallback();
		if (fallback != void.class) { // I think 'factory.getName()' should be replaced with 'factory.getContextId' here
			return targetWithFallback(factory.getName(), context, target, builder, fallback);
		}
		Class<?> fallbackFactory = factory.getFallbackFactory();
		if (fallbackFactory != void.class) { // the same above
			return targetWithFallbackFactory(factory.getName(), context, target, builder, fallbackFactory);
		}

		return feign.target(target);
	}
```

as a contrast：

https://github.com/spring-cloud/spring-cloud-openfeign/blob/75faca6c17181e27692205c34928298de73591ea/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientFactoryBean.java#L228-L230

### here is a complete [example](https://github.com/jojo921/openfeign-issues-173) which can reproduce this problem

**Comment by ryanjbaxter** [comment]
You need to specify the fallback in the annotation.
http://cloud.spring.io/spring-cloud-static/Greenwich.SR1/single/spring-cloud.html#spring-cloud-feign-hystrix-fallback

**Comment by jojo921** [comment]
@ryanjbaxter thank you for pointing out the mistake , I omit the fallback just in the demo and I re-edit the issue，the problem still exits.

**Comment by jojo921** [comment]
@ryanjbaxter 
some details:
spring boot 2.1.x : Bean overriding has been disabled by default。
openfeign 2.1.0:   add contextId attribute
1.if multiple @FeignClient with the same name but without specifing the contexId exist, BeanDefinitionOverrideException will be throwed (https://github.com/spring-cloud/spring-cloud-openfeign/blob/aba2abba8a0c651e3c539123e43429bf2083bb50/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientsRegistrar.java#L389)
2.when specifing the contexId,  BeanDefinitionOverrideException can be solved
but the fallback instance (like BarHttpClientFallBack defined in BarClientConfiguration) will not be gained，because hystrixTargeter still get this fallback instance from the context corresponding the name attribute (https://github.com/spring-cloud/spring-cloud-openfeign/blob/aba2abba8a0c651e3c539123e43429bf2083bb50/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/HystrixTargeter.java#L77)

**Comment by ryanjbaxter** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by jojo921** [comment]
@ryanjbaxter [sample](https://github.com/jojo921/openfeign-issues-173)

**Comment by lmx1989219** [comment]
@jojo921 i see you code in your sample. 
i found the problem
like this
`@SpringBootApplication(scanBasePackages = "outside.client")`

Otherwise the fallback bean not be managed by spring.

**Comment by jojo921** [comment]
@lmx1989219 I think you don't find out the nature of this issue, or maybe I describe the problem clearly enough，but I prefer the former. The solution you provide  just works around it，but not solves
it，and I always know it, however, in some cases,  I can't use this solution.  About the question you mentioned  that  the fallback bean not be managed by spring，I think it does not exit，because the fallback bean is defined in FooClientConfiguration，so it would be managed by spring.

**Comment by gdong42** [comment]
We're seeing this issue as well while trying to upgrade to Spring Cloud Finchley. This prevents us from upgrading, any workaround?

**Comment by ScienJus** [comment]
Hi @lmx1989219, @ryanjbaxter, I think @jojo921 is right.

Take a look at the `getOptional` of `FeignClientFactoryBean`, which uses `contextId` to get the instance from context.

https://github.com/spring-cloud/spring-cloud-openfeign/blob/75faca6c17181e27692205c34928298de73591ea/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientFactoryBean.java#L228-L230

But why is the `name` used in `HystrixTargeter`?

https://github.com/spring-cloud/spring-cloud-openfeign/blob/aba2abba8a0c651e3c539123e43429bf2083bb50/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/HystrixTargeter.java#L94-L97

**Comment by Imccccc** [comment]
We experience the same problem

**Comment by jskim1991** [comment]
@ryanjbaxter I am not sure if this issue needs to be worked on or not. It seems to me that #67 introduced contextId in FeignClientFactoryBean but the use of contextId did not end up in other parts such as Hystrix

**Comment by ryanjbaxter** [comment]
@jskim1991 @gdong42 @Imccccc @jojo921 can someone provide a sample that does not use consul, that doesnt seem to be required here

**Comment by jskim1991** [comment]
@jojo921 @gdong42 @lmccccc  I tried to reproduce your problem and for me, whether I specify contextId or not, it resulted in BeanDefinitionOverrideException using multiple feign clients. @ryanjbaxter I do believe there is something wrong with this. I think the problem statement is simple that using multiple feign clients from one service results in errors (BeanDefinitionOverrideException for sure and maybe more since Hystrix does not make use of contextId?)
example : https://github.com/jskim1991/feign-tester-forj

**Comment by gdong42** [comment]
> @jskim1991 @gdong42 @Imccccc @jojo921 can someone provide a sample that does not use consul, that doesnt seem to be required here

Sure, please check out [this demo](https://github.com/gdong42/feign-demo) (only JDK is required). Just reproduce it with simply running:

```bash
$ ./mvnw clean spring-boot:run
```
