### ISSUE TITLE
The post request parameter no add http request body

### ISSUE THREAD

**Issue by Wislove** [spring-cloud/spring-cloud-openfeign#174]
hi !
I have a promble when use feign to invoke a third API.  third API Server side is php. can't receive parameter before I add RequestInterceptor.  

I find feign send http post request when Content-Type is application/x-www-form-urlencoded the http request body is null. Java Web receive parameter is ok. but php server side receive paramter have pormble. must add RequestInterceptor set parameter in body.

my version:  
>spring-cloud-open-feign  2.0.1 RELEASE
>feign-core: 9.5.1

my code 
```
@FeignClient(name = "safetyPowerClient", url = "${myurl}", configuration = SafetyPowerClient.FeignSupportConfig.class)
public interface SafetyPowerClient {

    @Configuration
    class FeignSupportConfig {
        @Bean
        public RequestInterceptor interceptor() {
            return requestTemplate -> {
                    requestTemplate.body(requestTemplate.queryLine().replace("?", ""));
            };
        }
    }
   
    @PostMapping(value = "/API/v1/login.php", consumes = MediaType.APPLICATION_FORM_URLENCODED_VALUE)
    String login(@RequestParam("name") String name, @RequestParam("pwd") String pwd);
}
```
I think feign can provider a feature  let developer determine whether add parameter to http request body

**Comment by ryanjbaxter** [comment]
You should be using the `@RequestBody` annotation in the method signature

**Comment by Wislove** [comment]
I try it like below

-  First Way:
```
@PostMapping(value = "/API/v1/user/check_log.php", consumes = MediaType.APPLICATION_FORM_URLENCODED_VALUE)
String login(@RequestBody String name, @RequestBody String pwd);
```
But it will cause exception when spring boot start 
> Caused by: java.lang.IllegalStateException: Method has too many Body parameters

- Second Way :
```
@Data
@AllArgsConstructor
public class SafetyPowerLoginParams {

    private String name;

    private String pwd;
}

@PostMapping(value = "/API/v1/user/check_log.php", consumes = MediaType.APPLICATION_FORM_URLENCODED_VALUE)
String login(@RequestBody SafetyPowerLoginParams params);
```
But this will cause a exception too when invoke the method
> feign.codec.EncodeException: Could not write request: no suitable HttpMessageConverter found for request type [com.rcsit.feign.esafety.entity.SafetyPowerLoginParams] and content type [application/x-www-form-urlencoded]

The third API recieve content type is [application/x-www-form-urlencoded] not [application/json]. It not work using `@RequestBody` annotation

**Comment by OlgaMaciaszek** [comment]
Yes, you can't have two `@RequestBody` elements. The second option should work. Try adding explicit public getters and setters.
Alternatively, you could just use `@RequestBody String body` and serialize json on your end.
 If you still have an issue after trying that, please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by Wislove** [comment]
I use `@RequestBody String body`  in FeginClient 
```
@PostMapping(value = "/API/v1/user/check_log.php", consumes = MediaType.APPLICATION_FORM_URLENCODED_VALUE)
String login(@RequestBody String params);
```
But I must set `params` equals `key=value&key=value` it will work well

```
String result = "";
String params1 = "name=myName&pwd=1234";
result = feginClient.login(params1); // success feedback

String params2 = "{\"name\":\"myName\",\"pwd\":\"1234\"}";
result = feginClient.login(params2); // error feedback
```


My problem is when I first use the fegin normal way like below to invoke a third API. It not work. The third can't receive parameter. I must add the parameter in request body like `key=value&key=value`.So I use `RequestInterceptor ` add parameter in request body like `key=value&key=value`. Also you provide another way  use `@RequestBody String body`. But It also must set parameter like `key=value&key=value`  not a json string. So I hope Feign can support add parameter auto like  `key=value&key=value` in request body when I send a `[application / x-www-form-urlencoded]` POST request 
```
// This way not work. This way not set parameter in request body like key=value&key=value
@FeignClient(name = "safetyPowerClient", url = "${myurl}")
public interface SafetyPowerClient {
   
    @PostMapping(value = "/API/v1/login.php", consumes = MediaType.APPLICATION_FORM_URLENCODED_VALUE)
    String login(@RequestParam("name") String name, @RequestParam("pwd") String pwd);
}
```

**Comment by jojo921** [comment]
You should be using the @RequestBody annotation in the method signature, and you need define [FormEncoder](https://stackoverflow.com/questions/42427639/how-to-send-post-request-by-spring-cloud-feign) in your configuration (like SafetyPowerClient.FeignSupportConfig.class), which is why your second way throws exception

**Comment by OlgaMaciaszek** [comment]
Ok @Wislove I didn't understand you wanted to send it as `form-encoded` type, which, of course, you need to do, if that's what your server consumes. It should work if you apply the suggestion that @jojo921  has provided.

**Comment by Wislove** [comment]
Ok it means it not `form-encoded` type  when I use `@PostMapping` and `@RequestParam` annotation in the method signature. So I can't use '@RequestParam' annotation. I must  define  a `FormEncoder` or `RequestInterceptor `.
