### ISSUE TITLE
Replacement for Ribbon LB

### ISSUE THREAD

**Issue by ArtyomGabeev** [spring-cloud/spring-cloud-openfeign#177]
**Enhancement**

As I understand, currently feign supports only Ribbon as client side loadbalancer, which is tight to Eureka. 

Since we introduced DiscoveryClient interface, which may be k8s, predefined, etc and have clean interfaces like LoadBalancerClient/ServiceInstanceChooser and ReactiveLoadBalancer,
I think it will be nice to have at least Round Robin LB based on high level DiscoveryClient.

It will allows us to choose between different discovery mechanisms (I'm currently interested in k8s discovery) and provide a basic LB support for feign.

Questions:
1. is it something already supported?
2. Is it in cloud openfeign roadmap? If yes or we are interested in it, I may try to contribute.

Thanks

**Comment by OlgaMaciaszek** [comment]
Hi @ArtyomGabeev This is a valid issue and a topic that has yet to be evaluated by the team, probably following a discussion and decisions on Ribbon replacement for the entire Spring Cloud stack (that's the issue to observe on this: https://github.com/spring-cloud/spring-cloud-commons/issues/553 ). Once there's an alternative chosen/ created, we would have to provide it for our OpenFeign integration as well. If you're interested in working on this bit, we will be happy to get the contribution. Will get back to you after we've done some progress on the other issue.

**Comment by Glosur** [comment]
Hey,

Is it something planned ?
I'd like to work on that if needed

**Comment by OlgaMaciaszek** [comment]
Hi @Glosur . yes, we've merged a PR providing our own non-reactive LB client:
https://github.com/spring-cloud/spring-cloud-commons/issues/553 . One of the things I will be doing for Hoxton M3 is switching to it wherever we used Ribbon, but there's a lot of work and help is definitely welcome. Would you like to work on doing that for OpenFeign?

**Comment by Glosur** [comment]
Thanks for the anwser @OlgaMaciaszek 

I'd like to give it a try ! Any advice for this ?

**Comment by OlgaMaciaszek** [comment]
Hi @Glosur - please let me know if you are going to work on it. If not, I will get it done soon.

**Comment by Glosur** [comment]
Hello !

I started looking at the code a bit but my computer died yesterday. No problem if you get it done, I'll look at how you will do it 

Sylvain

**Comment by OlgaMaciaszek** [comment]
Ok. Will work on it now.
