### ISSUE TITLE
@RequestParam with parentheses in name, does not work

### ISSUE THREAD

**Issue by butzy92** [spring-cloud/spring-cloud-openfeign#179]
Hello, I need to call an endpoint mapped like this:

http://url/resource?filter[param]=some-value

When I call like this: 

@GetMapping("/resource")
ResponseObject getResource(@RequestParam("filter[param]") String param);

but some how the request param value is request param name. This is the output from log

GET http://url/resource?filter%5Bparam%5D=%7Bfilter%5Bparam%5D%7D

**Comment by ryanjbaxter** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by butzy92** [comment]
I made a quick project in order to demonstrate the bug. If you follow the logs you will see the computed url. https://github.com/butzy92/DemoExampleOpenFeign

**Comment by yanjuning** [comment]
refer https://github.com/OpenFeign/feign/issues/894.
openfeign resolves {filter[param]}  as Literal.

**Comment by kdavisk6** [comment]
This should be fixed in OpenFeign 10.2.3, which is part of #185 I believe.
