### ISSUE TITLE
when Feign Service is closing,throwing a exception:BeanCreationNotAllowedException

### ISSUE THREAD

**Issue by jiyong101** [spring-cloud/spring-cloud-openfeign#18]
when I use STS develop a Feign-Service,if I do what it is a run-as Spring-boot-App。the console will show a error this it is a exception:
org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'eurekaAutoServiceRegistration': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
but I do  what it is a run-as Java Application，the error is nothing.
I don't understand what the reason is.,please help me

**Comment by ryanjbaxter** [comment]
Please learn how to [format code on GitHub](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

Not sure either, sounds like it might be something corrupt in your STS environment, especially is the same app runs fine elsewhere.  If you can provide a project to reproduce the problem I would be happy to try it on my machine as well.
