### ISSUE TITLE
Spring Data Pageable with PageableDefault

### ISSUE THREAD

**Issue by gauravvarma** [spring-cloud/spring-cloud-openfeign#182]
Referring to my question on [stackoverflow ](https://stackoverflow.com/questions/56021307/spring-data-pageable-not-supported-as-requestparam-in-feign-client) 

I have been trying to expose a Feign Client for my rest api. It takes Pageable as input and has PageDefaults defined:

```
    @GetMapping(value = "data", produces = MediaType.APPLICATION_JSON_VALUE)
     	@ApiOperation(value = "Get Data", nickname = "getData")
     	public Page<Data> getData(@PageableDefault(size = 10, page = 0) Pageable page,
     			@RequestParam(value = "search", required = false) String search) {
   		return service.getData(search, page);
     	}

```
And here is my feign client:

```
     @RequestMapping(method = RequestMethod.GET, value = "data")
     	public Page<Data> getData(@RequestParam(name = "pageable", required = false) Pageable page,
     			@RequestParam(name = "search", defaultValue = "null", required = false) String search);
```

Now the problem is regardless of whatever page size and page number I send to Feign Client it always applies PageDefaults (0,10).

When I call the rest service directly it works:
http://localhost:8080/data?size=30&page=6

I am using Spring Boot 2.1.4.RELEASE and Spring Cloud Greenwich.SR1. [Recently a fix was done to support Pageable]((https://github.com/spring-cloud/spring-cloud-openfeign/issues/26#issuecomment-483689346). 

However I am not sure if using Pageable as RequestParam with PageDefault is supported yet.

**Comment by OlgaMaciaszek** [comment]
yes, it won't work as `@RequestParam` as of now, you can pass plain pageable object in your Feign client, however, like so:

```java
@RequestMapping(value = "invoicesPaged", method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE)
	ResponseEntity<Page<Invoice>> getInvoicesPaged(
			org.springframework.data.domain.Pageable pageable);
```
Is this helpful?

**Comment by gauravvarma** [comment]
Thank you. It works without @RequestParam
