### ISSUE TITLE
Customized fallback or fallbackFactory should be allowed to replace the default

### ISSUE THREAD

**Issue by lw5946** [spring-cloud/spring-cloud-openfeign#184]
I don't want to define a fallBack for every FeignClient.

In FeignClientFactoryBean.java, the default fallback is void.class, the default fallbackFactory is void.class.

I need a way to replace the default with a customized fallback.

**Comment by luryson** [comment]
I also need to create some feign clients manually. But `FeignClientBuilder.Builder`'s methods are all not generic. Additionally, `fallback()` and `fallbackFactory()` should pass `Class<?>` maybe.
