### ISSUE TITLE
Feign client options timeout not updating properly

### ISSUE THREAD

**Issue by PrashanthVenkatesan** [spring-cloud/spring-cloud-openfeign#188]
Feign client options updates only if both connectTimeout and readTimeout provided? If either one property is missed, then feign client takes default value for timeout.

In local feign-client properties file, I mentioned
`feign.client.config.foo.connect-timeout=15000`

Although I updated the connect-timeout, I encountered feign-client takes default connect & read timeout.

Later, I added read-timeout also in properties file. Then it took provided values.
```
// This code from class FeignClientFactoryBean#155 
if (config.getConnectTimeout() != null && config.getReadTimeout() != null) {
// This code updates options only if both timeout is not null in configuration.
}
```
I expect even if I give one of the property it should be updated. Please correct me if I am wrong.

**Comment by ryanjbaxter** [comment]
Looks like it is a limitation of the `Options` class in OpenFeign which only has a constructor that takes both a read and connect timeout

https://github.com/OpenFeign/feign/blob/master/core/src/main/java/feign/Request.java#L227

We would need a change in OpenFeign first before we could support this.
