### ISSUE TITLE
@RequestBody(requried = false) not work with spring-cloud-openfeign

### ISSUE THREAD

**Issue by Flamingo93** [spring-cloud/spring-cloud-openfeign#190]
In spring mvc, we can use @RequestBody(requried = false) when the requestbody is optional, but spring-cloud-openfeign add an argument check to ensure the requestbody is not null. So we cannot use @RequestBody(requried = false), is there any plan to deal with the problem?

**Comment by spencergibb** [comment]
Yet another reason you should not share feign interfaces with a server. You should just have another feign interface method.

There is no plan to deal with it.
