### ISSUE TITLE
when I use openfeign do a get request method with same POJO, feign product different url

### ISSUE THREAD

**Issue by eyison** [spring-cloud/spring-cloud-openfeign#192]
when I use openfeign do a get request method with same POJO, feign product different url

feign producer controller
```
@RequestMapping("users")
@RestController
public class UserController {

    @GetMapping(value = "/_search")
    public ResponseEntity<List<UserVo>> search(UserVo userVo) {

        UserVo user = new UserVo(){{
            setUserName("producer_"+userVo.getUserName());
            setUserId(userVo.getUserId());
        }};

        return ResponseEntity.ok().body(Arrays.asList(user));
    }
}
```

UserVo
```
public class UserVo {

    private Long userId;
    private String userName; 

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    } 

    @Override
    public String toString() {
        return "UserVo{" +
                "userId=" + userId +
                ", userName='" + userName + '\'' +
                '}';
    }
}
```

consumer feign client
```
@FeignClient(name = "feign-producer")
public interface UserClient {
 
    @GetMapping(value = "users/_search")
    ResponseEntity<List<UserVo>> search(@SpringQueryMap UserVo userVo);

}
```

consumer controller
```
@RequestMapping("users")
@RestController
public class UserController {

    @Autowired
    private UserClient userClient;

   @GetMapping(value = "/_search1")
    public ResponseEntity<List<UserVo>> search(@RequestParam(value = "userId") Long userId,
                                               @RequestParam(value = "userName") String userName) { 

        UserVo user = new UserVo(){{
            setUserName("zhangsan");
            setUserId(2L);
        }};

        return userClient.search(user);
    }

   @GetMapping(value = "/_search2")
    public ResponseEntity<List<UserVo>> search(@RequestParam(value = "userId") Long userId,
                                               @RequestParam(value = "userName") String userName) { 

        UserVo user = new UserVo();
        user.setUserName("zhangsan");
        user.setUserId(2L);
        
        return userClient.search(user);
    }

}
```

when I request consumer controller `/_search1`,feign debug log is `c.n.loadbalancer.LoadBalancerContext     : feign-service-product using LB returned Server: 192.168.1.128:8021 for request http:///users/_search?this%240=com.eyison.controller.UserController%407b345013&val%24userName=zhangsan&val%24userId=2`

request `/_search2`,feign debug log is `c.n.loadbalancer.LoadBalancerContext     : feign-service-product using LB returned Server: 192.168.1.128:8021 for request http:///users/_search?userName=zhangsan&userId=2 `

why `/_search1` parmas begin with `val$` ? are anonymous inner classes all like this?

**Comment by ryanjbaxter** [comment]
Yes, you are creating a new class.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by ycy1991** [comment]
dear ryanjbaxter :
  Do you mean that fegin does not support cross-engineering POJO calls?
 I encountered the same problem when I was developing, and if I changed to json, there would be no similar problem.

**Comment by ryanjbaxter** [comment]
Your Feign Client takes in a type `UserVO`, it must have to do with the fact you are creating an anonymous class.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
