### ISSUE TITLE
A unified method to disable lb and service discovery which infrastructure may have provided

### ISSUE THREAD

**Issue by idouba** [spring-cloud/spring-cloud-openfeign#195]
The suggestion of  [Spring Cloud: How to use Feign without Ribbon](https://stackoverflow.com/questions/27620338/spring-cloud-how-to-use-feign-without-ribbon/27659935#27659935 ), and `@FeignClient(url="http://example.com", name="example")` can help feignclient call target service without ribbon.
But this require modify every method calling, is there a global method to disable lb and service discovery which infrastructure have provided, springcloud app just need to call the remote producer microservice by serviceName, as the issue spring-cloud/spring-cloud-netflix#2801 reffed scenario

**Comment by ryanjbaxter** [comment]
No there is no global property you can set.

**Comment by idouba** [comment]
I think this should be the default way of sdk to solve a service name, when can  find a instance for the service, use it, if cannot  just use the original service to call the remote service.
For example call remote Hello Server with embedded  LB and Discovery when Ribbon&Eureka is enabled,  and try to use infrastructure provided ns resolution  such as dns  when sdk's lb and discovery is not enabled .
```
@FeignClient(name="HelloServer")
	interface HelloClient {
		@RequestMapping(value = "/", method = GET)
		String hello();
	}
```

**Comment by spencergibb** [comment]
We don't feel that way. If you use a load balancer, you can configure it statically so it doesn't use eureka etc...

**Comment by idouba** [comment]
Thanks @spencergibb , Does you mean use ribbon and set the service instance like this？
```
HelloServer:
  ribbon:
    listOfServers: 10.133.249.158:7111,10.133.249.159:7111
```

**Comment by spencergibb** [comment]
Yes

**Comment by idouba** [comment]
Thanks.
