### ISSUE TITLE
【Feign】cannot get response after using global message converter

### ISSUE THREAD

**Issue by RobertoHuang** [spring-cloud/spring-cloud-openfeign#20]
Hi
      In My project service A calls  service B through Feign，Like this（Service A -> Feign -> Service B）. When the B service uses the global message converter，Service A cann‘’t receive any response，How can I solve this problem？ show you my code

![a](https://user-images.githubusercontent.com/20842825/38988779-0fed5f8c-4407-11e8-9767-846da6a9d136.png)

![b](https://user-images.githubusercontent.com/20842825/38988780-1025dbfa-4407-11e8-83da-19b2f82ea654.png)

![c](https://user-images.githubusercontent.com/20842825/38988781-105d6020-4407-11e8-9072-28ed43fcf3ee.png)

**Comment by ryanjbaxter** [comment]
Please dont post screenshots of code.  Put the code in a github repo or attach it as a zip.  Also if there are any error messages in service A or B can you please attach those?  Thanks.

**Comment by RobertoHuang** [comment]
Thanks for your reply, I have solved the problem with Feign Decoder.
