### ISSUE TITLE
Unable to decode Page<T> response

### ISSUE THREAD

**Issue by rafaelrenanpacheco** [spring-cloud/spring-cloud-openfeign#205]
> Spring Boot 2.1.6
> Spring Cloud OpenFeign 2.1.2
> Java 11

Hi there!

Looking at the Spring Cloud OpenFeign source code looks like it is able to decode Page responses, but something isn't working as expected. I have the following client:

```java
@RequestMapping(method = RequestMethod.POST, value = "users/find")
Page<UserResponse> findUsers(List<Long> usersId);
```

The `users/find` endpoint returns a `org.springframework.data.domain.Page` response, which should be decoded to `Page<UserResponse>`, but instead I get this exception:

```
Type definition error: [simple type, class org.springframework.data.domain.Page];
nested exception is com.fasterxml.jackson.databind.exc.InvalidDefinitionException:
Cannot construct instance of `org.springframework.data.domain.Page`
```

But shouldn't this project handle this through [PageJacksonModule.java](https://github.com/spring-cloud/spring-cloud-openfeign/blob/master/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/PageJacksonModule.java) and [FeignClientsConfiguration.java](https://github.com/spring-cloud/spring-cloud-openfeign/blob/master/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientsConfiguration.java)?

The FeignClientsConfiguration is beaning the `return new PageJacksonModule()` class during application startup, and `PageJacksonModule` has the implementation that is needed to decode a response to `Page` through:

```java
delegate = new PageImpl<>(content, PageRequest.of(number, size),
    totalElements);
```

I didn't find any instructions in the documentation regarding the Page desserialization. Am I missing something?

Best regards,
Rafael Pacheco.

**Comment by poznachowski** [comment]
I've encountered same thing. From what I understand:

1. `FeignClientsConfiguration` config is not a usual configuration class. It configures separate `ApplicationContext` dedicated only for Feign clients (see javadoc of `FeignContext` class)
2. Deserialization happens with Jackson's HttpMessageConverter and its injected from the outside applicationContext: https://github.com/spring-cloud/spring-cloud-openfeign/blob/master/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientsConfiguration.java#L62
3. Outside (normal) application context does not know about `PageJacksonModule` hence Jackson can't work it out.

That saying, simplest fix is to add `PageJacksonModule` module bean to your normal application context.

**Comment by OlgaMaciaszek** [comment]
Thanks @poznachowski . @rafaelrenanpacheco could you please try this solution and let us know if it fixes the issue?

**Comment by rafaelrenanpacheco** [comment]
Hello! I am on vacation and will be able to test this solution later this month.

Best regards,
Rafael Pacheco.

**Comment by poznachowski** [comment]
It was working that way, but this commit changed that: https://github.com/spring-cloud/spring-cloud-openfeign/commit/505a83e6a4ff3500cb7230b0e8f0da9d7dc13e75#diff-75f79e40d74af2b7ff1cfb558b90206e

where the test falsely assume that `FeignClientsConfiguration` is available for the Application: https://github.com/spring-cloud/spring-cloud-openfeign/commit/505a83e6a4ff3500cb7230b0e8f0da9d7dc13e75#diff-a49839663a8c102988e6435a470f4679R89

**Comment by OlgaMaciaszek** [comment]
Thanks @poznachowski - makes sense. Would you like to create a PR with a fix?

**Comment by ammmze** [comment]
And while I found that the workaround posted [here](https://github.com/spring-cloud/spring-cloud-openfeign/issues/205#issuecomment-525308100) works in the above demo app, it did not work in my main application where there are a bunch of other hairy configurations as that app has evolved over time.

**Comment by ammmze** [comment]
A brute force way to deal with this would be to register the module in the client configuration. Something like this:

```java
@FeignClient(name = "strings", url = "http://localhost:${server.port:8080}/", configuration = ClientConfiguration.class)
public interface StringClient {
    @GetMapping("/api")
    Page<String> getStrings(Pageable pageable);

    class ClientConfiguration implements InitializingBean {
        private List<AbstractJackson2HttpMessageConverter> converters;
        private List<Module> modules;

        public ClientConfiguration(List<AbstractJackson2HttpMessageConverter> converters,
                List<Module> modules) {
            this.converters = converters;
            this.modules = modules;
        }

        @Override
        public void afterPropertiesSet() throws Exception {
            converters.forEach(converter ->
                    modules.forEach(module -> converter.getObjectMapper().registerModule(module)));
        }
    }
}
```

Note: The above doesn't do any checking/comparison to see if the module has been registered already.

**Comment by nkonev** [comment]
Seems another workaround can be following:
```java
@Import(FeignClientsConfiguration.class)
```
https://github.com/spring-cloud/spring-cloud-openfeign/pull/103#issuecomment-474870642

**Comment by ryandanielspmc** [comment]
> A brute force way to deal with this would be to register the module in the client configuration (can be done either in the `@FeignClient` or the `@EnableFeignClient`). Something like this:
> 
> ```java
> @FeignClient(name = "strings", url = "http://localhost:${server.port:8080}/", configuration = ClientConfiguration.class)
> public interface StringClient {
>     @GetMapping("/api")
>     Page<String> getStrings(Pageable pageable);
> 
>     class ClientConfiguration implements InitializingBean {
>         private List<AbstractJackson2HttpMessageConverter> converters;
>         private List<Module> modules;
> 
>         public ClientConfiguration(List<AbstractJackson2HttpMessageConverter> converters,
>                 List<Module> modules) {
>             this.converters = converters;
>             this.modules = modules;
>         }
> 
>         @Override
>         public void afterPropertiesSet() throws Exception {
>             converters.forEach(converter ->
>                     modules.forEach(module -> converter.getObjectMapper().registerModule(module)));
>         }
>     }
> }
> ```
> 
> Note: The above doesn't do any checking/comparison to see if the module has been registered already.

Even after switching to 2.2.7-RELEASE, and setting `feign.autoconfiguration.jackson.enabled=true`, this was the ONLY solution that worked for me.

**Comment by ryandanielspmc** [comment]
The problem was fixed for me after upgrading to `org.springframework.cloud:spring-cloud-dependencies:Hoxton.SR11`.

**Comment by okue** [comment]
It seems beaning `SortJacksonModule` in Spring's default `ApplicationContext` caused this error https://github.com/spring-cloud/spring-cloud-openfeign/issues/492.

If possible, it might be happy for me to bean `SortJacksonModule` only in separate Feign's `ApplicationContext`.

**Comment by myong3** [comment]
According to this reference: #https://stackoverflow.com/a/66135597
It work for me.

> If you use autoconfigured Feign client you can follow [Spring Cloud OpenFeign docs](https://docs.spring.io/spring-cloud-openfeign/docs/current/reference/html/#spring-data-support) by turning on corresponding configuration property:

You may consider enabling Jackson Modules for the support org.springframework.data.domain.Page and org.springframework.data.domain.Sort decoding.

`feign.autoconfiguration.jackson.enabled=true
`
