### ISSUE TITLE
SpringFormEncoderclass in feign-form-spring 3.8.0(When bodyType is MultipartFile[].class,files should not be override)

### ISSUE THREAD

**Issue by Been24** [spring-cloud/spring-cloud-openfeign#223]
it happens line 67-69 in the source code of SpringFormEncoder.class, because each file has same file.getName()..
**```
if (bodyType.equals(MultipartFile[].class)) {
val files = (MultipartFile[]) object;
val data = new HashMap<String, Object>(files.length, 1.F);
for (val file : files) {
data.put(file.getName(), file);
}
super.encode(data, MAP_STRING_WILDCARD, template);
}

**Comment by Been24** [comment]
???

**Comment by ryanjbaxter** [comment]
Please learn how to [format code on GitHub](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

Please also provide steps to reproduce the issue and a better description of the problem.
