### ISSUE TITLE
Body type is ignored in SpringEncoder

### ISSUE THREAD

**Issue by ahmadmo** [spring-cloud/spring-cloud-openfeign#225]
In the [`SpringEncoder`](https://github.com/spring-cloud/spring-cloud-openfeign/blob/master/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/SpringEncoder.java), the parameter `bodyType` is ignored and not passed to the `canWrite` and `write` methods of the [`GenericHttpMessageConverter`](https://github.com/spring-projects/spring-framework/blob/master/spring-web/src/main/java/org/springframework/http/converter/GenericHttpMessageConverter.java) ([here](https://github.com/spring-cloud/spring-cloud-openfeign/blob/master/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/SpringEncoder.java#L94) and [here](https://github.com/spring-cloud/spring-cloud-openfeign/blob/master/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/SpringEncoder.java#L112)) which is important for them to determine whether or not they support and can write the `requestBody`.
This could be done similar to [this](https://github.com/spring-projects/spring-framework/blob/master/spring-webmvc/src/main/java/org/springframework/web/servlet/mvc/method/annotation/AbstractMessageConverterMethodProcessor.java#L284).

BTW, as long as this problem exists, what is the alternative solution for  `GenericHttpMessageConverter`s to determine the actual `Type` of the `requestBody` for example when it is a `ParameterizedType` which cannot be determined from `requestBody.getClass()`?

**Comment by ryanjbaxter** [comment]
Would you like to submit a PR to fix the problem?

**Comment by ahmadmo** [comment]
@ryanjbaxter sure, in a few days.
