### ISSUE TITLE
spring boot server.compression conflict with feign.compression

### ISSUE THREAD

**Issue by jskim1991** [spring-cloud/spring-cloud-openfeign#229]
I had the same issue as #145 .
I have the workaround or the fix to add the gzip decode support in default decoder.
Let me know if I can help to contribute.

Thanks,

**Comment by jskim1991** [comment]
Or default decoder should be able to handle gzip support with feign.compression.enabled=true. This would provide users minimum amount of gzip support for increased performance.

**Comment by OlgaMaciaszek** [comment]
Hi, @jskim1991 it makes sense to me to allowing gzip support (although not enforcing gzip decoding) when `feign.compression.enabled=true`, but this is probably not specific to Spring Cloud Open Feign, so you should create an issue in [OpenFeign repo](https://github.com/OpenFeign/feign) instead.

**Comment by jskim1991** [comment]
@OlgaMaciaszek Thank you for your feedback. In #145, you mentioned gzip support is not there because the default decoder(feign.codec.Decoder) from open-feign does not support it. However, when I checked the spring-cloud-openfeign, it actually has SpringDecoder which implements feign.codec.Decoder. So I think adding gzip support should be in spring-cloud-openfeign as well as openfeign.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.
