### ISSUE TITLE
which version has used latest openfeign version (10.x), I use 2.1.3.RELEASE version and find it uses 9.x 

### ISSUE THREAD

**Issue by kong-996** [spring-cloud/spring-cloud-openfeign#236]

**Comment by ryanjbaxter** [comment]
Spring Cloud OpenFeign 2.2.x will use OpenFeign 10.x.  Spring Cloud OpenFeign 2.2.x is part of our Hoxton release train.  You can try Hoxton.RC1 if you want to use Spring Cloud OpenFeign 2.2.x.
