### ISSUE TITLE
Make interface Targeter public

### ISSUE THREAD

**Issue by jacek-kaczmarek** [spring-cloud/spring-cloud-openfeign#240]
Problem description:
The type `org.springframework.cloud.openfeign.Targeter` is package-private. However:
* it's defined as @ConditionalOnMissingBean (suggesting it could be replaced by spring-cloud users),
* its initial commit message for type `org.springframework.cloud.openfeign.Targeter` reveals the intention to allow users to implement Feign clients without using Ribbon.

Request:
Could this interface be made public?
Now that Ribbon is deprecated, there might be more interest in this type, e.g. for lightweight service location.

Workaround:
defining `Targeter` implementations and `@Configuration` classes in the interface package works but is not elegant.

**Comment by echooymxq** [comment]
The request is reasonable.

**Comment by spencergibb** [comment]
PRs welcome
