### ISSUE TITLE
Regex support for EnableFeignClients basePackage attribute

### ISSUE THREAD

**Issue by mumukiller** [spring-cloud/spring-cloud-openfeign#249]
Hi all!

As far as i understand currently it's not possible to use regex in basePackages attribute for EnableFeignClients annotation.

Motivation for this is pretty simple - i have a lot of gradle modules with common domain feign clients which are all located in the same base package, but also there are feign clients which are related to specific domain. All these clients can be scanned by pattern e.g. .client.*

Does it make sense?

**Comment by spencergibb** [comment]
I don't think so. This is based off of core framework and I don't think the scanner supports that.
