### ISSUE TITLE
@ConditionalOnBean(Client.class) not being injected properly

### ISSUE THREAD

**Issue by jskim1991** [spring-cloud/spring-cloud-openfeign#251]
Problem Statement:
 - FeignAcceptGzipEncodingAutoConfiguration and FeignContentGzipEncodingAutoConfiguration have condition:  
[@ConditionalOnBean(Client.class)](https://github.com/spring-cloud/spring-cloud-openfeign/blob/1ce5ca1ba83a96036efa105d1fedfb1a72f0303f/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/encoding/FeignAcceptGzipEncodingAutoConfiguration.java#L41)

When testing with the attached code, I noticed in the logs (specifically negative matches) of the Spring Boot App in client-side directory like below

```
FeignAcceptGzipEncodingAutoConfiguration:
      Did not match:
         - @ConditionalOnBean (types: feign.Client; SearchStrategy: all) did not find any beans of type feign.Client (OnBeanCondition)
      Matched:
         - @ConditionalOnClass found required class 'feign.Feign' (OnClassCondition)
         - @ConditionalOnProperty (feign.compression.response.enabled) matched (OnPropertyCondition)


FeignContentGzipEncodingAutoConfiguration:
      Did not match:
         - @ConditionalOnBean (types: feign.Client; SearchStrategy: all) did not find any beans of type feign.Client (OnBeanCondition)
      Matched:
         - @ConditionalOnClass found required class 'feign.Feign' (OnClassCondition)
         - @ConditionalOnProperty (feign.compression.request.enabled) matched (OnPropertyCondition)
```

Code : 
[openfeign-issue-example-master.zip](https://github.com/spring-cloud/spring-cloud-openfeign/files/3854293/openfeign-issue-example-master.zip)

When I used the older versions (look for the commented versions in the parent pom.xml), that ConditionalOnBean(Client.class) condition was being matched.

**Comment by OLPMO** [comment]
Maybe you can pay attention to issue19169 of SpringBoot (https://github.com/spring-projects/spring-boot/issues/19169)

**Comment by spencergibb** [comment]
you are using a release candidate of spring boot. Can you please try again with boot 2.2.2.RELEASE?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
