### ISSUE TITLE
Capture Feign data using Java Aspect

### ISSUE THREAD

**Issue by FeeFelipe** [spring-cloud/spring-cloud-openfeign#254]
Hi,

I'm tring to use Aspect to capture data from feign, i found a closed issue ([https://github.com/spring-cloud/spring-cloud-openfeign/issues/59](https://github.com/spring-cloud/spring-cloud-openfeign/issues/59)), but that solution return the below exception

```
@Pointcut("execution(* org.springframework.cloud.netflix.feign.ribbon.LoadBalancerFeignClient.*(..))")
public void feignClientPointcut() {}

Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration': Initialization of bean failed; nested exception is java.lang.IllegalArgumentException: warning no match for this type name: org.springframework.cloud.netflix [Xlint:invalidAbsoluteTypeName]
```
After starting the spring i had the message 
`2019-12-02 15:23:38.484  INFO 9919 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)`

I'm using this repository to test it [https://github.com/FeeFelipe/azpecLogger](https://github.com/FeeFelipe/azpecLogger)

**Comment by spencergibb** [comment]
Are you asking a question or reporting a bug?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
