### ISSUE TITLE
Collection annotated with @PathVariable is parsed as semicolon separated value

### ISSUE THREAD

**Issue by AndrewPanov** [spring-cloud/spring-cloud-openfeign#274]
**Describe the bug**
FeignClient parses collection from method argument as string value where elements are separated by semicolon, but I think it should be a comma separated value instead. 

**Sample**
Let's say we have some feign client 

`@FeignClient(name = "some-entity-target-service", url = "http://localhost:8081/api/v0/some_entity/")`
`public interface SomeEntityFeignClient {...}`

with method like this

`@GetMapping("{ids}")` 
`ResponseEntity<Collection<SomeEntity>> getByIds(@PathVariable Set<String> ids);`

Style from guideline gives the same result

`@RequestMapping(method = RequestMethod.GET, path = "{ids}")`
`ResponseEntity<Collection<SomeEntity>> getByIds(@PathVariable("ids") Set<Integer> ids);`

Logs show request that feign sends
![Screenshot from 2020-01-13 20-17-09](https://user-images.githubusercontent.com/39460919/72276865-ee7a7b80-3641-11ea-87e5-6cdbc74d1210.png)
`GET http://localhost:8081/api/v0/some_entity/1;2 HTTP/1.1`

But as for me it should be
`GET http://localhost:8081/api/v0/some_entity/1,2 HTTP/1.1`

**Comment by spencergibb** [comment]
What version are you using? #260 added something similar but for matrix parameters.

**Comment by AndrewPanov** [comment]
@spencergibb I've pulled spring boot project from spring initializr version 2.2.2. 

It has 

` <dependency>`
      `<groupId>org.springframework.cloud</groupId>`
      `<artifactId>spring-cloud-openfeign-core</artifactId>`
      `<version>2.2.1.RELEASE</version>`
      `<scope>compile</scope>`
    `</dependency>`

And

  `  <dependency>`
      `<groupId>io.github.openfeign</groupId>`
      `<artifactId>feign-core</artifactId>`
      `<version>10.4.0</version>`
      `<scope>compile</scope>`
    `</dependency>`

If I missing something, you may see list of dependencies and its versions [here](https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-starter-openfeign/2.2.1.RELEASE)

**Comment by IlyasYOY** [comment]
I'm not a developer of this library, but as far as I understand **spring-cloud-openfeign** is not responsible for doing this. 

Expanding URI parameters is feign's burden.

Maybe you should consider moving your issue there?

I hope this helps! Good luck trying to fix this!

**Comment by AndrewPanov** [comment]
@IlyasYOY maybe, idk
Let someone reject this issue this comment like yours and I'll do the same for feign directly

**Comment by OlgaMaciaszek** [comment]
Hi, @AndrewPanov I have just tested your example on `Hoxton.SR3`, and I'm getting  `/ids/1,2,3` as expected.
Please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by lashen** [comment]
Hi. @AndrewPanov problem fixed on release 2.2.2.RELEASE.
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
            <version>2.2.2.RELEASE</version>
        </dependency>

**Comment by lashen** [comment]
Hi. @AndrewPanov problem fixed on release: 2.2.2.RELEASE.
```
<dependency>
<groupId>org.springframework.cloud</groupId>
<artifactId>spring-cloud-starter-openfeign</artifactId>
<version>2.2.2.RELEASE</version>
</dependency>
```

**Comment by OlgaMaciaszek** [comment]
Hi @AndrewPanov, please upgrade to `Hoxton.SR3` and verify.

**Comment by AndrewPanov** [comment]
@lashen, @OlgaMaciaszek thanks for reply
