### ISSUE TITLE
Ability to configure client to send default headers & etc.

### ISSUE THREAD

**Issue by IlyasYOY** [spring-cloud/spring-cloud-openfeign#284]
Hello,

I faced the need to send some headers that were identical for the service the were sent on. I thought that it'd be nice to have the ability to set default headers for the client in configuration.

Something like:
```java
feign:
  client
    config:
      some-api:
        defaultHeaders: 
          headerName: [HeaderValue1, HeaderValue2]
```

I'd like to add the possibility to do this without writing code yourself.
Of course you can write a `RequetInterceptor` yourself,  and make something similar, but I think that it's much more convenient to have it directly in here.

I think It may be done with adding some additional field in `FeignClientConfiguration` & `FeignClientFactoryBean` (at the first glance)

Thank you for the feedback.

**Comment by timpamungkas** [comment]
It will be nice. Most of my API needs to add *apikey* header so +1 for this

**Comment by IlyasYOY** [comment]
I've tried to implement this, you can check this [here](https://github.com/IlyasYOY/spring-cloud-openfeign/commit/6ab462f541978df8c90256e5451c0794bab1b87d)!
I wrote some tests, my solution seems to work fine. 

I hope this helps!

**Comment by IlyasYOY** [comment]
Any updates on this? 
Should I prepare a PR?

**Comment by OlgaMaciaszek** [comment]
Changes merged.
