### ISSUE TITLE
Add support for Spring Retry along with spring cloud loadbalancer

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-openfeign#286]
Looks like this was dependant on ribbon before.

**Comment by ryanjbaxter** [comment]
Ugh....yeah

**Comment by spencergibb** [comment]
Maybe it should be independent and use a feign retryer?

**Comment by Davio** [comment]
How about using Spring Cloud Circuit Breaker?

**Comment by Alos** [comment]
Can we use `spring-cloud-starter-circuitbreaker-resilience4j` (or Spring Retry) with Spring Cloud Open Feign? It looks like removing ribbon in favor of `spring-cloud-starter-loadbalancer` removed Circuit Breaker functionality from our FeignClients.

**Comment by spencergibb** [comment]
removing ribbon did not remove circuit breaker functionality, removing hystrix did it. see https://github.com/spring-cloud/spring-cloud-circuitbreaker/issues/3

**Comment by Alos** [comment]
Thanks!

**Comment by fehmer** [comment]
+1 for a solution using spring-retry similar to the way ribbon was integrated. Ribbons 'retryableStatusCodes' and 'MaxAutoRetries/MaxAutoRetriesNextServer' was quite useful.

**Comment by OlgaMaciaszek** [comment]
We are planning to  [add support for Retry in SC LoadBalancer](https://github.com/spring-cloud/spring-cloud-commons/issues/659). I will be working on it at the beginning of October.
