### ISSUE TITLE
Hoxton.SR1 cannot recognize consul URL (unknown host exception)

### ISSUE THREAD

**Issue by timpamungkas** [spring-cloud/spring-cloud-openfeign#294]
**Boot 2.24 + Cloud Hoxton.SR1**

I have feign client + consul + spring cloud LB

```java
@FeignClient(name = "payrollClient", url = "http://payroll-compensation")
public interface PayrollClient {

	@DeleteMapping(value = "/api/payroll/master/{employee_id}")
	ResponseEntity<MasterPayrollResponse> disableMasterPayroll(@PathVariable(name = "employee_id") String employeeId,
			@RequestBody MasterPayrollRequest requestBody);

}
```

Consul runs on localhost.  
When I use `Hoxton.RELEASE`, calling feign method works fine using this caller

```java
@Service
public class UnpaidLeaveService {

	@Autowired
	private PayrollClient payrollClient;

	public boolean approveUnpaidLeave(String employeeId, LocalDate unpaidLeaveDate) {
                ...
		try {
			var requestBody = new MasterPayrollRequest();
			requestBody.setEffectiveDate(unpaidLeaveDate);
			payrollClient.disableMasterPayroll(employeeId, requestBody);
			return true;
		} catch (FeignException e) {
			LOG.warn("[Sync] Feign client Exception : {}", e.getMessage());
			return false;
		}
                ...
	}

}
```

Changing the cloud version to `SR1` breaks this functionality, when calling through feign client, it throws `UnknownHostException`.

Attached is the full stack trace, my build.gradle, and application.yml  
 - [stacktrace.txt](https://github.com/spring-cloud/spring-cloud-openfeign/files/4169880/stacktrace.txt)
  - [java-config-files.zip](https://github.com/spring-cloud/spring-cloud-openfeign/files/4169886/java-config-files.zip)

Thanks

**Comment by spencergibb** [comment]
You shouldn't be using url if you are using discovery

**Comment by timpamungkas** [comment]
So what should i use? @spencergibb
