### ISSUE TITLE
Path variables with / are not url encoded

### ISSUE THREAD

**Issue by doumdoum** [spring-cloud/spring-cloud-openfeign#3]
With Feign directives the decodeSlash parameter of RequestLine directive deals with it, 
see https://stackoverflow.com/questions/43889140/feign-url-encode-path-params
There is no such thing with spring XXXMapping directive (which can not be modified).
(PR for fix to come)

**Comment by cosyman** [comment]
I solved it by the following code, but native support will be appreciated
```java
  @Bean
    SpringMvcContract decodeSlashContract() {
        return new SpringMvcContract() {
            @Override
            protected void processAnnotationOnMethod(MethodMetadata data, Annotation methodAnnotation, Method method) {
                if (!NotDecodeSlash.class.isInstance(methodAnnotation) && !methodAnnotation
                        .annotationType().isAnnotationPresent(NotDecodeSlash.class)) {
                    data.template().decodeSlash(false);
                }
                super.processAnnotationOnMethod(data, methodAnnotation, method);
            }
        };
    }
```

**Comment by RaphC** [comment]
hi @cosyman is NotDecodeSlash class belongs to feign package or another one ?

**Comment by cosyman** [comment]
@RaphC  Yes，just a mark annotation.

**Comment by fdirlikli** [comment]
@ryanjbaxter, @adriancole  Are you still interested in this if I come up with a PR?

**Comment by ryanjbaxter** [comment]
PRs are welcome sure

**Comment by swaroopak** [comment]
I am working on this issue as a part of gracehopperOSD

**Comment by OlgaMaciaszek** [comment]
Fixed with https://github.com/spring-cloud/spring-cloud-openfeign/commit/d419826ca0d17c94ffd8829442096c1d7fbf90b9.

**Comment by nagy3n** [comment]
When will you release the new version?
