### ISSUE TITLE
MatrixVariables dont ignore synthetic members

### ISSUE THREAD

**Issue by nickcodefresh** [spring-cloud/spring-cloud-openfeign#302]
**Version: 2.2.2.RELEASE**

My code is generating this GET request:
```
http://{{host}}:18113/api/events?offset=0&includeMessage=false&%24jacocoData=[Z@26486a0d&includeTotal=false&DEFAULT_LIMIT=100&sortOrder=DESC&limit=100&sortBy=TIMESTAMP&objectId=10100&includeEventsWithNoWorkspace=false
```
note the `24jacocoData` parameter. I suspect that you're using reflection to generate matrix variables, but you're not ignoring synthetic members

https://github.com/jacoco/jacoco/issues/168

Thank

Nick

**Comment by spencergibb** [comment]
We reuse spring codecs. It's quite possible this could be in feign core also

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
