### ISSUE TITLE
Could provide some samples for open-feign(none boot application) connect SpringCould via Eureka Question

### ISSUE THREAD

**Issue by tain198127** [spring-cloud/spring-cloud-openfeign#31]
Could provide some samples for open-feign(none boot application)  connect SpringCould via Eureka

----------------------------------------
Background: 
My project is none boot application, like cli, I wanna connect the SpringCloud via Eureka server. I can connect the real ip address by open-feign, but I wanna via Eureka as named server. 
Could someone provide sample? Or give me some hints?

**Comment by ryanjbaxter** [comment]
Spring Cloud depends on Spring Boot, you cannot use the projects without it.  If you are just using plain OpenFeign then I suggest you open an issue in that project.
