### ISSUE TITLE
Feign Inheritance Support

### ISSUE THREAD

**Issue by bjchen2** [spring-cloud/spring-cloud-openfeign#315]
https://cloud.spring.io/spring-cloud-static/spring-cloud-openfeign/2.2.2.RELEASE/reference/html/#spring-cloud-feign-inheritance

In this doc's note, it's described that the demo does not work, but in my test, the demo can work correctly. so I want to know what's mean about "method parameter mapping is not inherited"

Version:
SpringBoot : 2.2.5.RELEASE
SpringCloud: Hoxton.SR3
springCloudAlibaba: 2.2.0.RELEASE
registration center use spring-cloud-starter-alibaba-nacos

**Comment by spencergibb** [comment]
@bjchen2 what was your demo?

**Comment by bjchen2** [comment]
Sorry, I misunderstood at the beginning, this document is talking about SpringMVC, but I use SpringBoot
