### ISSUE TITLE
AsyncFeign builder with Spring Cloud

### ISSUE THREAD

**Issue by LuigiCerone** [spring-cloud/spring-cloud-openfeign#317]
Hello,
in the Open feign repository [https://github.com/OpenFeign/feign#async-execution-via-completablefuture](here) it says that from version Feign 10.8 it is possible to use this asynchronous builder in order to perform async queries.
Is it possible to use it also with spring cloud? If yes, is there any kind of example? 
Thanks.

**Comment by ryanjbaxter** [comment]
No we do not have any support for that right now

**Comment by UzimakiNaruto** [comment]
@ryanjbaxter Hi, Do we have any plans for support the AsyncFeign?

**Comment by ryanjbaxter** [comment]
@UzimakiNaruto see https://github.com/spring-cloud/spring-cloud-openfeign/blob/v2.2.3.RELEASE/docs/src/main/asciidoc/spring-cloud-openfeign.adoc#reactive-support

**Comment by UzimakiNaruto** [comment]
@ryanjbaxter Thanks 👍
