### ISSUE TITLE
Read timeout from application properties is not used when client is configured.

### ISSUE THREAD

**Issue by stoetti** [spring-cloud/spring-cloud-openfeign#324]
**Describe the bug**
If the read-timeout is configured using application properties, this value is only used if the connect-timeout is configured with the same context. So if e.g. connect-timeout shall be configured using the default-context and the read-timeout per client, both values would not be used.

**Sample**
These two configurations will not lead to a timeout other than the default 60 sec
```
feign.client.config.client1.read-timeout=1000
```
 
```
feign.client.config.client1.read-timeout=1000 
feign.client.config.default.connect-timeout=1000
```

If the configuration looks like this the configured values will be picked up when configuring the clients.
```
feign.client.config.client1.read-timeout=1000
feign.client.config.client1.read-timeout=1000
```

**Comment by ryanjbaxter** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by stoetti** [comment]
For sure, hope this provides the necessary information.

https://github.com/stoetti/feign-timeout-demo

**Comment by OlgaMaciaszek** [comment]
Thanks @stoetti - it's a bug. Will fix it.
