### ISSUE TITLE
SpringDecoder returns null on empty Resource

### ISSUE THREAD

**Issue by Czocher** [spring-cloud/spring-cloud-openfeign#327]
**Describe the bug**
When returning an empty `org.springframework.core.io.Resource` response (e.g. `FileSystemResource` pointing to an empty file) `SpringDecoder` converts it to a `null` instead of an empty `Resource`.

Version: org.springframework.cloud:spring-cloud-openfeign-core:2.1.3.RELEASE

**Source of the problem**
[Line 59 in SpringDecoder](https://github.com/spring-cloud/spring-cloud-openfeign/blob/9a335536bcbd28eef92b121516461becf39b526b/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/SpringDecoder.java#L59) uses `HttpMessageConverterExtractor` to extract the data from the HTTP response using the assigned `MessageConverter`. Unfortunately [Line 89 in the HttpMessageConverterExtractor class](https://github.com/spring-projects/spring-framework/blob/d2bcf1ed71be5cad91b39fd613a3c1aa91bf3609/spring-web/src/main/java/org/springframework/web/client/HttpMessageConverterExtractor.java#L89) has an early return when the body is empty. This is the case when returning an empty `Resource`.

**Comment by spencergibb** [comment]
Why are you returning a Resource from feign?

**Comment by Czocher** [comment]
I'm returning a `FileSystemResource` from a controller because I need file-download functionality. I am aware Feign is not the best fit for this kind of functionality, but I'm constrained by the environment.

**Comment by Czocher** [comment]
For the people searching for a quick-fix: this issue can be bypassed by creating a new delegating `Decoder` implementation and decorating the `SpringDecoder` as follows:

```java
public class EmptyResourceDecoder implements Decoder {

	public static final ByteArrayResource EMPTY_RESPONSE = new ByteArrayResource("".getBytes(StandardCharsets.UTF_8));
	private final Decoder delegate;

	public EmptyResourceDecoder(final Decoder delegate) {
		Objects.requireNonNull(delegate, "Decoder must not be null. ");
		this.delegate = delegate;
	}

	@Override
	public Object decode(final Response response, final Type type) throws IOException, FeignException {
		final Object result = delegate.decode(response, type);

		if (type instanceof Class && ((Class<?>) type).isAssignableFrom(Resource.class) && result == null) {
			return EMPTY_RESPONSE;
		}

		return result;
	}
}
```

```java
       @Bean
	public Decoder feignDecoder(final ObjectFactory<HttpMessageConverters> messageConverters) {
		return new OptionalDecoder(
			new ResponseEntityDecoder(new EmptyResourceDecoder(new SpringDecoder(messageConverters))));
	}
```

**Comment by spencergibb** [comment]
Why can't the feign client just return a byte array?

**Comment by Czocher** [comment]
The return type must be the same as the one in the `Type` argument otherwise a `ClassCastException` occurs due to the fact the return of this method is later casted to the `Resource` type expected by the Feign client interface (`java.lang.ClassCastException: [B cannot be cast to org.springframework.core.io.Resource` to be exact).

**Comment by spencergibb** [comment]
Yes, this is a problem when you share an interface between a client and server. I'm going decline this as we don't want to support everything you can do on a server on a client.
