### ISSUE TITLE
Spring could load balancer is not working with feign client 

### ISSUE THREAD

**Issue by sivagandhi1993** [spring-cloud/spring-cloud-openfeign#332]
I am getting error saying when using spring cloud load balancer that it is not able to get list of servers.
Used 
```
id 'org.springframework.boot' version '2.2.6.RELEASE'
set('springCloudVersion', "Hoxton.SR4")
implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'
```

And application.ymml as 
```
spring:
  application:
    name: client
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
server:
  port: 7211
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
```

Error is :
```
2020-05-04 10:50:15.935  INFO 16742 --- [ctor-http-nio-2] com.epe.client.ClientApplication         : feignclient is working or not HardCodedTarget(type=HelloClient, name=api, url=http://api)
2020-05-04 10:50:21.060 ERROR 16742 --- [ctor-http-nio-2] a.w.r.e.AbstractErrorWebExceptionHandler : [3f301a88-1]  500 Server Error for HTTP GET "/"

java.lang.IllegalStateException: block()/blockFirst()/blockLast() are blocking, which is not supported in thread reactor-http-nio-2
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:83) ~[reactor-core-3.3.4.RELEASE.jar:3.3.4.RELEASE]
```
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ HTTP GET "/" [ExceptionHandlingWebHandler]
Stack trace:
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(Blockin

**Comment by spencergibb** [comment]
Feign is blocking by nature and therefore can not be used in webflux

**Comment by spencergibb** [comment]
Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
