### ISSUE TITLE
ribbon-starter not included in openfeign-starter

### ISSUE THREAD

**Issue by carbon-projects** [spring-cloud/spring-cloud-openfeign#340]
the doc:
https://cloud.spring.io/spring-cloud-static/spring-cloud-openfeign/2.2.2.RELEASE/reference/html/

spring-cloud-starter-openfeign contains both spring-cloud-starter-netflix-ribbon and spring-cloud-starter-loadbalancer.

but in maven ribbon and loadbalancer is:
`<optional>true</optional>`

i need add dependencies again

**Comment by OlgaMaciaszek** [comment]
That's right @carbon-projects. They are actually supposed to be optional. See https://github.com/spring-cloud/spring-cloud-openfeign/issues/35. Will fix the docs.
