### ISSUE TITLE
url参数未转义

### ISSUE THREAD

**Issue by zkk9205** [spring-cloud/spring-cloud-openfeign#341]
**Describe the bug**
我使用openFeign 9.4时，请求参数含有分号 ; 参数未转义，导致参数变成其他含义  
**Sample**
请求参数：qrCode=SHANDONGGS/V1;CZB19225814704760lFi3
openFeign未转义错误的参数 qrCode=SHANDONGGS%2FV1&qrCode=CZB19225814704760lFi3
正确的参数：qrCode=SHANDONGGS%2FV1%3BCZB19225814704760lFi3

**Comment by zkk9205** [comment]
package feign.template;
feign.template.QueryTemplate#queryString 
这个方法把带分号的参数，分割成了多个参数，导致调用失败
List<String> resolved = Arrays.stream(values.split(COLLECTION_DELIMITER))
        .filter(Objects::nonNull)
        .filter(s -> !UNDEF.equalsIgnoreCase(s))
        .collect(Collectors.toList());

**Comment by OlgaMaciaszek** [comment]
@zkk9205 The language of the Spring Cloud repository is English. If you want us to take a look at this issue, please translate to English.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
