### ISSUE TITLE
Do not encode path variable

### ISSUE THREAD

**Issue by srikanth88infy** [spring-cloud/spring-cloud-openfeign#348]
We have the following feign client
```
public interface MyServiceClient {

    @RequestMapping(method = RequestMethod.GET, value = "/item/{itemKey}")
    Item getItem (@PathVariable("itemKey") String itemKey);
```
the items can contains special characters like `:` or `::` which are being encoded and the Request URL becomes something like `https://myservice.com/item/a%3Ab%3A%3Ac` rather than `https://myservice.com/item/a:b::c` 

Can anyone help me understand how can I overcome this issue?

**Comment by robrtj** [comment]
Same issue is open in openFeign project: https://github.com/OpenFeign/feign/issues/1190
You can find workaround there. Unfortunetelly there is no pretty solution.

**Comment by OlgaMaciaszek** [comment]
Closing in favour of https://github.com/OpenFeign/feign/issues/1190.
