### ISSUE TITLE
Donot wrap custom exception to HystrixRunTimeException in Feign Client Fall back methods

### ISSUE THREAD

**Issue by shivasantosh** [spring-cloud/spring-cloud-openfeign#356]
Fallback service is wrapping ProductNotFoundException into `HystrixRunTimeException`.
I want to propagate custom exception as it is instead of wrapping into `HystrixRunTimeException`.
Below is the code snippet for reference:

```java
@FeignClient(name = "service1", fallback = FallBackService1.class )
public interface FeignService1{
     String validateProducts(Product product);
}
```
```java
class FallBackService1 implements FeignService1{
@override
public String validateProducts(Product product){
     throw new ProductNotFoundException("P119","Product not found");
}
}
```
I have enabled
`feign.hystrix.enabled = true`.

Please help with this. I want to propagate the exception as it is. I do not want it to be wrapped.

Exception is 
```java
: Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.netflix.hystrix.exception.HystrixRuntimeException: ProductFeignService#validateProducts(product) failed and fallback failed.] with root cause
```

**Comment by OlgaMaciaszek** [comment]
@shivasantosh 
Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

**Comment by OlgaMaciaszek** [comment]
Please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by shivasantosh** [comment]
@OlgaMaciaszek  
Here is my git public link which has two services
https://github.com/shivasantosh/feignproject



![image](https://user-images.githubusercontent.com/13864811/87450203-dd73ec80-c61b-11ea-825c-5ae24041e1ef.png)

Order service is calling Product service using feign client.
Steps for replication:
1. Run the two spring boot projects.
2. Call the POST end point "http://localhost:<portnumber>/order/{productId}". This end point which internally calls product service with feign client.
3. product service throws exception, entered into ProductFeignServiceFallBack.java where I want to throw exception to the client "ProductNotFoundException" as below

```java
@Component
@Scope(ConfigurableBeanFactory.SCOPE_PROTOTYPE)
public class ProductFeignServiceFallBack implements ProductFeignService{

	private static final Logger LOGGER = LogManager.getLogger(ProductFeignServiceFallBack.class);

	private final Throwable cause;

	public ProductFeignServiceFallBack(Throwable cause) {
		this.cause = cause;
	}

	@Override
	public ResponseEntity<String> validateProduct(long productId) {
		// my code for updating errors in my DB
		//throw exception to the client
		LOGGER.error(cause.getMessage());
		LOGGER.info("thrown exception from upstream so entered fall back");
		throw new ProductNotFoundException("PRODUCT_NOT_FOUND", "PRODUCT_NOT_FOUND");
	}

}
```
4. But I see in the Controller advice it is entering into HystrixRuntimeException block. I want it to be entered into productNotFoundException block. ProductNotFoundException is wrapped in HystrixRuntimeException.
I want the business exception to be thrown as it is instead of wrapping it in HystrixRuntimeException. 
Because in my service class I donot want to catch with HystrixRuntimeException.

 ```java
@ControllerAdvice
public class OrderServiceExceptionHandler {

	/*Exception has to enter this block*/
	@ExceptionHandler(ProductNotFoundException.class)
    public @ResponseBody ResponseEntity<ErrorDetails> productNotFoundException(ProductNotFoundException ex) {
		ErrorDetails errorDetails = new ErrorDetails(ex.getErrorMessage(), ex.getErrorCode());
        return new ResponseEntity<>(errorDetails, HttpStatus.EXPECTATION_FAILED);
    }
	
	/*Should not enter this block*/
	@ExceptionHandler(HystrixRuntimeException.class)
    public @ResponseBody ResponseEntity<String> hystrix(HystrixRuntimeException ex) {
        return new ResponseEntity<>("Hystrix bloc", HttpStatus.CONFLICT);
    }
}
```

**Comment by OlgaMaciaszek** [comment]
@shivasantosh I have verified it and this, indeed, happens. However, first of all, I would not consider it a bug: any exception occurring within a feign call is wrapped with a FeignException as a design decision. Secondly, I would definitely not consider throwing an exception from the fallback method a good practice, either - the fallback method should provide a default replacement result when the actual result cannot be retrieved and would suggest you modify this approach. Lastly, this is being handled by the [core Feign library](https://github.com/OpenFeign/feign) and not the Spring Cloud OpenFeign library, so any discussion should take place within that repo.
