### ISSUE TITLE
FeignClientFactoryBean#getObjectType() return null lead to "is not eligible..."

### ISSUE THREAD

**Issue by 879913935** [spring-cloud/spring-cloud-openfeign#361]
**Describe the bug**

Bean 'com.example.demo.DemoApplication$NameService' of type [org.springframework.cloud.openfeign.FeignClientFactoryBean] **is not eligible for getting processed by all BeanPostProcessors** (for example: not eligible for auto-proxying)

it‘s because **FeignClientFactoryBean#getObjectType()** return null, so spring will **early init** and i think it is a little worried.

even if this is not a bug actually,  but it bothers me and i hope this **info** log will disappear :)  

```java
// AbstractAutowireCapableBeanFactory#getTypeForFactoryBean(String beanName, RootBeanDefinition mbd, boolean allowInit) 

// If we're allowed, we can create the factory bean and call getObjectType() early
if (allowInit) {
    FactoryBean<?> factoryBean = (mbd.isSingleton() ?
        getSingletonFactoryBeanForTypeCheck(beanName, mbd) :
	getNonSingletonFactoryBeanForTypeCheck(beanName, mbd));
    if (factoryBean != null) {
        // Try to obtain the FactoryBean's object type from this early stage of the instance.
        Class<?> type = getTypeForFactoryBean(factoryBean);
        if (type != null) {
            return ResolvableType.forClass(type);
        }
        // No type found for shortcut FactoryBean instance:
        // fall back to full creation of the FactoryBean instance.
        return super.getTypeForFactoryBean(beanName, mbd, true);
    }
}
```

**Sample**

@SpringBootApplication
@EnableFeignClients
public class DemoApplication {

    public static void main(String[] args) {
        SpringApplication.run(DemoApplication.class, args);
    }

    @FeignClient("name")
    static interface NameService {
        @RequestMapping("/")
        public String getName();
    }
}

**Comment by stardyun** [comment]
me too

**Comment by spencergibb** [comment]
It's just a warning.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
