### ISSUE TITLE
Open Feign is working on VM, but the same is not working on local

### ISSUE THREAD

**Issue by satishpatro44** [spring-cloud/spring-cloud-openfeign#362]
**Describe the bug**
The bug which I am facing in my local system is running in my teammates' local system & running in AWS VM also,
When I make an inter-service call, I am getting "status:403"

**Sample**
No way to reproduce, as the same is running in other's systems.
Field value in ServiceErrorDecoder

`    

    status	:403
    reason	:Forbidden
    headers	:{connection=[keep-alive], content-language=[en], content-length=[4633], content-type=[text/html;charset=utf-8], date=[Wed, 24 Jun 2020 10:30:19 GMT], mime-version=[1.0], server=[squid], vary=[Accept-Language], x-cache=[MISS from Uranus], x-cache-lookup=[NONE from Uranus:8085], x-squid-error=[ERR_ACCESS_DENIED 0]}
    body	:feign.Response$InputStreamBody@2fca1bef // repeatable": false
    request	:GET http://abc.xyz:9410/engn/v2/product
    Authorization: Bearer Xyz // JWT Token
    Cookie: Content-Type: application/json`

**Comment by spencergibb** [comment]
you have some authorization error with squid? What does this have to do with openfeign?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by satishpatro44** [comment]
I didn't know what is squid. Looked into this after you mentioned, Some proxy issues.
Yeah, it is not an issue of Openfeign.

Sorry for the trouble.
