### ISSUE TITLE
historical version 

### ISSUE THREAD

**Issue by SolitaryEagle** [spring-cloud/spring-cloud-openfeign#368]
Hello, I have a question. Where can I find the historical version of spring cloud related projects's document? For example, spring cloud openfeign 2.1.4.release. I visit https://cloud.spring.io/spring-cloud-static/spring-cloud-openfeign/2.1.4.RELEASE/reference/html/ Prompt not found

**Comment by ryanjbaxter** [comment]
Here you go, sorry about that!
https://cloud.spring.io/spring-cloud-static/spring-cloud-openfeign/2.1.4.RELEASE/spring-cloud-openfeign.html
