### ISSUE TITLE
HystrixDelegatingContract

### ISSUE THREAD

**Issue by govardhanaraoganji** [spring-cloud/spring-cloud-openfeign#374]
Caused by: java.lang.AbstractMethodError: Receiver class feign.hystrix.HystrixDelegatingContract does not define or inherit an implementation of the resolved method abstract parseAndValidateMetadata(Ljava/lang/Class;)Ljava/util/List; of interface feign.Contract.
	at feign.ReflectiveFeign$ParseHandlersByName.apply(ReflectiveFeign.java:151)
	at feign.ReflectiveFeign.newInstance(ReflectiveFeign.java:49)
	at feign.hystrix.HystrixFeign$Builder.target(HystrixFeign.java:63)
	at feign.hystrix.HystrixFeign$Builder.target(HystrixFeign.java:111)

I am getting the above error while creating feign client with HystrixFeign.

**Comment by govardhanaraoganji** [comment]
I don't know, what I am missing in dependencies.
Using: 
spring-boot-starter-parent as 2.1.8.RELEASE
spring-cloud-dependencies as Greenwich.SR3
feign-hystrix as 10.2.3

**Comment by spencergibb** [comment]
without seeing all of your dependencies I can't answer.

**Comment by govardhanaraoganji** [comment]
These dependencies, will help you?

spring-boot-starter-parent as 2.1.8.RELEASE
spring-cloud-dependencies as Greenwich.SR3
feign-hystrix as 10.2.3

        
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-cache</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-netflix-zuul</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.security.oauth</groupId>
            <artifactId>spring-security-oauth2</artifactId>
            <version>${spring-security-oauth2.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>

        <dependency>
            <groupId>io.github.openfeign</groupId>
            <artifactId>feign-httpclient</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.openfeign</groupId>
            <artifactId>feign-hystrix</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.openfeign</groupId>
            <artifactId>feign-jackson</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.openfeign</groupId>
            <artifactId>feign-slf4j</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.openfeign.form</groupId>
            <artifactId>feign-form</artifactId>
        </dependency>

**Comment by OlgaMaciaszek** [comment]
@govardhanaraoganji Spring Cloud `Greenwich` is no longer supported. Can you please verify on `Hoxton` release train (we recommend using https://start.spring.io/ to ensure correct dependency set) and let us know if the issue persists.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by govardhanaraoganji** [comment]
Thank you for the support @OlgaMaciaszek and @spring-issuemaster. I have many dependencies with our common modules so I used different approach i.e) `feign-hystrix` as dependency to my component so issue got resolved. Earlier It was in our common module.
