### ISSUE TITLE
Add test that verifies the path

### ISSUE THREAD

**Issue by OlgaMaciaszek** [spring-cloud/spring-cloud-openfeign#387]
The following issue should not have happened: https://github.com/spring-cloud/spring-cloud-openfeign/issues/386

Add test for this area.

**Comment by calaroche** [comment]
I will take a stab at this issue

**Comment by Bhavya-official** [comment]
I would like to resolve this issue. Please guide me to how to start

**Comment by OlgaMaciaszek** [comment]
Hello, @Bhavya-official  The following bug was reported some time ago: https://github.com/spring-cloud/spring-cloud-openfeign/issues/386. The tests we had did not catch this regression. The bug was since fixed, but a test that would have caught the issue should be added as well. If you are an OpenForce 2022 participant, please contact mentors in spring cloud channel in OpenForce discord for if you need more help or have any questions.

**Comment by Bhavya-official** [comment]
@OlgaMaciaszek If any suggestions or modifications can be done, please let me know.
