### ISSUE TITLE
When doing request, feign is removing "/" (bar) from end url

### ISSUE THREAD

**Issue by toedio** [spring-cloud/spring-cloud-openfeign#396]
**Describe the bug**
I am access a endpoint that should a bar in end of url, and when I put url with bar don't work because the request was executed without the bar.

My alternative solution is put two bar in url to work.

Spring cloud version: Hoxton.SR7
Java 8

**Comment by OlgaMaciaszek** [comment]
@toedio 
Please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
