### ISSUE TITLE
 Open-feign cannot restrict access to the external network

### ISSUE THREAD

**Issue by developers-youcong** [spring-cloud/spring-cloud-openfeign#397]
**Describe the bug**

Normal should my local IP access can not be，But you can also access it to get a normal response

added:
Can open-Feign really implement internal communication and restrict external communication

**Sample**

My Code

```
@FeignClient(contextId = "userApiService", value = ServiceNameConstants.BLOG_SERVICE, url = "http://localhost:2020")

public interface UserApiService {

    @GetMapping("/blog_user/list")
    String queryUserList();
}

```

**Comment by OlgaMaciaszek** [comment]
@developers-youcong we will need more details to triage it. Could you provide a more detailed description of the proposed feature, including what you expect should happen vs. what actually happens?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
