### ISSUE TITLE
Add support for reactive feign clients

### ISSUE THREAD

**Issue by ryanjbaxter** [spring-cloud/spring-cloud-openfeign#4]
See https://github.com/spring-cloud/spring-cloud-netflix/issues/1554 for history.

**Comment by kptfh** [comment]
Added support of hystrix and ribbon to reactive feign
https://github.com/kptfh/feign-reactive

**Comment by kptfh** [comment]
@spencergibb You was right about blocking body serialization. After refactoring it can accept Publisher as body. Take a look at shouldReturnFirstResultBeforeSecondSent() test in
[https://github.com/kptfh/feign-reactive/blob/master/feign-reactive-core/src/test/java/feign/reactive/allfeatures/AllFeaturesTest.java](https://github.com/kptfh/feign-reactive/blob/master/feign-reactive-core/src/test/java/feign/reactive/allfeatures/AllFeaturesTest.java)

**Comment by spencergibb** [comment]
@kptfh sweet. Any interest in donating that to the project?

**Comment by kptfh** [comment]
Sure. That is the goal of all this work. Can you provide the next steps to do?

**Comment by spencergibb** [comment]
At this point, just a pull request. There's probably some work to be done in autoconfiguration.

**Comment by kptfh** [comment]
@spencergibb Dont you mind about 2 modules?:
spring-reactivefeign
spring-cloud-reactivefeign
The key point here that spring-reactivefeign-core can work out of cloud.

**Comment by ryanjbaxter** [comment]
Are you saying that spring-reactivefeign-core would be a separate project the spring-cloud-reactivefeign would consume?

**Comment by kptfh** [comment]
Yes. As for me it would be the best to incorporate code of `feign-reactive-core` into `spring-boot-starter-webflux` as it's actually a thin wrapper over `WebClient` that just use Feign's `MethodMetadata` class to discover target client interface. If it's impossible then let it be separate project.
But `feign-reactive-cloud` is perfect candidate to be included into `spring-cloud-openfeign`.
Don't want to limit the usage of `spring-reactivefeign-core` to just spring cloud stack. It will be nice to use it in Kubernetes or Docker Swarm as well.

**Comment by spencergibb** [comment]
Nothing of feign will go into spring boot. I'm ok with a module here that doesn't have boot dependencies and then one that does. Though the group id will still be Spring Cloud's regular group id.

**Comment by kptfh** [comment]
here is the core module pr:
https://github.com/spring-cloud/spring-cloud-openfeign/pull/11

**Comment by prafsoni** [comment]
Any updates on this?

**Comment by ryanjbaxter** [comment]
Follow along on the PR.  We will be looking at integrating this in Finchley.SR1

**Comment by kdavisk6** [comment]
I've left a question on the PR, but I'll bring it up here.  Why not submit this into `OpenFeign` as a module there instead of here?  That would be the appropriate place if you wanted this support to be available outside of Spring.

**Comment by AnkBurov** [comment]
Any progress so far?

**Comment by ryanjbaxter** [comment]
See the PR for details.

**Comment by kptfh** [comment]
@ryanjbaxter @spencergibb stack into dead end with openfeign repo. Don't see any benefits to keep code there. No one is reviewing the code except one guy (@kdavisk6) that don't understand how reactive approach should work. It will last for years and from my side looks like sabotage or time killing.
Please, take a look at this issue [https://github.com/OpenFeign/feign-reactive/issues/15](https://github.com/OpenFeign/feign-reactive/issues/15) and pull request [https://github.com/OpenFeign/feign-reactive/pull/18](https://github.com/OpenFeign/feign-reactive/pull/18)

**Comment by kptfh** [comment]
We definitely should find other way if we want Reactive Feign to be released for Spring WebClient.

**Comment by spencergibb** [comment]
I highly doubt it is "sabotage or time killing." No need to comment on multiple issues, we see them. I see the ones on OpenFeign as he is taking over for myself and @adriancole. It is a community run project, no full-time developers.

**Comment by kptfh** [comment]
I highly doubt it's a community run project. I see only one person :(. 
Have you a chance  to check PR? Don't spend many time just check this class [https://github.com/kdavisk6/feign-reactive/blob/reactive-core/feign-reactive-core/src/main/java/feign/ReactorInvocationHandler.java](https://github.com/kdavisk6/feign-reactive/blob/reactive-core/feign-reactive-core/src/main/java/feign/ReactorInvocationHandler.java).
Can't imagine how he is going to process Flux :)

**Comment by spencergibb** [comment]
Your attitude and comments are very unfortunate.

**Comment by AnkBurov** [comment]
@spencergibb now you're the one who sounds not very polite. @kptfh is offering help on highly demanded feature. Pecking him to death is not helpful. 

Maybe you could spend some time and review that @kptfh PR?

**Comment by gnom7** [comment]
any updates on this please?

**Comment by kptfh** [comment]
Just finished Spring auto configuration
[https://github.com/Playtika/feign-reactive](https://github.com/Playtika/feign-reactive)

**Comment by Giftedl-Jarvis** [comment]
I wonder if feign now supports Webflux
@kptfh @spencergibb @ryanjbaxter

**Comment by kptfh** [comment]
Playtika feign supports WebFlux. We successfully use it on production for half a year.

**Comment by WithoutCaps** [comment]
Hello, 2020!!! 
Any updates on this?

**Comment by kptfh** [comment]
Just updated ReactiveFeign to support Load balancer and CircuitBreaker. You can use it in 2.0.0 release

**Comment by spencergibb** [comment]
No. For now I would suggest https://github.com/spring-cloud/spring-cloud-openfeign/issues/4#issuecomment-458514280

Marking for team discussion to see if this is something we want to pursue.

**Comment by spencergibb** [comment]
We're going to defer to the community project mentioned by @kptfh https://github.com/Playtika/feign-reactive

To aid in discovery of community projects, I've created https://github.com/spring-cloud/spring-cloud-commons/issues/686 to add a list to our docs.
