### ISSUE TITLE
Trailing slash in the end of path in @RequestMapping

### ISSUE THREAD

**Issue by igorbljahhin** [spring-cloud/spring-cloud-openfeign#405]
Hello,

Our application was using Spring Cloud Openfeign 2.0.1.RELEASE (shipped with Spring Boot Cloud Finchley.SR1; Openfeign 9.5.1) with MVC contract. Our Feign clients were looking like

```
@RequestMapping("/api/v1/reservation")
public interface ReservationResource {
    @PostMapping("{reservationId}/cancel")
    @ResponseBody
    ReservationDTO cancel(@PathVariable("reservationId") Integer reservationId, @RequestBody CancelReservationRequestDTO request);
}

@FeignClient(name = "reservation")
public interface ReservationClient extends ReservationResource {
}
```

and the call of `reservationClient.cancel` was sent to URL like `http://localhost:8080/api/v1/reservation/12345/cancel`, in other words Spring MVC or Feign was automatically adding a slash between path given in @RequestMapping and in @PostMapping annations.

After upgrade to Spring Cloud Openfeign 2.2.3.RELEASE (shipped with Spring Boot Cloud Hoxton.SR6; Openfeign 10.10.1) a slash is not added anymore. When we call `reservationClient.cancel` the request is sent to `http://localhost:8080/api/v1/reservation12345/cancel`.

What can we do to restore old Feign's behaviour? At the moment whole our application is broken due this change in Feign...

**Comment by OlgaMaciaszek** [comment]
@igorbljahhin This is probably due to [this bug](https://github.com/spring-cloud/spring-cloud-openfeign/issues/386), that has already been fixed. Can you check against `Hoxton.SR8`?

**Comment by igorbljahhin** [comment]
> @igorbljahhin This is probably due to [this bug](https://github.com/spring-cloud/spring-cloud-openfeign/issues/386), that has already been fixed. Can you check against `Hoxton.SR8`?

Yes, seems that new version has no this bug. I will close the issue. Thank you for help!
