### ISSUE TITLE
Bean 'com.example.demo.Client' of type [org.springframework.cloud.openfeign.FeignClientFactoryBean] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

### ISSUE THREAD

**Issue by BigMichi1** [spring-cloud/spring-cloud-openfeign#416]
**Describe the bug**
we have a lot of FeignClients in our application which are triggering a lot of INFO log messages regarding the problem then the clients are not eligible for being processed by all bean post-processors. these messages indicate that something is going wrong but not exactly what is the problem.

as this message is triggered by the core springframework it would be nice that the feign clients can be created in such a way that they are not triggering the information log message.

**Sample**
sample project: https://github.com/BigMichi1/openfeign-warning
the problem is when `@EnableAsync` annotation is added then the info message is triggered, if it is removed then no message is shown

**Comment by BigMichi1** [comment]
a similiar issue was reported already in #361 but when I debugged it this was not true anymore that a `null` was returned

**Comment by OlgaMaciaszek** [comment]
Hi, @BigMichi1 if I understand your comment correctly, the only issue here is that a warning or info log appears?

**Comment by BigMichi1** [comment]
@OlgaMaciaszek as far as i can tell yes it might be the "only" issue that a message is displayed tellingme that something is fishy even if it is not. But i have a feeling that there might be something else that has an influence on the functionallity of the created clients. this is the thing i do not know. i have only seen during debugging that 8 out of 12 postprocessors were called for the created client bean and 4 were just skipped. Do they have an impact on the client bean, i can not tell for sure as during mytesting it "seems" that everything works.
What the most confuses me and other devs inmy project is that no message is shown until someone adds an '@EnableAsync' annotation to one configuration and then the log file is full of these messages during the startup.

**Comment by OlgaMaciaszek** [comment]
@BigMichi1 Thanks for the answer.  These warnings are a known issue, but since we have not observed that the behaviour is hindered in any way, it has a very low priority, and we will not be working on it at this time.

**Comment by BigMichi1** [comment]
looks like this behaviour has been fixed now in spring-framework 5.3.14 with https://github.com/spring-projects/spring-framework/issues/27808
