### ISSUE TITLE
Use Spring Boot autoconfigure-processor to optimize auto-configurations

### ISSUE THREAD

**Issue by bclozel** [spring-cloud/spring-cloud-openfeign#43]
As explained in [the its reference documentation](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-docs/src/main/asciidoc/spring-boot-features.adoc#autoconfigure-module), Spring Boot provides a `spring-boot-autoconfigure-processor`.

This should be added as an optional dependency to the module that contains the AutoConfiguration classes (and contains the `spring.factories` file declaring them).

Once configured, this annotation processor will generate metadata at compile time and will help Spring Boot process those auto-configurations without loading the actual classes in some cases.

In this project, the `spring-cloud-openfeign-core` module declares auto-configurations but doesn't use this annotation processor. Could you add it to the build file of this module?

```xml
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-autoconfigure-processor</artifactId>
	<optional>true</optional>
</dependency>
```

Once added, this should generate a `spring-autoconfigure-metadata.properties` file in the `target/classes/META-INF` folder.

See https://github.com/spring-cloud/spring-cloud-commons/issues/377

**Comment by ryanjbaxter** [comment]
I thought I added this to all of our projects but I must have missed this one, thanks!

**Comment by hexiaogou** [comment]
> As explained in [the its reference documentation](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-docs/src/main/asciidoc/spring-boot-features.adoc#autoconfigure-module), Spring Boot provides a `spring-boot-autoconfigure-processor`.
> 
> This should be added as an optional dependency to the module that contains the AutoConfiguration classes (and contains the `spring.factories` file declaring them).
> 
> Once configured, this annotation processor will generate metadata at compile time and will help Spring Boot process those auto-configurations without loading the actual classes in some cases.
> 
> In this project, the `spring-cloud-openfeign-core` module declares auto-configurations but doesn't use this annotation processor. Could you add it to the build file of this module?
> 
> ```
> <dependency>
> 	<groupId>org.springframework.boot</groupId>
> 	<artifactId>spring-boot-autoconfigure-processor</artifactId>
> 	<optional>true</optional>
> </dependency>
> ```
> 
> Once added, this should generate a `spring-autoconfigure-metadata.properties` file in the `target/classes/META-INF` folder.
> 
> See [spring-cloud/spring-cloud-commons#377](https://github.com/spring-cloud/spring-cloud-commons/issues/377)

Thank you for your advice to the author, so the spring-autoconfigure-metadata.properties contained the feign configuration information ever since Finchley.SR2 version. I found this problem when I used IDEA IDE for studing Spring-Cloud-Feign knowledge with no auto tip during setting application.yml.
