### ISSUE TITLE
Hystrix Fallback not working

### ISSUE THREAD

**Issue by ramonmalcolm10** [spring-cloud/spring-cloud-openfeign#438]
**Describe the bug**
Fallback is being ignored with spring boot version 2.4.0 and spring cloud version 2020.0.0-M6. 

**Sample**
@FeignClient(
    value = "ecommerceClient",
    url = "${ecommerce-service.url}",
    configuration = EcommerceClientConfig.class,
        fallback = EcommerceClientFallback.class
)
public interface EcommerceClient {
}
class EcommerceClientFallback implements EcommerceClient {

}

feign:
  hystrix:
    enabled: true

**Comment by OlgaMaciaszek** [comment]
SC Netflix Hystrix is no longer supported. A CircuitBreaker integration is being added within [this issue](https://github.com/spring-cloud/spring-cloud-openfeign/issues/279). Closing in favour of that issue.
