### ISSUE TITLE
QueryMap doesn't conform to the set property naming style. 

### ISSUE THREAD

**Issue by Pilipets** [spring-cloud/spring-cloud-openfeign#439]
I have a feign client with spring boot app, that has a method signature like below - it uses SpringQueryMap to send URL parameters.
`@PostMapping(path="/api/services/helper/reduce")`
`ResponseEntity<List<String>> filterSupply(`
`@SpringQueryMap FilterTripParams params,`
`@RequestBody List<String> supply_list);`

The problem is mapped field names of the `params` are in the camel case while I expect them in the snake case since have `spring.jackson.property-naming-strategy=SNAKE_CASE`

Serialization and deserialization with the `@RequestBody` work as expected.
I would consider it a bug.

**Comment by OlgaMaciaszek** [comment]
@Pilipets thanks for reporting this. Please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by Pilipets** [comment]
As claimed originally in the description, serialization for an object with `@QueryMap` annotation ignores set property naming strategy in the `application.properties`, and always uses camel case.

1.5 months of waiting, and I finally got a kind of response to the reported issue.
Keeping that in mind, I don't find it worth spending time for a workable example to wait months again before getting a response.

Shame on you guys for making enthusiastic developers waiting months...
I was willing to support this thread and solve the problem, but at the moment of reporting the issue - not years after.

Close this issue as expected.

**Comment by spencergibb** [comment]
@Pilipets please be respectful. You opened an issue as we were completing a major release with a year's worth of work. Then many team members took time off over holidays. You have no concept of our lives outside of open source support.

**Comment by Pilipets** [comment]
@spencergibb  My fault, agree - just emotions cause I don't have a working example anymore, but I had it then.

**Comment by spencergibb** [comment]
Thanks
