### ISSUE TITLE
Deadlock may occure when Openfeign works with deferred JPA repository

### ISSUE THREAD

**Issue by michaldo** [spring-cloud/spring-cloud-openfeign#443]
Spring Cloud version "Hoxton.SR9"

Under some condition deadlock happens with  Openfeign + deferred JPA repository. I can reproduce the case only in tests.

I created a simple project to reproduce the problem: https://github.com/michaldo/feign-jpa-deffered-deadlock

I think the same case is reported on https://stackoverflow.com/questions/65078382/spring-boot-context-load-test-hangs

I guess the reason is that `FeignClientFactoryBean`  does not extend `AbstractFactoryBean`

**Comment by OlgaMaciaszek** [comment]
@michaldo Thanks for reporting this.

Further analysis:
From [here](https://github.com/spring-cloud/spring-cloud-openfeign/blob/5f932b01589370e933a4a14efe1d4464f340606f/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientFactoryBean.java#L104) new context is being created, which triggers `ContextRefreshedEvent`. `DataSourceInitializedPublisher` [listens on this event and tries to get `dataSourceInitialization` future](https://github.com/spring-projects/spring-boot/blob/bf9c67b793d67c1ffb569fd3c49114bacdb60755/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/orm/jpa/DataSourceInitializedPublisher.java#L148). This is causing a deadlock. 
`dataSourceIniitialization` is being initialized within the `postProcessEntityManagerFactory` method.

**Comment by OlgaMaciaszek** [comment]
The problem seems to be in Spring Boot. Have created https://github.com/spring-projects/spring-boot/issues/24966.  Also, upgrading to Boot `2.3.7` should help as the deferred mode was set to non-default (https://github.com/spring-projects/spring-boot/issues/24249).
Closing in favour of the Spring Boot issues.

**Comment by michaldo** [comment]
Initially Spring Boot guys told it is OpenFeing issue :)
