### ISSUE TITLE
customizable value object encoding

### ISSUE THREAD

**Issue by dicolar** [spring-cloud/spring-cloud-openfeign#45]
hi
I'm recently struggling with the problem of "Feign's client request with parameters' encoding".
I have found the key code in the method named 'encodeValueIfNotEncoded' of 'RequestTemplate.java'.
it uses the default 'toString' method to encode the parameter before it's ready to perform a POST request.
```java
private String encodeValueIfNotEncoded(String key, Object objectValue, Map<String, Boolean> alreadyEncoded) {
        String value = String.valueOf(objectValue); //the key line
        Boolean isEncoded = (Boolean)alreadyEncoded.get(key);
        if (isEncoded == null || !isEncoded) {
            value = urlEncode(value);
        }

        return value;
}
```

but usually the 'toString' method just returns a nonsense-string.
in my case, i defined an interface's method with multi POJO params.
just like `QueryResult<List<CouponModelInfo>> grantCoupon(@RequestParam("grantRequest") CouponGrantRequest grantRequest, @RequestParam("operatorInfo") OperatorInfo operatorInfo)`,and i wrote a custom arg-resolver so it can decode request param to pojo param(use jackson).
but,if the client is using the 'toString' method to encode the param, my arg-resolver is just useless.

can you support custom encoding in the next version?
for now, i have just copied the source code and changed the key line.

**Comment by ryanjbaxter** [comment]
If the problem is in the class `RequestTemplate` please open an issue in the OpenFeign repo https://github.com/OpenFeign/feign
