### ISSUE TITLE
I think this is a useless variable

### ISSUE THREAD

**Issue by learnprogram2** [spring-cloud/spring-cloud-openfeign#460]
https://github.com/spring-cloud/spring-cloud-openfeign/blob/5011703eb9eefd08cc6b8e1bd9354627d6b20405/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientsRegistrar.java#L162

**Comment by OlgaMaciaszek** [comment]
Indeed, it is - was left by mistake. Thanks for reporting it, @learnprogram2 .
