### ISSUE TITLE
FeignCircuitBreaker should override target(Target)

### ISSUE THREAD

**Issue by sleicht** [spring-cloud/spring-cloud-openfeign#464]
**Describe the bug**
If _Spring Cloud Circuitbreaker_ is used and feign client is created via annotation `FeignCircuitBreakerTargeter` doesn't call `target` method of `FeignCircuitBreaker` when no fallback is defined.

**Sample**
`@FeignClient(name = "Restadapter", url = "rest-endpoint", configuration = FeignClientConfiguration.class)`

**Comment by OlgaMaciaszek** [comment]
@sleicht could you please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue, including steps to reproduce, what you expect to happen and what is happening instead?

**Comment by sleicht** [comment]
@OlgaMaciaszek Sure. This test should be green: https://github.com/sleicht/FeignCircuitBreakerTest/blob/master/src/test/java/com/example/openfeign/FeignClientServiceTest.java

**Comment by OlgaMaciaszek** [comment]
@sleicht In fact, that should work. Will provide a fix today.

**Comment by sleicht** [comment]
Thank you for the quick fix.
