### ISSUE TITLE
feign.Request.Options should be RefreshScope beans to refresh connectTimeout and readTimeout

### ISSUE THREAD

**Issue by jas34** [spring-cloud/spring-cloud-openfeign#468]
**In production we need to adjust feign client connectTimeout and readTimeout frequently due to some unavoidable circumstances**
Feign comes with out of the box connectTimeout and readTimeout support at default level `feign.client.default` or contextId level `feign.client.{contextId}`. Since these properties are applied at the time of FeignClient creation and there is no way to refresh these settings via `/actuator/refresh` other than re-deploying or restarting the spring boot application again.

`@RefreshScope` cannot be used on the class with `@FeignClient` because every feign client is a proxy instances of an interface.

**Possible solution**
- FeignClient when constructed from `org.springframework.cloud .openfeign.FeignClientFactoryBean` should be composed with Refresh scoped `feign.Request.Options` bean for each FeignClient instance.
- Then `/actuator/refresh` will be able to refresh `feign.Request.Options` and hence connectTimeout and readTimeout.

**Additional context**
If request looks justified then I can share idea and approach in more detail.

**Comment by OlgaMaciaszek** [comment]
Hello, @jas34 . Will discuss with the team and get back to you.

**Comment by jas34** [comment]
@OlgaMaciaszek any feedback yet?

**Comment by jas34** [comment]
@OlgaMaciaszek did you get a chance to discuss this?

**Comment by jas34** [comment]
@OlgaMaciaszek anything on this yet?

**Comment by OlgaMaciaszek** [comment]
Sorry for getting back so late - have overlooked this issue. We  are not planning to be working on it, however, if you would like to provide a PR, we could add it as an enhancement.

**Comment by jas34** [comment]
Sure, I will share PR soon.

**Comment by jas34** [comment]
@OlgaMaciaszek  I am done with development and need to raise PR but I am not able to push code as I am getting 403 from git with below error.
**remote: Permission to spring-cloud/spring-cloud-openfeign.git denied to jas34.
fatal: unable to access 'https://github.com/spring-cloud/spring-cloud-openfeign.git/': The requested URL returned error: 403**

As mentioned in [Contributing](https://github.com/spring-cloud/spring-cloud-openfeign#3-contributing) I have gone through [Individual Contributor License Agreement](https://cla.pivotal.io/sign/pivotal/icla) but not getting any option to accept the agreement.
Can you please help, looks like I am missing something?

**Comment by jas34** [comment]
Here is PR https://github.com/spring-cloud/spring-cloud-openfeign/pull/526
