### ISSUE TITLE
Configure circuit breaker by using method signature 

### ISSUE THREAD

**Issue by Ferioney** [spring-cloud/spring-cloud-openfeign#484]
I have two methods with the same name but with different signatures:
```
@FeignClient(
        name = "client",
        path = "/client"
)
public interface Client {
    @PostMapping
    Response create(@RequestBody Options options);

    @PostMapping
    Response create();
}
```
In `spring-cloud-openfeign 2.2.6` I could configure Hystrix's circuit breaker for these two methods:

```
hystrix.command.Client#create(Options).execution.isolation.thread.timeoutInMilliseconds
hystrix.command.Client#create().execution.isolation.thread.timeoutInMilliseconds
```

but as I see from version `2.2.7`. circuit breaker name follows the pattern `clientName_methodName`, so I don't see a possibility to configure the circuit breakers separately.
Is it possible now to configure circuit breakers by using method signature?

**Comment by OlgaMaciaszek** [comment]
Do you mean that the behaviour of Hystrix in SC OpenFeign has changed or that CircuitBreaker behaves differently?

**Comment by OlgaMaciaszek** [comment]
@Ferioney this behaviour is, in fact, different. Will add the possibility to use full method signatures.

**Comment by Ferioney** [comment]
@OlgaMaciaszek thanks!

**Comment by OlgaMaciaszek** [comment]
Actually, since there was a behaviour change, I am marking it is a bug and am going to revert to the earlier behaviour.

**Comment by OlgaMaciaszek** [comment]
This actually only affects the new way of adding circuit-breaking (the `feign-hystrix` approach still works as before), however as it makes configuring overloaded methods impossible and is not in keeping with the Feign `configKey` format, which has been used in OpenFeign circuit-breaking before, I'm going to treat it as a bug anyway and change it for the new `Hoxton` and `2020` releases as opposed to adding as an alternative.
