### ISSUE TITLE
Openfeign with vavr integration

### ISSUE THREAD

**Issue by Opalo** [spring-cloud/spring-cloud-openfeign#51]
Hi,

First of all - thanks for cool work! Secondly, is there any way for openfeign to return [`io.vavr.control.Try`](https://static.javadoc.io/io.vavr/vavr/0.9.2/io/vavr/control/Try.html) (or maybe other types also) instead of throwing exceptions? I know a custom `Decoder` and `ErrorDecoder` can be implemented however no idea - after quick research - if this is doable.

**Comment by ryanjbaxter** [comment]
I have never tried this before, but maybe if you tried implementing your own `Decoder`.

**Comment by Opalo** [comment]
Thanks for a prompt response @ryanjbaxter. Do you think that implementing a `Decoder` will be sufficient? Since status code are checked in a different place. I suppose a decoder might be too late.

**Comment by ryanjbaxter** [comment]
Like I said I am not 100% sure given I have not done it before, sorry I cant be much help.

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
