### ISSUE TITLE
“;” isn't treated as "/;" in Spring Cloud Openfeign client

### ISSUE THREAD

**Issue by Spillage** [spring-cloud/spring-cloud-openfeign#519]
Hi there,
  I am facing a weird problem in my project. Here is the scenario.
  There are service a and service b, and  a -> b by feign client.

  When calling http://localhost:8080/feign?test=1&a=1;1, feign client treated "a=1;1" as "a=1&a=1" and it occurs in 10.X of Spring Cloud Openfeign which works well in 9.X.
  
  Can someone help to look into this problem?

**Comment by OlgaMaciaszek** [comment]
Duplicates https://github.com/spring-cloud/spring-cloud-openfeign/issues/395. Root issue: https://github.com/OpenFeign/feign/issues/1319. Closing in favour of https://github.com/spring-cloud/spring-cloud-openfeign/issues/395.
