### ISSUE TITLE
HystrixSecurityTests.testFeignHystrixSecurity() fails after 2.1.0 upgrade

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-openfeign#52]
The custom CustomConcurrenyStrategy is not called :-(

**Comment by ryanjbaxter** [comment]
Assert now passes when uncommented.   ¯\_(ツ)_/¯  https://github.com/spring-cloud/spring-cloud-openfeign/commit/dd7b869a121878d511b5891a3e038c06fc018145
