### ISSUE TITLE
How to set the global url

### ISSUE THREAD

**Issue by social-uni** [spring-cloud/spring-cloud-openfeign#527]
I don’t want to set the url once on each class. Is there any way to configure the global url? I didn’t use the configuration center

**Comment by OlgaMaciaszek** [comment]
The `url` has to be set via annotation attribute, however, you can use placeholders, like so:

```java
@FeignClient(name = "${feign.name}", url = "${feign.url}")
public interface StoreClient {
    //..
}
```
and then set `feign.url` in properties. See [related documentation](https://docs.spring.io/spring-cloud-openfeign/docs/current/reference/html/#spring-cloud-feign-overriding-defaults).
