### ISSUE TITLE
Add check for null object 

### ISSUE THREAD

**Issue by rcbandit111** [spring-cloud/spring-cloud-openfeign#538]
**Describe the bug**
When I send null object I get wrong message: _no suitable HttpMessageConverter found for request type with Feign_

Add check and appropriate debug message.

**Sample**
Ref https://stackoverflow.com/questions/67376764/could-not-write-request-no-suitable-httpmessageconverter-found-for-request-type

**Comment by cbezmen** [comment]
Is this solved? @rcbandit111

**Comment by rcbandit111** [comment]
no, I don't have updated on this topic

**Comment by cbezmen** [comment]
I didn't understand the real problem in here. In the stackoverflow example; there is no getter/setter RegisterUserDTO. When Jackson check the pojo canSerialize, however the object is not serializable for jackson.

```java
new ObjectMapper().canSerialize(RegisterUserDTO.class, causeRef); 
```

This will return false. So [Spring encoder](https://github.com/spring-cloud/spring-cloud-openfeign/blob/5aa1b7a5298d985e9e103da3752c932b0ebc4200/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/SpringEncoder.java#L112) can't find suitable converter to encode your object. So it throws: 

> Could not write request: no suitable HttpMessageConverter found for request type

I think message is clear.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
