### ISSUE TITLE
Can`t set feign.hystrix in yml 

### ISSUE THREAD

**Issue by RichardReindeer** [spring-cloud/spring-cloud-openfeign#550]
openFeign 2.2.8 R

no 'feign.hystrix' choice in yml

**Comment by cbezmen** [comment]
I didn't understand the question. Could you give me more detail?

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
