### ISSUE TITLE
False warning "The provided URL is empty. Will try picking an instance via load-balancing."

### ISSUE THREAD

**Issue by michaldo** [spring-cloud/spring-cloud-openfeign#552]
Branch 2.2.x
When  I follow reference documentation and create

`@FeignClient("stores")`

I got false warning

> 2021-06-05 22:11:55.300  WARN 3468 --- [           main] o.s.c.openfeign.FeignClientFactoryBean   : The provided URL is empty. Will try picking an instance via load-balancing.

Url is optional and absence should not cause warning

Reason: commit 5e494aa1 for https://github.com/spring-cloud/spring-cloud-openfeign/issues/517

**Sample**
Run org.springframework.cloud.openfeign.beans.FeignClientTests#testAnnotations

**Comment by OlgaMaciaszek** [comment]
Changed to `INFO` log level.

**Comment by ingogriebsch** [comment]
I'm facing the same problem if I use spring-cloud-dependencies in version 2020.0.3. The version of the managed starter is 3.0.3.
