### ISSUE TITLE
feign can't support ipv6 request 

### ISSUE THREAD

**Issue by qixie1** [spring-cloud/spring-cloud-openfeign#557]
**Describe the bug**
I registered service to eruake use IPv6 address and @FeignClient to request the service. it's dosn't work !!

**Sample**
1、service run ok and registered  to eruake 
![image](https://user-images.githubusercontent.com/29743801/122222743-1fb94400-cee5-11eb-954e-e86d10b77aeb.png)
![image](https://user-images.githubusercontent.com/29743801/122222850-3c557c00-cee5-11eb-94ad-35ce460e3c44.png)

2、request to the service error
![image](https://user-images.githubusercontent.com/29743801/122222363-c5b87e80-cee4-11eb-8284-e3761dc22837.png)
![image](https://user-images.githubusercontent.com/29743801/122222423-d537c780-cee4-11eb-9f58-cc33465223bb.png)

**Comment by qixie1** [comment]
Adding brackets works., change config ip-address 2001:da8:2:10d::36 to [2001:da8:2:10d::36]

**Comment by OlgaMaciaszek** [comment]
@qixie1 If I understand correctly, you have a workaround?

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
