### ISSUE TITLE
Switch remaining jUnit 4 tests to jUnit jupiter

### ISSUE THREAD

**Issue by OlgaMaciaszek** [spring-cloud/spring-cloud-openfeign#563]

**Comment by Syemon** [comment]
Hi, I would like to work on this issue.

**Comment by OlgaMaciaszek** [comment]
Hi @Syemon - great :) . Just please let us know if you will be converting the entire project or just some specific modules or packages.

**Comment by OlgaMaciaszek** [comment]
@Syemon Please add your changes against the `3.0.x` branch.

**Comment by OlgaMaciaszek** [comment]
@Syemon Please let me know what your planned timeline is for submitting this PR.

**Comment by Syemon** [comment]
@OlgaMaciaszek I plan submitting this PR on Monday 02.08

**Comment by Syemon** [comment]
@OlgaMaciaszek I have created draft because I am not sure about one test.
