### ISSUE TITLE
How to disable Feign's IOException retry logic

### ISSUE THREAD

**Issue by yoongang** [spring-cloud/spring-cloud-openfeign#570]
When my Feign client throws IOExceptions, it automatically retries the request. I want to disable this retry.
Now I'm using spring-cloud-starter-openfeign.

- spring-cloud-starter-openfeign
- version: 3.0.0

I do not define any configuration about Feign.

So I think my Feign client is created with Retryer.NEVER_RETRY which will disable retrying.

But the [document](https://docs.spring.io/spring-cloud-openfeign/docs/current/reference/html/#spring-cloud-feign-overriding-defaults) says 

"_Notice this retrying behavior is different from the Feign default one, where it will automatically retry IOExceptions, treating them as transient network related exceptions, and any RetryableException thrown from an ErrorDecoder._"

Actually when my Feign client request file upload, it often throws IOExceptions and retry request (**infinite IOExceptions -> infinite request**)

How can I disable Feign's IOExceptions retry logic?

**Comment by OlgaMaciaszek** [comment]
@yoongang Please provide the version you are using. Also, do you have `spring-retry` in your classpath?

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
