### ISSUE TITLE
Upgrade to newer feign version

### ISSUE THREAD

**Issue by MelleD** [spring-cloud/spring-cloud-openfeign#571]
There is a newer feign version 11.2 available. The version should be raised or is there a reason against it?

**Comment by cbezmen** [comment]
Hi @MelleD,

Feign version already upgraded on 3.x.x. Please check https://github.com/spring-cloud/spring-cloud-openfeign/tree/3.1.x

**Comment by MelleD** [comment]
@cbezmen thanke for the quick answer. Then I wait for the next release. 
Is there already a date?
