### ISSUE TITLE
Allow to change a circuitbreaker name

### ISSUE THREAD

**Issue by bananayong** [spring-cloud/spring-cloud-openfeign#574]
**Is your feature request related to a problem? Please describe.**

**We need a flag or option for legacy circuit breaker name.**

We are using 2020.0.0 version (spring cloud version).
Recently, I updated version upto 2020.0.3 and I realized that this version includes breaking change. Actually 2020.0.2 version.
https://github.com/spring-cloud/spring-cloud-openfeign/commit/11fd7dc43ed693313b8b511a596cba4252b4491d#diff-6aadece31f2eb772088dd7e2e2b63d5bbf52c7080c602500197125dcca493488R79

If, circuit breaker name is changed, many metric names will also be affected and many configurations for resilience4j (if resilience4j spring-boot module is used) also need to be changed.

**Describe the solution you'd like**

**If a developer can change circuitbreaker name, It will be very helpful!**
ex) CircuitBreakerNameResolver interface

**Describe alternatives you've considered**

**Additional context**

**Comment by OlgaMaciaszek** [comment]
@bananayong Thanks for reporting this. You're right - that was a breaking change, however, we decided to go on with it, as it actually was a bugfix. Definitely, the enhancement you describe should be added.
