### ISSUE TITLE
bump OpenFeign version to at least 11.3

### ISSUE THREAD

**Issue by BigMichi1** [spring-cloud/spring-cloud-openfeign#581]
**Describe the bug**
current master uses OpenFeign version 11.2, but when this one goes live we can not build our projects anymore because of another dependency (https://github.com/OpenFeign/feign-annotation-error-decoder) managed until version 11.2 by a different maintainer in OpenFeign repository has not been updated to version 11 (still only works for version 10.x). Starting with version 11.3 this subproject has been included in the main repository and is now part and also compatible with OpenFeign 11.

it would be really helpful to increase the OpenFeign version to 11.3 (https://github.com/OpenFeign/feign/releases/tag/11.3)

**Comment by OlgaMaciaszek** [comment]
@BigMichi1 thanks for reporting this. Makes sense. Will bump it. Btw., what is currently on `main`, will be going into the new `2021.0.0` release train (M1 planned for this week). The `2020.0` release train work has been moved over to the `3.0.x` branch.

**Comment by OlgaMaciaszek** [comment]
Could not upgrade to `11.5` due to [this issue](https://github.com/OpenFeign/feign/issues/1466). Have bumped it to `11.4` instead.
