### ISSUE TITLE
Fix possible outdated docs

### ISSUE THREAD

**Issue by quaff** [spring-cloud/spring-cloud-openfeign#585]
**Describe the bug**
https://cloud.spring.io/spring-cloud-openfeign/reference/html/#spring-cloud-feign-inheritance
> It is generally not advisable to share an interface between a server and a client. It introduces tight coupling, and also actually doesn’t work with Spring MVC in its current form (method parameter mapping is not inherited).

I'm sharing interface between `@RestController` and `@FeignClient`, It's works fine with latest Spring MVC.

**Comment by OlgaMaciaszek** [comment]
Ok, thanks @quaff, I will update the doc, however, I still would say it's not advisable to do it.
