### ISSUE TITLE
Feign Client failed to resolve @RequstMapping on interface with inheritance

### ISSUE THREAD

**Issue by sialais** [spring-cloud/spring-cloud-openfeign#587]
**Describe the bug**
Rest API Interface with inheritance, the @RequestMapping annotation will be ignored.

**Sample**

```java
public interface Foo {

}

@RequestMapping(path="/bar")
public interface Bar extends Foo{
  @GetMapping("xxx")
  Object someMethod();
}

```
if i use Bar as interface to generate a feign client, the uri call to someMethod will lose "/bar" 

I checked the code, and quiet confused with the code in [`org.springframework.cloud.openfeign.support.SpringMvcContract$processAnnotationOnClass`](https://github.com/spring-cloud/spring-cloud-openfeign/blob/main/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/SpringMvcContract.java#L172) that
 `clz.getInterfaces().length == 0`

```java

	@Override
	protected void processAnnotationOnClass(MethodMetadata data, Class<?> clz) {
		if (clz.getInterfaces().length == 0) {
        ...
```
the call to this method has already handled inheriance: 
code in [`feign.Contract`](https://github.com/OpenFeign/feign/blob/master/core/src/main/java/feign/Contract.java#L103)

```java
    protected MethodMetadata parseAndValidateMetadata(Class<?> targetType, Method method) {
      final MethodMetadata data = new MethodMetadata();
      data.targetType(targetType);
      data.method(method);
      data.returnType(Types.resolve(targetType, targetType, method.getGenericReturnType()));
      data.configKey(Feign.configKey(targetType, method));

      if (targetType.getInterfaces().length == 1) {
        processAnnotationOnClass(data, targetType.getInterfaces()[0]);
      }
      processAnnotationOnClass(data, targetType);
     ...
```
I think the statement `if (clz.getInterfaces().length == 0)` 
[`org.springframework.cloud.openfeign.support.SpringMvcContract$processAnnotationOnClass`](https://github.com/spring-cloud/spring-cloud-openfeign/blob/main/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/SpringMvcContract.java#L172) may be removed.

**Comment by cbezmen** [comment]
Hi @sialais,

Please read gh-564

**Comment by cbezmen** [comment]
> if i use Bar as interface to generate a feign client, the uri call to someMethod will lose "/bar"

When I read this. I think you will use Bar class as interface to your FeignClient. In Feign `path` variable is used to define path and There is no way to inherit it. As @OlgaMaciaszek mentioned [here](https://github.com/spring-cloud/spring-cloud-openfeign/issues/564#issuecomment-877090630), I think you can't use @RequestMapping annotation on inherited interface of FeignClient.

**Comment by sialais** [comment]
> > if i use Bar as interface to generate a feign client, the uri call to someMethod will lose "/bar"
> 
> When I read this. I think you will use Bar class as interface to your FeignClient. In Feign `path` variable is used to define path and There is no way to inherit it. As @OlgaMaciaszek mentioned [here](https://github.com/spring-cloud/spring-cloud-openfeign/issues/564#issuecomment-877090630), I think you can't use @RequestMapping annotation on inherited interface of FeignClient.

Yes, Bar is the interface of FeignClient, and path variable is not inherited from Foo.
Foo can be some interface just to mark, like `Serializable`, and this inheritance will make `@RequestMapping` be ignored.

**Comment by sialais** [comment]
By the way, I think it is resonable to use `@RequestMapping` annotation on child interface and **ignore** annotation on parent interface if the annotation both on child and parent. (`@RequestMapping` can be overrided), as the way url mapping in springMVC.

**Comment by OlgaMaciaszek** [comment]
Yes, as @cbezmen has noted, this is not advisable and not supported. Please see the note at the end of [this section](https://docs.spring.io/spring-cloud-openfeign/docs/current/reference/html/#spring-cloud-feign-inheritance).
