### ISSUE TITLE
Is it possible to create @Around Aspect for feign.Client?

### ISSUE THREAD

**Issue by abhishekhbd** [spring-cloud/spring-cloud-openfeign#59]
If not then what is the other way I want to add additional properties for logs for Feign.

**Comment by ryanjbaxter** [comment]
Can explain what you are trying to log?

**Comment by ryanjbaxter** [comment]
Why does using an interceptor not work?

**Comment by abhishekhbd** [comment]
How to get response time using interceptor?

**Comment by ryanjbaxter** [comment]
Maybe you can do something like provide your own `LoadBalancerFeignClient` bean and add the logging you need to the `execute` method.

**Comment by zzhi** [comment]
There is a demo ：
`@Aspect
@Component
public class FeignClientAspect {

    private static final Logger LOGGER = LoggerFactory.getLogger(FeignClientAspect.class);

    @Pointcut("execution(* org.springframework.cloud.netflix.feign.ribbon.LoadBalancerFeignClient.*(..))")
    public void feignClientPointcut() {
    }

    @org.aspectj.lang.annotation.Around("feignClientPointcut()")
    public Object doAround(ProceedingJoinPoint joinPoint) throws Throwable {

        LOGGER.info("feignclient begin");
        Object object = joinPoint.getTarget();

        if (!(object instanceof LoadBalancerFeignClient)) {
            LOGGER.info("feignclient not LoadBalancerFeignClient");
            return joinPoint.proceed();
        }
        Object[] args = joinPoint.getArgs();
        for (Object obj : args) {
            if (obj instanceof Request) {
                Request request = (Request) obj;
                LOGGER.info("feignclient request url:{}", request.url());
            }
        }
        long start = System.currentTimeMillis();
        Object result = joinPoint.proceed();
        if (result instanceof Response) {
            Response response = (Response) result;

            StringWriter writer = new StringWriter();
            IOUtils.copy(response.body().asInputStream(), writer, "UTF-8");
            String theString = writer.toString();

            LOGGER.info("feignclient response body:{}", theString);
        }
        LOGGER.info("feignclient end :{}", (System.currentTimeMillis() - start));
        return result;
    }
}`

**Comment by abhishekhbd** [comment]
Exactly this the code that I also implemented.

**Comment by JAXma1996** [comment]
> Exactly this the code that I also implemented. Thank you so much.
HI,I meet a problem that 


> There is a Demo ：
> @aspect
> @component
> public class FeignClientAspect {
> 
> ```
> private static final Logger LOGGER = LoggerFactory.getLogger(FeignClientAspect.class);
> 
> @Pointcut("execution(* org.springframework.cloud.netflix.feign.ribbon.LoadBalancerFeignClient.*(..))")
> public void feignClientPointcut() {
> }
> 
> @org.aspectj.lang.annotation.Around("feignClientPointcut()")
> public Object doAround(ProceedingJoinPoint joinPoint) throws Throwable {
> 
>     LOGGER.info("feignclient begin");
>     long start = System.currentTimeMillis();
>     Object object = joinPoint.getTarget();
> 
>     if (!(object instanceof LoadBalancerFeignClient)) {
>         LOGGER.info("feignclient not LoadBalancerFeignClient");
>         return joinPoint.proceed();
>     }
>     Object[] args = joinPoint.getArgs();
>     for (Object obj : args) {
>         if (obj instanceof Request) {
>             Request request = (Request) obj;
>             LOGGER.info("feignclient request url:{}", request.url());
>         }
>     }
>     Object result = joinPoint.proceed();
>     if (result instanceof Response) {
>         Response response = (Response) result;
> 
>         StringWriter writer = new StringWriter();
>         IOUtils.copy(response.body().asInputStream(), writer, "UTF-8");
>         String theString = writer.toString();
> 
>         LOGGER.info("feignclient response body:{}", theString);
>     }
>     LOGGER.info("feignclient end ,耗时:{}", (System.currentTimeMillis() - start));
>     return result;
> }
> ```
> }

Hi, Why can't I  get args in your code.

**Comment by chenkunyun** [comment]
> > Exactly this the code that I also implemented. Thank you so much.
> > HI,I meet a problem that
> 
> > There is a Demo ：
> > @aspect
> > @component
> > public class FeignClientAspect {
> > ```
> > private static final Logger LOGGER = LoggerFactory.getLogger(FeignClientAspect.class);
> > 
> > @Pointcut("execution(* org.springframework.cloud.netflix.feign.ribbon.LoadBalancerFeignClient.*(..))")
> > public void feignClientPointcut() {
> > }
> > 
> > @org.aspectj.lang.annotation.Around("feignClientPointcut()")
> > public Object doAround(ProceedingJoinPoint joinPoint) throws Throwable {
> > 
> >     LOGGER.info("feignclient begin");
> >     long start = System.currentTimeMillis();
> >     Object object = joinPoint.getTarget();
> > 
> >     if (!(object instanceof LoadBalancerFeignClient)) {
> >         LOGGER.info("feignclient not LoadBalancerFeignClient");
> >         return joinPoint.proceed();
> >     }
> >     Object[] args = joinPoint.getArgs();
> >     for (Object obj : args) {
> >         if (obj instanceof Request) {
> >             Request request = (Request) obj;
> >             LOGGER.info("feignclient request url:{}", request.url());
> >         }
> >     }
> >     Object result = joinPoint.proceed();
> >     if (result instanceof Response) {
> >         Response response = (Response) result;
> > 
> >         StringWriter writer = new StringWriter();
> >         IOUtils.copy(response.body().asInputStream(), writer, "UTF-8");
> >         String theString = writer.toString();
> > 
> >         LOGGER.info("feignclient response body:{}", theString);
> >     }
> >     LOGGER.info("feignclient end ,耗时:{}", (System.currentTimeMillis() - start));
> >     return result;
> > }
> > ```
> > }
> 
> Hi, Why can't I get args in your code.
> 
> I have added a log to get args.length after "Object[] args = joinPoint.getArgs();" .
> And I can only get 0 ...
> 
> hope your help..

@JAXma1996 
hi, JAXma1996
I've tried the code above, and joinPoint.getArgs() works quite well as expected(returns an array of 2).
I suggest you step into joinPoint.getArgs() to see what's really happening
