### ISSUE TITLE
nullpointexception

### ISSUE THREAD

**Issue by M1NGc** [spring-cloud/spring-cloud-openfeign#593]
![image](https://user-images.githubusercontent.com/26264126/129144089-82eaa793-02af-4ca7-af8e-a6ad3f53e4e9.png)
feign-form 3.5

**Comment by OlgaMaciaszek** [comment]
Hello, @M1NGc. Please describe the issue, including the steps to reproduce, the expected result and the actual result. Also, please 
provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
