### ISSUE TITLE
How to custom load balance strategy

### ISSUE THREAD

**Issue by zl7261** [spring-cloud/spring-cloud-openfeign#60]
I want to custom load balance strategy  rather than default round strategy.
According this question, I tried, but my project can't run it over ,and without error message.
https://stackoverflow.com/questions/42505136/how-can-i-adjust-load-balancing-rule-by-feign-in-spring-cloud.

Spring boot 2.0.4 RELEASE.

**Comment by ryanjbaxter** [comment]
What is not working?  Can you provide a sample demonstrating the problem?

**Comment by zl7261** [comment]
https://github.com/zl7261/freego/blob/master/freego-official-website-consumer/src/main/java/com/freego/official/website/consumer/feign/ProducerFeign.java
When I change the annotation from FeignClient to RibbonClient ,this project will shut down ,and I don't see any error message.
I wonder maybe this question is asked 2 year ago,perhaps this way won't work in spring boot 2.

**Comment by zl7261** [comment]
https://github.com/zl7261/freego
It's ok now.
First I think I should replace annotation feignclient with ribbon client.
But I know it's just put an annotation ribbonclient in springboot application class,
and it's same to do with custom ribbon load balance strategy.
I think the reason I couldn't run it cause I put  ribbonclient annotation on Feign not on the spring boot application class.
ty.
