### ISSUE TITLE
Documentation SimpleDiscoveryClient reference a broken link

### ISSUE THREAD

**Issue by ffroliva** [spring-cloud/spring-cloud-openfeign#601]
Reading:

https://docs.spring.io/spring-cloud-openfeign/docs/current/reference/html/

![image](https://user-images.githubusercontent.com/25033371/133124589-90195b0e-85e6-4251-a2c8-b37f9c07bee9.png)

`SimpleDiscoveryClient` link redirects to the following broken link.

https://cloud.spring.io/spring-cloud-static/spring-cloud-commons/current/reference/html/#simplediscoveryclient

**Comment by cbezmen** [comment]
Fixed in ch-603

**Comment by OlgaMaciaszek** [comment]
Done.
