### ISSUE TITLE
feign.RetryableException: Socket closed executing POST URI

### ISSUE THREAD

**Issue by ChinaMjm** [spring-cloud/spring-cloud-openfeign#615]
I encountered an exception when I tried to call service B from service A
Service A calls service B, and service A prompts that the socket is close. B confirms that it has received the request, processed it and returned the message. What is the reason
![image](https://user-images.githubusercontent.com/36297763/137468781-b87e90ee-1bf5-4332-9244-786ea08b0ec4.png)

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
