### ISSUE TITLE
FeignClient returns empty results when azure key vault dependency include in  build.gradle

### ISSUE THREAD

**Issue by vjaybhas1** [spring-cloud/spring-cloud-openfeign#617]
Hello Everyone,
I am experiencing the weird issue with Azure keyvault dependency and OpenFeign(FeignClient)
I am using FeignClient to invoke  REST endpoint in springboot. It works fine. However, When I include below dependency for azure keyvault in build.gradle, endpoint returns empty results. 
If I exclude the below dependency, I am able to see the results form endpoint.
Azure key vault dependency:
compile("com.azure.spring:azure-boot-starter-keyvault-secrets:3.6.0")

open feign dependencies:
compile("org.springframework.cloud:spring-cloud-starter-openfeign:2.1.3.RELEASE")
compile("io.github.openfeign:feign-okhttp")

SpringbootVersion :2.3.12
SpringCloudVersion: "Greenwich.M2"

Please let me know if anybody experienced the same issue.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
