### ISSUE TITLE
Application doesn't start with the last SNAPSHOT spring-clould-loadBalancer 

### ISSUE THREAD

**Issue by Ferioney** [spring-cloud/spring-cloud-openfeign#620]
spring-cloud-dependencie: 2021.0.0-SNAPSHOT (includes fix [Adds config per load balancer client](https://github.com/spring-cloud/spring-cloud-commons/pull/1028))

I have tried to test feign client with the last load balancer (snapshot version) which includes the possibility to configure load-balance per client.
Feign [DefaultFeignLoadBalancerConfiguration](https://github.com/spring-cloud/spring-cloud-openfeign/blob/main/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/loadbalancer/DefaultFeignLoadBalancerConfiguration.java) class uses `@EnableConfigurationProperties({LoadBalancerProperties.class})`. But in last spring-cloud-common `@ConfigurationProperties` annotation was removed from class `LoadBalancerProperties`.

Application doesn't start with error:
```
Caused by: java.lang.IllegalStateException: No ConfigurationProperties annotation found on  'org.springframework.cloud.client.loadbalancer.LoadBalancerProperties'.
```

**Comment by OlgaMaciaszek** [comment]
Fixed with https://github.com/spring-cloud/spring-cloud-openfeign/commit/5fee522f4ccc2c4b1f6a4fee241bf70e73e2a4f6.
