### ISSUE TITLE
3.0.5 has parent 3.0.4

### ISSUE THREAD

**Issue by ewoks** [spring-cloud/spring-cloud-openfeign#623]
Not sure if it is intentional or typo but `spring-cloud-openfeign` Version `3.0.5` has as parent `spring-cloud-build` Version `3.0.4`
As a consequence some of dependencies are still on old version, despite update to v3.0.5, e.g.:
org.springframework.cloud:spring-cloud-openfeign-core:3.0.4

![OpenFeign_20211104_090254](https://user-images.githubusercontent.com/1666500/140278474-073f276d-170d-40b4-96aa-a7de88352bbd.png)

**Comment by OlgaMaciaszek** [comment]
SC build was `3.0.4` on purpose, however `spring-cloud-openfeign-core` should be `3.0.5`, and this is what is in the [pom](https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-starter-openfeign/3.0.5/spring-cloud-starter-openfeign-3.0.5.pom).

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by ewoks** [comment]
Thanks for the answer @OlgaMaciaszek . However, I am still not sure is this configuration issue on my side or something is wrong with the build. As you see in a screenshot, I got 3.0.4 that leaked in although spring-cloud-starter-openfeign is 3.0.5

**Comment by OlgaMaciaszek** [comment]
That probably comes from dependency management. As a workaround could you add:

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
