### ISSUE TITLE
Why there is no code tag for the 2.2.10.RELEASE version?

### ISSUE THREAD

**Issue by zwwtj2014** [spring-cloud/spring-cloud-openfeign#626]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

have a tag for the 2.2.10.RELEASE version

**Comment by OlgaMaciaszek** [comment]
@zwwtj2014 Thanks for submitting the issue. Fixed: https://github.com/spring-cloud/spring-cloud-openfeign/releases/tag/v2.2.10.RELEASE.
