### ISSUE TITLE
Error in paginated calls in Spring Cloud Hoxton.SR11/SR12

### ISSUE THREAD

**Issue by dienarvil** [spring-cloud/spring-cloud-openfeign#627]
Hello, It seems that there is a bug with Spring Cloud Hoxton.SR11 / SR12 when calling paginated end points with feign.

I am using Spring boot 2.2.5.RELEASE

How to reproduce it:

```
Client:

@PostMapping(path = "/filterp")
    Page<EmailTemplateDTO> testp(@RequestBody EmailTemplateRequestDTO emailTemplateRequestDTO,@SpringQueryMap Pageable pageable);
```

```
Server:

@PostMapping("/filterp")
    public ResponseEntity<Page<EmailTemplateDTO>> testp(@RequestBody EmailTemplateRequestDTO emailTemplateRequestDTO, @PageableDefault(size = 50) Pageable pageable)
```

If I use Spring Cloud Hoxton.SR10 the call works properly. But when I use SR11 or SR12 I recieve the next error:

**Open Feign java.lang.NoSuchFieldError: MULTIPART_RELATED ....**

It seems that IN SR11 a bug was added when using paginated calls.

So I decided to use the last version of spring boot (2.5.6) and spring cloud (2020.0.4) to test if it was my mistake, but It works perfectly.

**Comment by OlgaMaciaszek** [comment]
Hello, @dienarvil `Hoxton` is no longer supported (only security issues are being addressed). Please upgrade to `2020.0.x` or `2021.0.x` and let us know if the issue persists.

**Comment by dienarvil** [comment]
With spring boot (2.5.6) and spring cloud (2020.0.4) works perfectly.

I thought Hoxton still has receiving bugs support.

Thank  you
