### ISSUE TITLE
Use Spring Boot configuration-processor to generate configuration metadata

### ISSUE THREAD

**Issue by nicklasholm** [spring-cloud/spring-cloud-openfeign#63]
Spring Boot configuration-processor should be added to `spring-cloud-openfeign-core` module to enable generation of configuration metadata.
```xml
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-configuration-processor</artifactId>
    <optional>true</optional>
</dependency>
```
Spring Boot [reference documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/configuration-metadata.html#configuration-metadata-annotation-processor).

**Comment by ryanjbaxter** [comment]
Closed via a33fd6d
