### ISSUE TITLE
How feign retry works?

### ISSUE THREAD

**Issue by sunilkale24** [spring-cloud/spring-cloud-openfeign#634]
How does feign retryer works?.

**Comment by OlgaMaciaszek** [comment]
Please take a look at [OpenFeign docs](https://github.com/OpenFeign/feign#retry) and [Spring Cloud OpenFeign docs](https://docs.spring.io/spring-cloud-openfeign/docs/current/reference/html/#spring-cloud-feign-overriding-defaults).
