### ISSUE TITLE
Two questions on feign.compression.request 

### ISSUE THREAD

**Issue by childewuque** [spring-cloud/spring-cloud-openfeign#635]
This interface is shared by the server and the client (client is openfeign 10.10--httpclient in springboot,server is springboot2.3)：
```
@RequestMapping(value = "/user/get", method = {RequestMethod.GET})
 public User userGetByDesc(@SpringQueryMap User user);
```
The input parameter (`@SpringQueryMap User user`)   is very big ,and the size is dynamic, so I  compress the request in openfeign：
**`feign.compression.request.enabled: true`**
But it doesn't work.

I read these codes in `FeignContentGzipEncodingInterceptor.requiresCompression()`:
```
return matchesMimeType(headers.get(HttpEncoding.CONTENT_TYPE))
				&& contentLengthExceedThreshold(headers.get(HttpEncoding.CONTENT_LENGTH));
```

I thought these two headers were added automatically.
But the request has not any header when I debug the code.

So: 
My 1st question is : In the case ,how to add `Content-Type` & `Content-Length` in request header that is better?
My 2nd question is : If the request header has `Content-Encoding: gzip,deflate`,  which class does the compression work?

Thanks!

plus:
 I change to `POST` instead:
```
    @RequestMapping(value = "/user/get", method = {RequestMethod.POST}, headers = {"Content-Type="+MediaType.APPLICATION_JSON_VALUE})
    public User userGet(@RequestBody  User user);
```
There are `Content-Type` & `Content-Length` in header, then feign adds: `Content-Encoding gzip,deflate`.   
But through wireshark observation, the request content is not compressed.
How to let it work? 
Thanks！

**Comment by OlgaMaciaszek** [comment]
Hello, @childewuque, thank for submitting the question. Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/). 
The `Content-Length` header is [added by OpenFeign when the request contains a body](https://github.com/OpenFeign/feign/blob/79ba51019920d49a6a295dcc56785c59360fba4a/core/src/main/java/feign/RequestTemplate.java#L819-L832), which is in keeping with the [spec](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html) for this header. It refers to entity-body. Similarly, you can read there that the `Content-Encoding` header also refers to the `entity-body`. Unlike the body, the query map should not be huge and require compression. If it does, there are probably architecture changes required to improve the API. Moreover, the encoding headers added on request side do not cause anything to happen automatically - they indicate to the server that the client expects an encoded response, but it's the responsibility of the server to actually implement and handle the encoding when such headers are present.

**Comment by childewuque** [comment]
> Hello, @childewuque, thank for submitting the question. Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/). The `Content-Length` header is [added by OpenFeign when the request contains a body](https://github.com/OpenFeign/feign/blob/79ba51019920d49a6a295dcc56785c59360fba4a/core/src/main/java/feign/RequestTemplate.java#L819-L832), which is in keeping with the [spec](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html) for this header. It refers to entity-body. Similarly, you can read there that the `Content-Encoding` header also refers to the `entity-body`. Unlike the body, the query map should not be huge and require compression. If it does, there are probably architecture changes required to improve the API. Moreover, the encoding headers added on request side do not cause anything to happen automatically - they indicate to the server that the client expects an encoded response, but it's the responsibility of the server to actually implement and handle the encoding when such headers are present.

Thank you very much.
But you said   "Moreover, the encoding headers added on request side do not cause anything to happen automatically"
By the openfeign doc [https://docs.spring.io/spring-cloud-openfeign/docs/2.2.11.BUILD-SNAPSHOT/reference/html/#feign-requestresponse-compression](url)
 ,I think openfeign will compress the request body. If NOT,then what does this configuration do?

> feign.compression.request.enabled=true

**Comment by childewuque** [comment]
@OlgaMaciaszek 
Please help explain this configuration item:
feign.compression.request.enabled=true
Thank you!
