### ISSUE TITLE
Custom feign client with proxy+auth provides no Proxy-Auth header

### ISSUE THREAD

**Issue by justSomeo** [spring-cloud/spring-cloud-openfeign#641]
Bug report

Need Feign to use proxy with credentials and defining something like this:

```
@Bean
    public Client feignClient() {
        return new Client.Proxied(null, null,
                new Proxy(Proxy.Type.HTTP,
                        new InetSocketAddress(proxyHost, Integer.parseInt(proxyPort))),
                        proxyUsername, proxyPassword);
    }
```

But in the end the Proxy-Auth header is not sent, proxy is used though.

**Comment by OlgaMaciaszek** [comment]
Hello, @justSomeo. There's no Spring Cloud OpenFeign integration code used in the snippet you've provided. You should probably create your issue in the [Feign repository](https://github.com/OpenFeign/feign).
