### ISSUE TITLE
Okhttpclient

### ISSUE THREAD

**Issue by ctrotto-celticintl-com** [spring-cloud/spring-cloud-openfeign#643]
`org.springframework.cloud.openfeign.clientconfig.OkHttpFeignConfiguration`w
conflicts with
`org.springframework.cloud.openfeign.FeignAutoConfiguration`

`OkHttpFeignConfiguration`w stops `FeignAutoConfiguration`

Version v3.0.0

**Comment by ctrotto-celticintl-com** [comment]
org.springframework.cloud.openfeign.clientconfig.OkHttpFeignConfiguration gets scanned first. 
So this happens
	@Bean
	public okhttp3.OkHttpClient client(OkHttpClientFactory httpClientFactory, ConnectionPool connectionPool,
			FeignHttpClientProperties httpClientProperties) {

Now in org.springframework.cloud.openfeign.FeignAutoConfiguration this gets block(never happens)
	@Configuration(proxyBeanMethods = false)
	@ConditionalOnClass(OkHttpClient.class)
	**@ConditionalOnMissingBean(okhttp3.OkHttpClient.class)**
	@ConditionalOnProperty("feign.okhttp.enabled")
	protected static class OkHttpFeignConfiguration {

**Comment by OlgaMaciaszek** [comment]
`OkHttpFeignConfiguration` is used for load-balanced scenarios, while the config in `FeignAutoConfiguration` is used for non-loadbalanced clients.
