### ISSUE TITLE
service-id.ribbon.listOfServers is ineffective in springcloud 2020.0.0

### ISSUE THREAD

**Issue by farsunset** [spring-cloud/spring-cloud-openfeign#645]
in dev environment,   how to assign url for feign client in application.yaml

like old version case:

-Dservice-user.ribbon.listOfServers=http://server-user.dev.test.com

**Comment by cbezmen** [comment]
Hi @farsunset, 

You can change to 
-Dspring.cloud.discovery.client.simple.instances.yourServiceName[0].uri=http://server-user.dev.test.com

Please check the [documentation](https://docs.spring.io/spring-cloud-commons/docs/current/reference/html/#simplediscoveryclient).

**Comment by farsunset** [comment]
Thank you！

**Comment by farsunset** [comment]
That is helpful answer

**Comment by farsunset** [comment]
That is helpful answer
