### ISSUE TITLE
okhttp3 The client was re-created because of the lack of configuration

### ISSUE THREAD

**Issue by 9talk** [spring-cloud/spring-cloud-openfeign#655]
**Describe the bug**
spring-cloud-openfeign version : 2.2.6.RELEASE
feign-okhttp version: 10.10.1.jar

Missing configuration causes the okhttp3 client to be recreated on request.

ps: This is still the case with the current main branch.

**Sample**

create code, line 59: org.springframework.cloud.openfeign.clientconfig.OkHttpFeignConfiguration#client
execute code , line 154: feign.okhttp.OkHttpClient#execute

<img width="1668" alt="屏幕快照 2021-12-30 下午4 40 44" src="https://user-images.githubusercontent.com/74651863/147735886-c6f2c7cf-f791-4e9a-acd7-3118fdf2e934.png">

**Comment by OlgaMaciaszek** [comment]
@9talk Thanks for reporting this. Makes sense.
