### ISSUE TITLE
When I pass in multiple parameters at the http test file, it will receive multiple passed parameters from the interface.

### ISSUE THREAD

**Issue by yzhao66** [spring-cloud/spring-cloud-openfeign#670]
[https://github.com/alibaba/spring-cloud-alibaba/issues/2350#issue-1105329209](url)

**Comment by OlgaMaciaszek** [comment]
Is this a Spring Cloud OpenFeign-related issue? If yes, please provide full description of the issue, including steps to reproduce, expected result and actual result. Also, please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
