### ISSUE TITLE
config retry in request method

### ISSUE THREAD

**Issue by qmmm61** [spring-cloud/spring-cloud-openfeign#677]
may add a annotation on feign cilent interface's method or a param so that call this method decide retry eable or retry times override cilent config about retry

**Comment by OlgaMaciaszek** [comment]
Hi, @qmmm61 - thanks for creating the issue. To me, it's better to keep it in the underlying configuration. It's not part of the API. Feel free to provide your reasoning here to start a broader discussion.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
