### ISSUE TITLE
Using @RequestHeader with HttpHeaders throws a ClassCast Exception

### ISSUE THREAD

**Issue by boristhuy** [spring-cloud/spring-cloud-openfeign#68]
Using @RequestHeader with HttpHeaders as a method parameter causes a ClassCast Exception. This issue does not appear if using MultiValueMap<String, String> instead.

Apparently, this [pull request ](https://github.com/OpenFeign/feign/pull/689) over at OpenFeign fixes the issue. 

In short, the version of OpenFeign just needs to be updated.

Do you have any idea when approximately you are planning on updating the version of OpenFeign?

Thanks

**Comment by ryanjbaxter** [comment]
Closed via 9fc19bb
