### ISSUE TITLE
How Feign Client to request  https instead of HTTP?

### ISSUE THREAD

**Issue by Rutik333** [spring-cloud/spring-cloud-openfeign#684]
My service is configured to https , registered on Eureka server.
when I use @FeignClient(value = "my-service-name")  it is always request serves over http how to change it to Https

Sample output : 
[POST] to [http://consumer-service/oty/consumer/tracesByApis]    ----Actual
[POST] to [https://consumer-service/oty/consumer/tracesByApis]   ------Expectation

**Comment by OlgaMaciaszek** [comment]
Hello @Rutik333, if you wish to use`https` scheme for load-balanced calls, you need to make sure that the instances returned for the `serviceId` the client communicates with will have `https` scheme or be marked as `secure`. If any of these is true, `https` scheme will be set for the URI generated by SC OpenFeign. [Here](https://github.com/spring-cloud/spring-cloud-commons/blob/a1f408c8e17ee60d1402323479032e2e181902a0/spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/LoadBalancerUriTools.java#L97-L98)'s the code that resolves it.

**Comment by norbson** [comment]
Btw, it's been a while Ola :)
