### ISSUE TITLE
set common fallback of circuitbreaker in FeignCircuitBreakerInvocationHandler 

### ISSUE THREAD

**Issue by chocolateaya** [spring-cloud/spring-cloud-openfeign#704]
hello,I want to set common fallback in circuitbreaker when use feign and resiliense4j，not add @fallback in every @FeignClient.
Now I rewrite `FeignCircuitBreaker` class and `FeignCircuitBreakerInvocationHandler` class.I want to set in `FeignClientsConfiguration` by `circuitBreakerFeignBuilder()`

```
 @Configuration(proxyBeanMethods = false)
	@ConditionalOnClass(CircuitBreaker.class)
	@ConditionalOnProperty("feign.circuitbreaker.enabled")
	protected static class CircuitBreakerPresentFeignBuilderConfiguration {
		@Bean
		@Scope("prototype")
		@ConditionalOnMissingBean({ Feign.Builder.class, CircuitBreakerFactory.class })
		public Feign.Builder defaultFeignBuilder(Retryer retryer) {
			return Feign.builder().retryer(retryer);
		}

		@Bean
		@Scope("prototype")
		@ConditionalOnMissingBean
		@ConditionalOnBean(CircuitBreakerFactory.class)
		public Feign.Builder circuitBreakerFeignBuilder() {
			return FeignCircuitBreaker.builder();
		}

	}
```

And my way is 

```
@Configuration
public class FeignConfig {

	@Bean
	@ConditionalOnBean({CircuitBreaker.class, CircuitBreakerFactory.class})
	@Scope("prototype")
	public Feign.Builder circuitBreakerFallbackFeignBuilder() {
		return FeignCircuitBreakerFallback.builder();
	}
}
```

but it is not work.

Could you give me some suggestion?

**Comment by OlgaMaciaszek** [comment]
Hello @chocolateaya , the only supported way to configure callbacks is the one[ described in the docs](https://docs.spring.io/spring-cloud-openfeign/docs/current/reference/html/#spring-cloud-feign-circuitbreaker-fallback). Alternatively, you could use `FeignClientBuilder` and its `fallback()` method, but that is also used to build each client individually.
