### ISSUE TITLE
Configuration to use only specific interceptors

### ISSUE THREAD

**Issue by kampaii53** [spring-cloud/spring-cloud-openfeign#717]
Hi everyone.

In my application, I use configurations of rest clients like this

`@FeignClient(value = "TestClient", url = "${test.url:#{null}}", configuration = ApplicationAuthenticationConfig.class)`

in ApplicationAuthenticationConfig I do:

`public class ApplicationAuthenticationConfig{

    @Bean
    public RequestInterceptor jwtInterceptor() {
        return new FeignConfig.JwtInterceptor();
    }
}`

As I have multiple feign clients with ApplicationAuthenticationConfig, there occurs multiple JwtInterceptors created. they all follow same functionality and I would like to create only one JwtInterceptor.

If I make ApplicationAuthenticationConfig a @Configuration, JwtInterceptor will be applied to the clients they are not needed.

What I would like to see is when I specify the configuration, only request interceptors from this configuration are applied

**Comment by OlgaMaciaszek** [comment]
Hello, @kampaii53, thanks for opening the issue. There are separate contexts created for each OF client, so there has to be a separate interceptor per client.

**Comment by kampaii53** [comment]
Hi, @OlgaMaciaszek ! the issue is - when we introduce some global interceptors(as components of global context for example), they are applied in addition to separate context of a client. So a possibility to fetch only interceptors of the configuration should be great.

**Comment by OlgaMaciaszek** [comment]
I'm afraid that's how the Boot context config works - you can either have one in the parent application context (applied everywhere) or ones in the child contexts (OF client contexts) only visible for that particular client. Maybe you could try working with conditions within the interceptor - have one in the main contexts but filter the requests to apply the logic to within it?

**Comment by kampaii53** [comment]
That's almost the approach im using right now.
The thing I want to propose here is to create a mod to feign client builder. Once enabled, it would make builder autowire only beans registered in configuration = **ApplicationAuthenticationConfig**.class.

**Comment by kampaii53** [comment]
Also wanted to mention that feign automatically adding all feign beans from context is not intuitive. I have surprized my colleagues when discovered this

**Comment by OlgaMaciaszek** [comment]
Ok, I don't think we will work on anything similar at this point. If you figure out an improved way, feel free to create a PR - will review.
