### ISSUE TITLE
spring-cloud-openfeign Version compatibility issues

### ISSUE THREAD

**Issue by ricadro** [spring-cloud/spring-cloud-openfeign#720]
When I upgraded the version of springboot from 2.3.12.RELEASE to 2.4.6, and the version of springcloud from Hoxton.SR9 to 2020.0.3, and When starting the service, I get the following error: "Caused by: java.lang.ClassNotFoundException: org.springframework.cloud.openfeign.ribbon.LoadBalancerFeignClient
", what should I do to solve this problem

**Comment by OlgaMaciaszek** [comment]
Hello @ricadro. Ribbon is no longer supported, so changing the dependencies versions should result in it not being included at all. Are you referencing `LoadBalancerFeignClient` anywhere from your code? If not, could you please provide your project build file?

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
