### ISSUE TITLE
Can we support readTimeout for ApacheHttpClient

### ISSUE THREAD

**Issue by x-iron** [spring-cloud/spring-cloud-openfeign#721]
seems we only support `readTimeout` for okhttp, Can we support `readTimeout` for `FeignAutoConfiguration:HttpClientFeignConfiguration:httpClient`?

-------
I just noticed we actually have per-request-default options which override the httpClient-default value:

>     public Options() {
>       this(10, TimeUnit.SECONDS, 60, TimeUnit.SECONDS, true);
>     }

so I can use this as a workaround, but still want the httpClient level readTimeout :)

**Comment by OlgaMaciaszek** [comment]
`HttpClientBuilder` does not provide readTimeout property, however we could add setting `socketTimeout` and `connectionRequestTimeout`.

**Comment by jas34** [comment]
@OlgaMaciaszek if this is still needed to be worked upon then I would like to take this up.

**Comment by OlgaMaciaszek** [comment]
Hi @jas34, sure :). We are not planning to be adding many enhancements to this project anymore, since we've moved it into maintenance mode, but if you'd like to create a PR for this, we will review it.

**Comment by OlgaMaciaszek** [comment]
Closing as already done.

**Comment by OlgaMaciaszek** [comment]
Hi @x-iron, yes, we've [announced it as feature-complete](https://spring.io/blog/2022/12/16/spring-cloud-2022-0-0-codename-kilburn-has-been-released). We suggest [Spring Interface Clients](https://docs.spring.io/spring-framework/reference/integration/rest-clients.html#rest-http-interface) as a replacement going forward.
