### ISSUE TITLE
Please add feign's repository link to the project reference

### ISSUE THREAD

**Issue by DevDengChao** [spring-cloud/spring-cloud-openfeign#729]
**Is your feature request related to a problem? Please describe.**

https://docs.spring.io/spring-cloud-openfeign/docs/current/reference/html/#spring-cloud-feign-overriding-defaults says:

> The `OkHttpClient` and `ApacheHttpClient` and `ApacheHC5` feign clients can be used by setting `feign.okhttp.enabled` or `feign.httpclient.enabled` or `feign.httpclient.hc5.enabled` to `true`, respectively, and having them on the classpath.

but it doesn't tell us which package should we depend to having these classes on the classpath.

**Describe the solution you'd like**

Add at least https://github.com/OpenFeign/feign to the reference page, and don't forget to add a note that users should use the same version with feign-core, or NoClassDefFoundException may thorws.

**Additional context**

I added a latest version of feign-okhttp to a project with spring cloud 2020.0.6, which uses feign-core 10.12 inside spring-cloud-starter-openfeign, then the unit test failed as some class cannot be found 🤣

**Comment by OlgaMaciaszek** [comment]
Hello @DevDengChao, thanks for reporting the issue. Makes sense to add link to Feign project to the docs - will do. However, when it comes to Feign dependencies, you should not specify the version on your own at all. If you are using Spring Cloud dependency management bom (which you should be doing), the correct version of the dependency will be resolved for  you.

**Comment by OlgaMaciaszek** [comment]
Actually, the reference is also link there in the first point of the documentation: https://docs.spring.io/spring-cloud-openfeign/docs/current/reference/html/#spring-cloud-feign.
