### ISSUE TITLE
Jersey 1 transitive dependency - SB app throws error

### ISSUE THREAD

**Issue by mydata** [spring-cloud/spring-cloud-openfeign#73]
Enhancement:
  Jersey 1 dependency as below results in : java.lang.NoSuchMethodError: javax.ws.rs.core.Application.getProperties()Ljava/util/Map;
<img width="446" alt="screen shot 2018-10-04 at 2 29 53 pm" src="https://user-images.githubusercontent.com/1267245/46494894-024df580-c7e2-11e8-9e64-2be274257edb.png">

This could be due to Jersey 1 and Jersey 2 dependencies in the path. Expectation is to have only Jersey 2 when using spring boot 2. 

Currently we are excluding this dependency to get our app working. A version upgrade to include jersey 2 dependency might be the optimal solution.

`<dependency>
    <groupId>javax.ws.rs</groupId>
    <artifactId>javax.ws.rs-api</artifactId>
</dependency>`

**Comment by ryanjbaxter** [comment]
The version of jersey on the classpath is from Ribbon.  There is nothing we can do about the version of Jersey used by Ribbon, that is controlled by Netflix.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
