### ISSUE TITLE
Host was cleaned in LoadBalancerFeignClient

### ISSUE THREAD

**Issue by holmofy** [spring-cloud/spring-cloud-openfeign#733]
**Describe the bug**

**version**: spring-cloud-openfeign-core-2.2.6.RELEASE.jar

`org.springframework.cloud.openfeign.ribbon.LoadBalancerFeignClient#execute`

`cleanUrl(request.url(), clientName)` The clean method will clean the host.

input: `http://192.168.10.103:1662/thing/dix/getByAttr`,`192.168.10.103`
output: `http://:1662/thing/dix/getByAttr`

![image](https://user-images.githubusercontent.com/19494806/186324559-ea3bcf5f-7b47-4c2b-83a0-bf20cf333b5c.png)

**Comment by OlgaMaciaszek** [comment]
Hello @holmofy, both OpenFeign `2.2.6.RELEASE` and Spring Cloud Netflix Ribbon have not been supported for a very long time now. Please switch to a supported OF version (currently `3.1.3`) and migrate from Ribbon to Spring Cloud LoadBalancer.
