### ISSUE TITLE
OpenFeign document v3.1.3 have a error

### ISSUE THREAD

**Issue by ThinkPeace** [spring-cloud/spring-cloud-openfeign#736]
Hi~
Openfeign document **v3.1.3 version** 
At **_1.6 Configuring CircuitBreakers With Configuration Properties_**

![Snipaste_2022-08-29_10-15-57](https://user-images.githubusercontent.com/24205725/187109876-245d13ad-1578-403a-a8b0-91bfdd82ff56.png)

write correctly：
```java
@FeignClient(url = "http://localhost:8080")
public interface DemoClient {

    @GetMapping("demo")
    String getDemo();
}
```

thanks.

**Comment by aofall** [comment]
already fixed and merged in #708

**Comment by ThinkPeace** [comment]
already fixed and merged in https://github.com/spring-cloud/spring-cloud-openfeign/pull/708

**Comment by ThinkPeace** [comment]
already fixed and merged in https://github.com/spring-cloud/spring-cloud-openfeign/pull/708
