### ISSUE TITLE
replacement for DefaultGzipDecoder and DefaultGzipDecoderConfiguration

### ISSUE THREAD

**Issue by rlanycard** [spring-cloud/spring-cloud-openfeign#737]
I upgraded from 2.2.9_RELEASE to 3.1.2. My code using DefaultGzipDecoder and DefaultGzipDecoderConfiguration no longer works, apparently those classes were removed. What is the replacement for those classes?

**Comment by OlgaMaciaszek** [comment]
Hello @rlanycard these were no longer needed as after the upgrade, OF properly handles Gzip input streams. See more [here](https://github.com/spring-cloud/spring-cloud-openfeign/issues/529).

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.
