### ISSUE TITLE
OpenFeign nonsupport request/response compression

### ISSUE THREAD

**Issue by villebo** [spring-cloud/spring-cloud-openfeign#738]
1. JDK 17.0.2
2. Spring  Cloud   2021.0.3
3. Spring  cloud  openfeign   3.1.3
4. Maven  3.8.6
5. intellij  idea  2022.2.1

configured this properties

```
feign.compression.request.enabled=true
feign.compression.request.min-request-size=2048
feign.compression.request.mime-types=text/xml,application/xml,application/json
feign.compression.response.enabled=true
```
I  use  openfeign   call   remote  service  make the deserialized errors:

<img width="811" alt="iShot_2022-08-31_15 59 03" src="https://user-images.githubusercontent.com/6864250/187624884-8bd1e66a-9379-4322-bf38-c8ceab34cc2c.png">

**Comment by OlgaMaciaszek** [comment]
Setting these flags only results on headers being added that indicate compressed request/response handling is expected. Please read more on it [in this issue](https://github.com/spring-cloud/spring-cloud-openfeign/issues/639).

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
