### ISSUE TITLE
Suport for child context creation during AOT processing

### ISSUE THREAD

**Issue by lgklein** [spring-cloud/spring-cloud-openfeign#742]
Based on https://github.com/spring-cloud/spring-cloud-commons/pull/1135...

**Comment by lgklein** [comment]
@OlgaMaciaszek this enhancement should by moved to 4.0.0-RC1? Asking because 4.0.0-M55 was already closed but this issue still open

**Comment by OlgaMaciaszek** [comment]
Yes, I've moved it.

**Comment by lgklein** [comment]
Hello @OlgaMaciaszek, this improvement ended up being left out of RC-1, it would be great to have this point implemented together with the first release of cloud 2022, is this the planning or is the idea that this support will come in future versions?

**Comment by OlgaMaciaszek** [comment]
@lgklein I am working on it now. The plan is to have it done before our GA release.

**Comment by HakChealKim** [comment]
is it means we can use this feature by the end of this year? @OlgaMaciaszek

**Comment by OlgaMaciaszek** [comment]
@HakChealKim  The plan is for it to be ready with the `2022.x` Spring Cloud release train, which is scheduled for mid-December. We're currently working on it.
