### ISSUE TITLE
SpringMVCContract will not search for class level @RequestMapping annotations if the client interface extends a base interface.

### ISSUE THREAD

**Issue by fbyrne** [spring-cloud/spring-cloud-openfeign#76]
Hi, 

I have come across an issue with the SpringMVCContract and base interfaces.

It seems that the code will only look for class level annotations if there are no super interfaces. See https://github.com/spring-cloud/spring-cloud-openfeign/blob/e85e74e311e111fabe5983c7f6fc98afbbc9f5e4/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/SpringMvcContract.java#L122

I have a case where I have a base interface defining methods and two implementations of this 
```java
public interface Foo {
   String get();
}

@RequestMapping("/foo")
public interface FeignFoo extends Foo {
   @Override
   @RequestMapping("")
   String get();
}

public interface AnotherFoo extends Foo {
   @Override
   String get();
}
```
Given the above the client proxy generated for FeignFoo will not include '/foo' from the class level annotation.

Is this by design?  There is specific code to only do this check if there are no extended interfaces.

Kind regards, 
Fergus

**Comment by ryanjbaxter** [comment]
It appears it is by design if that is the way the code is written.  Not sure if @spencergibb knows the reason why.

**Comment by fbyrne** [comment]
@spencergibb, @ryanjbaxter, gentle reminder.
I can contribute a resolution to my issue, however, i would like to understand the original reasoning first.

**Comment by spencergibb** [comment]
Spring thinks classes with request mapping at the top level are actual controllers, so we don't support it because it breaks because it is just an interface

**Comment by fbyrne** [comment]
Thanks for the responses guys, 
@spencergibb, could you clarify mean regarding @RequestMapping at top level classes.  Do you mean
- The @RequestMapping specified at class level will not be supported at all? This is not the case atm.
- The @RequestMapping specified at class level on base interface will not be supported?
- The @RequestMapping specified at class level on an extension of a base interface will not be supported?

Kind regards, 
Fergus

**Comment by spencergibb** [comment]
On feign interfaces, `@RequestMapping` will not be supported at the interface level, regardless of extension or not.
