### ISSUE TITLE
"Source code" link in POM 404's

### ISSUE THREAD

**Issue by aSemy** [spring-cloud/spring-cloud-openfeign#761]
The "Source code" link in the POM is visible in Maven Central 

https://search.maven.org/artifact/org.springframework.cloud/spring-cloud-starter-openfeign/3.1.4/jar

<img width="701" alt="image" src="https://user-images.githubusercontent.com/897017/193019670-b39f429d-4ae9-444c-8212-4747103bd3bc.png">

This links to 
https://github.com/spring-cloud/spring-cloud-openfeign/spring-cloud-starter-openfeign

It should be 
https://github.com/spring-cloud/spring-cloud-openfeign/

**Comment by OlgaMaciaszek** [comment]
The artifact selected in Maven under that link is the `spring-cloud-starter-openfeign` artifact and the source code link points to the corresponding module in the code. That module assembles various different modules as dependencies, but it does not change the fact, that this is the code and maven module from which that artifact is built.

**Comment by OlgaMaciaszek** [comment]
Hello @aSemy, it seems they've started redirecting from search.maven.org to central.sonatype.com and the link you've provided no longer works. If you still experience the issue, please provide updated link.

**Comment by OlgaMaciaszek** [comment]
Thanks, @aSemy, will fix it.
