### ISSUE TITLE
jackson ident not working

### ISSUE THREAD

**Issue by xenoterracide** [spring-cloud/spring-cloud-openfeign#763]
jackson ident doesn't seem to work. This is probably an I durm situation.

I have this... but the json is only output on a single line, suggestions? client is super simple, I suspect you could client up anything with log level full to test this.

```kt
@SpringBootTest
@ActiveProfiles("dev")
@TestPropertySource(
  properties = [
    "cof.devexchange.feign-log-level = full", // is output but only on a single line
    "spring.jackson.serialization.indent-output= true"
  ]
)
internal class BusinessDivisionClientLiveTest @Autowired constructor(val client: BusinessDivisionClient) {
  @Test
  @WithMockUser
  fun findAllBy() {
    val res = client.findAllBy(BusinessDivisionQueryParams(includeRoles = true))
    assertThat(res.divisions).isNotEmpty
  }
}
```

**Comment by OlgaMaciaszek** [comment]
Which version are you using @xenoterracide ?

**Comment by OlgaMaciaszek** [comment]
Also, could you provide a full executable sample that we could verify?

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
