### ISSUE TITLE
Why is @EnableFeignClients needed in spring boot?

### ISSUE THREAD

**Issue by hannah23280** [spring-cloud/spring-cloud-openfeign#769]
Hi,
    May i enquire why `@EnableFeignClients` need to be explicitly added in spring boot in order to use it, since spring boot should be able to detect the presence of the feign dependencies, and  automatically enable it.  
   This is akin to spring MVC where developer doesn't need to explicitly add @EnableWebMvc in spring boot

**Comment by poolsnowhui** [comment]
There may be performance impact.

**Comment by OlgaMaciaszek** [comment]
Using the annotation allows a more fine-grained control, including allowing to specify only certain clients to be enabled.
