### ISSUE TITLE
Spring Data Support (conversion?)

### ISSUE THREAD

**Issue by xenoterracide** [spring-cloud/spring-cloud-openfeign#772]
**Is your feature request related to a problem? Please describe.**

So I know currently this is a Spring Cloud project, however I find that FeignClients look like repositories. It would be cool if I could define Feign Repositories supporting the same interfaces as spring data

**Comment by OlgaMaciaszek** [comment]
Hello, @xenoterracide, Spring Cloud OpenFeign has been[ announced as feature-complete as of `2022.0.0`](https://spring.io/blog/2022/12/16/spring-cloud-2022-0-0-codename-kilburn-has-been-released) in favour of [Spring Interface Clients](https://docs.spring.io/spring-framework/docs/current/reference/html/integration.html#rest-http-interface). We're not planning on adding on any major features at this point. Instead, we'll be concentrating on providing more feature
