### ISSUE TITLE
FeignClient fails to initialize during the Spring Boot 3 AOT phase

### ISSUE THREAD

**Issue by mbouchenoire** [spring-cloud/spring-cloud-openfeign#778]
**Describe the bug**

`@FeignClient` fails to initialize during the Spring Boot 3 AOT phase

**Sample**
Via the Spring Initializer, create any project with:
- `spring-boot-starter-parent:3.0.0-RC1` 
- `spring-cloud-starter-openfeign` (`spring-cloud-dependencies:2022.0.0-M5` is configured automatically)

When declaring a `@FeignClient`, the application works normally, but when passing through the AOT phase, the build fails with this error: 

```
java.lang.IllegalStateException: No constructor or factory method candidate found for Root bean: class [com.app.MyFeignClient]; scope=singleton; abstract=false; lazyInit=true; autowireMode=2; dependencyCheck=0; autowireCandidate=true; primary=true; factoryBeanName=null; factoryMethodName=null; initMethodNames=null; destroyMethodNames=null and argument types []
```

**Comment by lgklein** [comment]
I think this is the same as https://github.com/spring-cloud/spring-cloud-openfeign/issues/742

**Comment by OlgaMaciaszek** [comment]
Yes, it looks to be the same. This is still in the backlog.
