### ISSUE TITLE
LocalDate serializer for @PathVariable don't serialize correctly dates.

### ISSUE THREAD

**Issue by rotilho** [spring-cloud/spring-cloud-openfeign#779]
**Describe the bug**

The following endpoint should resolve to the `balances/AAA/2022-11-1` url
```
    @RequestMapping(
            method = RequestMethod.POST,
            value = "/balances/{assetId}/{valueDate}"
    )
    List<ValueDateBalance> getBalances(@PathVariable String assetId, @PathVariable LocalDate valueDate);
```

Instead it resolves to `balances/AAA/11/1/22`

Use `@DateTimeFormat(iso = DATE)` workaround the issue

Version 3.1.4

**Comment by OlgaMaciaszek** [comment]
Hello, @rotilho. Please provide the `valueDate` String that is passed as the argument to the `getBalances` method.

**Comment by rotilho** [comment]
Hello Olga! I updated the example. I had copied the workaround instead of the sample.

**Comment by OlgaMaciaszek** [comment]
Actually, in this case, preceding the `LocalDate` argument in Feign Client with `@DateTimeFormat` works and is a good solution, like so:

**Comment by rotilho** [comment]
I understand. Thank for the explanation, I'll take a look in the Interface Clients.
