### ISSUE TITLE
Issue about sending post request with body

### ISSUE THREAD

**Issue by xiaohuij** [spring-cloud/spring-cloud-openfeign#78]
#### Error:
    Could not write request: no suitable HttpMessageConverter found for request type [com.***.Client] and content type [application/json]

#### Dependency:
```Java
    <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-openfeign</artifactId>
        <version>2.0.2.RELEASE</version>
    <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.0.5.RELEASE</version>
```

#### Code:  
```Java
@FeignClient(url = "${ding.api}", name = "payment-approval")
public interface DingService {
    @PostMapping(value = "/robot/send", consumes = MediaType.APPLICATION_JSON_VALUE)
    public void notifyRegisterRobot(@RequestParam("access_token") String accessToken, @RequestBody ClientDTO clientDTO);
}
```

Can someone help me out on this issue?

**Comment by ryanjbaxter** [comment]
Hard to tell, I would start with configuring your POM correctly.  It doesnt look like you are using the Spring Boot and Cloud BOMs.  I suggest you start with generating a project on start.spring.io to generate a properly formatted POM.

**Comment by xiaohuij** [comment]
> Hard to tell, I would start with configuring your POM correctly. It doesnt look like you are using the Spring Boot and Cloud BOMs. I suggest you start with generating a project on start.spring.io to generate a properly formatted POM.

Thank you very much for your reply, I believe we can close this issue. I fixed it by adding none args constructor to model object, my fault.
