### ISSUE TITLE
Configuration metadata for clientRegistrationId is missing/wrong

### ISSUE THREAD

**Issue by xnart** [spring-cloud/spring-cloud-openfeign#811]
**Describe the bug**
`clientRegistrationId` config value is needed by [Oauth2FeignConfiguration](https://github.com/spring-cloud/spring-cloud-openfeign/blob/7f66cf3829934f4788db15b78ed1c0971bdb1b8d/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignAutoConfiguration.java#L373) but [spring-configuration-metadata.json](https://github.com/spring-cloud/spring-cloud-openfeign/blob/7f66cf3829934f4788db15b78ed1c0971bdb1b8d/spring-cloud-openfeign-core/src/main/resources/META-INF/additional-spring-configuration-metadata.json#L78) file has it as  `registrationClientId`
```
    {
      "name": "spring.cloud.openfeign.oauth2.registrationClientId",
      "type": "java.lang.String",
      "description": "Provides a clientId to be used with OAuth2.",
      "defaultValue": ""
    }
```

**Sample**
It confused me, one of them should be replaced in my opinion.

**Comment by OlgaMaciaszek** [comment]
Thanks for reporting this, @xnart. That's right. Will fix it.
