### ISSUE TITLE
LoadBalancerUriTools causing issues when using OpenFeign requests

### ISSUE THREAD

**Issue by AdrienNguyenWorldline** [spring-cloud/spring-cloud-openfeign#819]
**Bug description**

OpenFeign generates webservices calls urls with partially encoded query params 

When spring cloud rewrites the call with the choosen target, it does reencode the URL

But as stated in LoadBalancerUriTools line 59 : // Verify if it is really fully encoded. Treat partial encoded as unencoded.

So I end up with a call that has some symbols encoded twice

**Sample**

Starting with a query parameter messageIds with the value <Hello=World@mail.gmail.com>
Feign client ends up making a call to 
http://servicename/search?messageIds=%3CHello=World@mail.gmail.com%3E

LoadBalancerUriTools sees that there is a % but it also finds a =
So it decide to reencode everything and I end up with a call to 
http://ip:port/search?messageIds=%253CHello%3DWorld%40mail.gmail.com%253E

What solutions do I have ?

**Comment by OlgaMaciaszek** [comment]
Hello @AdrienNguyenWorldline, thanks for reporting the issue. Please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue - will verify and work on a fix then.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.
