### ISSUE TITLE
feign.RetryableException: Invalid status(-1)  issue while communicating with other Apps

### ISSUE THREAD

**Issue by dilipmighty245** [spring-cloud/spring-cloud-openfeign#82]
Hi Team, 

I am observing a rather strange failure with FeignClient communicating with a SpringBoot eureka client application.
Following is the error I'm seeing in the logs: 

_feign.RetryableException: Invalid status(-1) executing GET http://192.x.x.x:1233/messages executing GET http://DEMO-APP2/messages_

My Setup:

I have two Applications deployed on cloud foundry, both apps are registered on the Eureka server 

**pom.xml**
<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
</dependency>

Spring boot version: 2.0.5.RELEASE
Spring cloud version:  Finchley.SR1

The issue has become more frequent, Am I missing anything?

Can anyone please help me with this issue ?

**Comment by OlgaMaciaszek** [comment]
Hello @dilipmighty245 Please provide a sample demo project that reproduces the issue - will have a look at it for you then.

**Comment by kongweiteng** [comment]
Can you talk about how to solve the problem? Thank you

**Comment by kongweiteng** [comment]
> HI @OlgaMaciaszek,
> 
> I added network policies between applications and I could be able to fix the issue.
> After that I couldn't reproduce the issue too.

Can you talk about how to solve the problem? Thank you

**Comment by OlgaMaciaszek** [comment]
Hello, @kongweiteng It seems like there was a network setup issue and not any issue with our library. We only support here the issues related to the libraries. I don't really know what changes @dilipmighty245 has introduced in the network policies of his ecosystem and if the issue you have is similar.
