### ISSUE TITLE
Spring suggests to go ahead with Webclient instead of Rest Template (as eventually it will get deprecated), how would it affect Open Feign?

### ISSUE THREAD

**Issue by mishra11dec-abhishek** [spring-cloud/spring-cloud-openfeign#824]
Hi Folks,

With rest template eventually set for deprecation and Spring suggesting to use Webclient instead of rest template.

How will it affect Open Feign, will it also get deprecated?

Kindly provide an answer to this query.

Thanks in advance.

**Comment by OlgaMaciaszek** [comment]
Making Spring Cloud OpenFeign support `WebClient` would require rearchitecting the core Feign, which is an independently maintained project. We are not planning on doing it. Starting with Spring 6 and Spring Cloud 2022, we recommend WebClient-backed [Spring Interface Clients](https://docs.spring.io/spring-framework/docs/6.0.6-SNAPSHOT/reference/html/integration.html#rest-http-interface) as a declarative clients solution of choice.
