### ISSUE TITLE
Exception is wrapped by NoFallbackAvailableException even using Resilence4J `@CircuitBreaker` fallbackMethod

### ISSUE THREAD

**Issue by MangKyu** [spring-cloud/spring-cloud-openfeign#826]
**Describe the bug**
I cannot find any information whether it is intended,
Exception is wrapped by NoFallbackAvailableException even using `@CircuitBreaker` fallbackMethod

</br>

**Sample**
This is my `@FeignClient` with `@CircuitBreaker`
```java
@FeignClient(name = "ExchangeRateOpenFeign", url = "${exchange.currency.api.uri}")
public interface ExchangeRateOpenFeign {
     Logger log = LoggerFactory.getLogger(ExchangeRateOpenFeign.class);

    @CircuitBreaker(name = "currency", fallbackMethod = "fallback")
    @GetMapping
    ExchangeRateResponse call(
            @RequestHeader String apiKey,
            @RequestParam Currency source,
            @RequestParam Currency currencies);

    default ExchangeRateResponse fallback(
            @RequestHeader String apiKey,
            @RequestParam Currency source,
            @RequestParam Currency currencies,
            Throwable e) throws Throwable {

        log.error("Here it comes with error", e);
        throw e;
    }
}
```

</br>
</br>

Then test below is passed
```java
@SpringBootTest
class ExchangeRateOpenFeignTest {

    @Autowired
    private ExchangeRateOpenFeign openFeign;

    @Test
    void errorWrappedWithNoFallbackAvailableException() {
        assertThatThrownBy(() -> openFeign.call("key", Currency.JPY, Currency.KRW))
                .isInstanceOf(NoFallbackAvailableException.class);
    }

}
```

</br>
</br>

Also I can get an error logs with NoFallbackAvailableException (Some logs have been omitted.)
```log
2023-02-08 11:24:33.456 ERROR 65842 --- [pool-1-thread-1] c.m.o.a.openfeign.ExchangeRateOpenFeign  : Here it comes with error

org.springframework.cloud.client.circuitbreaker.NoFallbackAvailableException: No fallback available.
	at org.springframework.cloud.client.circuitbreaker.CircuitBreaker.lambda$run$0(CircuitBreaker.java:31) ~[spring-cloud-commons-3.1.5.jar:3.1.5]
	at io.vavr.control.Try.lambda$recover$6ea7267f$1(Try.java:949) ~[vavr-0.10.2.jar:na]
	at io.vavr.control.Try.of(Try.java:75) ~[vavr-0.10.2.jar:na]
	at io.vavr.control.Try.recover(Try.java:949) ~[vavr-0.10.2.jar:na]
	at org.springframework.cloud.circuitbreaker.resilience4j.Resilience4JCircuitBreaker.run(Resilience4JCircuitBreaker.java:133) ~[spring-cloud-circuitbreaker-resilience4j-2.1.5.jar:2.1.5]
	at org.springframework.cloud.client.circuitbreaker.CircuitBreaker.run(CircuitBreaker.java:30) ~[spring-cloud-commons-3.1.5.jar:3.1.5]
...

Caused by: feign.FeignException$BadRequest: [400] during [GET] to [http://localhost:8090/currency_data/live?source=JPY&currencies=KRW] [ExchangeRateOpenFeign#call(String,Currency,Currency)]: []
	at feign.FeignException.clientErrorStatus(FeignException.java:213) ~[feign-core-11.10.jar:na]
	at feign.FeignException.errorStatus(FeignException.java:194) ~[feign-core-11.10.jar:na]
	at feign.FeignException.errorStatus(FeignException.java:185) ~[feign-core-11.10.jar:na]
...
```

</br>
</br>

Since the fallbackmethod is specified, I don't think the error should be wrapped.
But it is wrapped where it is called from [FeignCircuitBreakerInvocationHandler.java](https://github.com/spring-cloud/spring-cloud-openfeign/blob/main/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignCircuitBreakerInvocationHandler.java#L115)

What I found is that, it is happend by calling fallbackMethod from resilence4J [FallbackDecorators](https://github.com/resilience4j/resilience4j/blob/master/resilience4j-spring/src/main/java/io/github/resilience4j/fallback/DefaultFallbackDecorator.java#L24).

As Object with `@CircuitBreaker` is proxy and when resilence4J calls fallbackMethod By [DefaultFallbackDecorator](https://github.com/resilience4j/resilience4j/blob/master/resilience4j-spring/src/main/java/io/github/resilience4j/fallback/DefaultFallbackDecorator.java#L40),
[FeignCircuitBreakerInvocationHandler.java](https://github.com/spring-cloud/spring-cloud-openfeign/blob/main/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignCircuitBreakerInvocationHandler.java#L115) is called and error is wrapped when fallback method is called

Thanks for reading!

</br>
</br>

**Comment by cbezmen** [comment]
Hey @MangKyu 
Could you give more information about the spring version and cloud version you are using? 

I created a sample repository to understand more about your problem. As far as I can see it doesn't throw NoFallbackAvailableException. One more question from my side why do you want to throw an exception on fallback? 

Feel free to add a commit or create a branch so I can check on that.
https://github.com/cbezmen/can-feign/tree/b-MangKyu

**Comment by MangKyu** [comment]
@cbezmen hi can, Thanks for your kindness!
I uploaded my code on your project which is forked on my [repository](https://github.com/MangKyu/can-feign)
Because 403 forbidden occurs

And i found that it occurs when `spring.cloud.openfeign.circuitbreaker.enabled` value is true.

**Comment by cbezmen** [comment]
Hey @MangKyu 

I updated my branch. you can see diff via there or in [here](https://github.com/cbezmen/can-feign/compare/094cb5a70fc67c33dc4bd9ff955e636f2bb0cc08...5f20421c70c7682a638a2d9be4636ab8345676de).

If you are using spring open feign, you shouldn't use @CircuitBreaker. There is already an implementation for fallbacks. There is documentation in [here](https://docs.spring.io/spring-cloud-openfeign/docs/current/reference/html/#spring-cloud-feign-circuitbreaker-fallback). Spring open-feign checks for fallback implementation in the @FeignClient annotation. If it is not implemented it will wrap it with `NoFallbackAvailableException`.

**Comment by MangKyu** [comment]
Thanks for reply!
I should avoid using `@CircuitBreaker` with Open Feign.

Thanks!
