### ISSUE TITLE
Migration guide for 4.0 - new property prefix

### ISSUE THREAD

**Issue by szpak** [spring-cloud/spring-cloud-openfeign#829]
**Is your feature request related to a problem? Please describe.**
*I'm always frustrated when* I unnecessarily spend time on things that could be clearly stated. Migrating a microservice to Spring Boot 3 (with Spring Cloud to 2022 and some other dependencies). Having no migration guide (maybe I missed one?) for Spring Cloud OpenFeign 4.0, I just bumped the version(s) and... luckily I had some integration test to verify the timeout behavior. They stopped working and after "some time" I've bumped into https://github.com/spring-cloud/spring-cloud-openfeign/pull/679/ where the property prefix was changes from `feign.` to `spring.cloud.openfeign.` :-).

All the custom configuration (also on production) would have to be ignored.

**Describe the solution you'd like**
While - in general - the new properties are covered in the documentation for 4.0, people doing migration might expect some kind of a migration guide to know what backward incompatible changes have been made. It could be in the GitHub release notes for 4.0 and/or as a separate section in the official documentation.

**Additional context**
Maybe there are any other "important" changes in 4.0 to be aware of?

**Comment by OlgaMaciaszek** [comment]
Right @szpak, thanks for pointing this out. It should have been added to the [breaking changes list](https://github.com/spring-cloud/spring-cloud-release/wiki/Spring-Cloud-2022.0-Release-Notes) that we have created for this release (that's where various other important changes are listed as well). We must have overlooked it. Have added it now.

**Comment by szpak** [comment]
Thanks Olga. Yes, I was looking also that page before :-). Nevertheless, maybe you could put a link to that generic document in the [release notes](https://github.com/spring-cloud/spring-cloud-openfeign/releases/tag/v4.0.0) for 4.0.0 in this repo?
