### ISSUE TITLE
Documentation link is incorrect at spring.io

### ISSUE THREAD

**Issue by tlvlp** [spring-cloud/spring-cloud-openfeign#83]
Hi, just a minor documentation related thing, but I have noticed that the link to this project at the spring.io main page is incorrect. 

Posting it here since I couldn't find a bug report link at the site and it's somewhat relevant here to keep the documentation of the project accessible.

**Page**: https://spring.io/projects/spring-cloud
**Link text**: Spring Cloud OpenFeign
**Current url with 404**: https://projects.spring.io/spring-new
**Correct url**: https://spring.io/projects/spring-cloud-openfeign

**Comment by ryanjbaxter** [comment]
Thanks for reporting this, should be fixed now!
