### ISSUE TITLE
Request service with x-www-form-urlencoded

### ISSUE THREAD

**Issue by IAmTrudy** [spring-cloud/spring-cloud-openfeign#836]
**Describe the bug**
Request with x-www-form-urlencoded,in class FormEncoder.encode()
object to map,Missing superclass attribute

**Comment by OlgaMaciaszek** [comment]
Hello @IAmTrudy , this is a duplicate of gh-695. This is an issue in the [feign-form library](https://github.com/OpenFeign/feign-form). Please see [proposed workaround](https://github.com/spring-cloud/spring-cloud-openfeign/issues/695#issuecomment-1443825339).
