### ISSUE TITLE
Request to the original url when retry

### ISSUE THREAD

**Issue by qingdaoheze** [spring-cloud/spring-cloud-openfeign#838]
https://github.com/spring-cloud/spring-cloud-openfeign/blob/647b0b3d1a61df4786c4d23dedf18e605184ef26/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/loadbalancer/RetryableFeignBlockingLoadBalancerClient.java#L142

When retry, retrievedServiceInstance is not assigned a value. So the retry feign client use the original url to send a request. But the original url not a callable address(service id, but instance ip), then the request will failed.

**Comment by qingdaoheze** [comment]
I think the following codes should be added here.
```java
				} else {
					retrievedServiceInstance = serviceInstance;
				}
```

**Comment by OlgaMaciaszek** [comment]
Thanks for reporting the issue, @qingdaoheze , do you mean [this](https://github.com/spring-cloud/spring-cloud-openfeign/pull/841)?

**Comment by qingdaoheze** [comment]
No, I think it is a new bug. The service id in the subsequent request url is not replaced with the service instance ip and port

**Comment by OlgaMaciaszek** [comment]
Thanks for the update @qingdaoheze . In this case, please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by qingdaoheze** [comment]
Please refer to the simple project below:
https://github.com/qingdaoheze/feign-rety-issue

Start the following two projects:
feign-rety-issue/openfeign-client/src/main/java/org/example/openfeign/client/SayHelloClient.java
feign-rety-issue/openfeign-server/src/main/java/org/example/openfeign/server/SayHelloServer.java

Then you can request to http://127.0.0.1:8001/say-hello.  you will see the following error:
java.net.UnknownHostException: hello-server

**Comment by OlgaMaciaszek** [comment]
Hello, @qingdaoheze it does seem to have been that issue and it's already been fixed. After[ upgrading and removing an unnecessary dependency](https://github.com/OlgaMaciaszek/feign-rety-issue/tree/upgrade-dependencies), I'm getting: `feign.FeignException$InternalServerError: [500] during [GET] to [http://hello-server/sayHello?name=john] [SayHello#sayHello(String)]: [Hello john]`, which is the correct error.

**Comment by qingdaoheze** [comment]
Yes, you are right. Thanks a lot!
