### ISSUE TITLE
SpringQueryMap is ignored when used with Pageable 

### ISSUE THREAD

**Issue by philippeu** [spring-cloud/spring-cloud-openfeign#842]
`@SpringQueryMap` is ignored when method includes `Pageable`

`Page<Dto> list(@SpringQueryMap Pojo pojo, Pageable pageable)`

this has been introduced in version 3.1.6 by https://github.com/spring-cloud/spring-cloud-openfeign/issues/753

`paramIndex` is set always to Pageable causing `PageableSpringQueryMapEncoder` to ignore `@SpringQueryMap`

**Comment by OlgaMaciaszek** [comment]
Thanks, @philippeu. Possibly a regression. Will verify this.
