### ISSUE TITLE
Overriding Feign Defaults Problem

### ISSUE THREAD

**Issue by mloine** [spring-cloud/spring-cloud-openfeign#844]
**Describe the bug**
According to the documentation, overriding the default configuration does not take effect. Prompt me that the name is not legitimate
version: 2.0.0.RELEASE

**Sample**
<img width="767" alt="image" src="https://user-images.githubusercontent.com/39936599/222921878-0ff182d6-0bbd-48b8-a55f-48cdfcacb725.png">
<img width="1913" alt="image" src="https://user-images.githubusercontent.com/39936599/222921888-805d2a44-7b21-4dae-b3bf-ddc0855d1686.png">

**Comment by mloine** [comment]
I have upgrade to a supported version 3.1.6. the issue still persists. this is a minimal, complete, verifiable example .
[fegin-issure-demo.zip](https://github.com/spring-cloud/spring-cloud-openfeign/files/10953043/fegin-issure-demo.zip)

**Comment by OlgaMaciaszek** [comment]
@cbezmen thanks so much for triaging this issue (and many others) before we had time to look at it :slightly_smiling_face: - it's really helpful. @mloine - please try applying @cbezmen's suggestion - it should fix your issue.
