### ISSUE TITLE
No special characters in @FeignClient

### ISSUE THREAD

**Issue by malandrakisgeo** [spring-cloud/spring-cloud-openfeign#858]
A Swedish company provided a URL containing special characters (äåö).

It looked like www.company.se/bäseUrl, and there were several endpoints after it.

We resorted to using www.company.se in Feign, and pasting /bäseUrl in each and every GetMapping/PostMapping annotation afterwards. 

This may be impossible if a url contains the special characters in its base. 

Consider using the same encoding as org.springframework.web.bind.annotation-packages.

**Comment by OlgaMaciaszek** [comment]
Hello, @malandrakisgeo, thanks for reporting the issue. This isn't really a valid URL. Please refer to [RFC-3986](https://www.rfc-editor.org/rfc/rfc3986).
