### ISSUE TITLE
Openfeign FeignClientRegistrar not recognising interfaces annotated with Netflix Feign Client

### ISSUE THREAD

**Issue by nitinteja** [spring-cloud/spring-cloud-openfeign#859]
Question: OpenFeign FeignClientRegistrar not recognising interfaces annotated with Netflix Feign Client

Description of the issue:

We have two spring boot microservices one running on Spring 2.6.7 using open feign dependency and another running on Spring 1.3.7 and netflix feign dependency.
 
When we try to use a service interface annotated with Netflix Feign having all the post mapping info of Microservice 2 in Microservice 1 as a child dependency, the Openfeign FeignClientRegistrar is simply ignoring the feign client with TRACE log as "Ignored because not matching any filter".

Is there any way that openfeign can still recognise the Netflix feign by any chance without having the need to upgrade Microservice 2 which is still using Netflix Feign

**Comment by OlgaMaciaszek** [comment]
Hello @nitinteja. These are incompatible major versions, you cannot use them together. Also, please note that the `1.3.7` dependency has not been supported for a long time. By continuing to use it, you risk exposing your applications to security issues. We strongly recommend you upgrade to a supported version as soon as possible.
