### ISSUE TITLE
Are you interested in providing a SpringBoot version?

### ISSUE THREAD

**Issue by youngledo** [spring-cloud/spring-cloud-openfeign#861]
**Is your feature request related to a problem? Please describe.**
I did not use SpringCloud in my project, but I also want to use Feign's features.

**Describe the solution you'd like**
I hope to release a Springboot version without any dependency on SpringCloud.

for example：
```xml
<dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-openfeign</artifactId>
    </dependency>
```

**Comment by OlgaMaciaszek** [comment]
Hello @youngledo. That is not something we plan to do. We suggest you use [Spring Interface Clients](https://docs.spring.io/spring-framework/docs/current/reference/html/web-reactive.html#webflux-http-interface-client) instead.

**Comment by OlgaMaciaszek** [comment]
Also, if you do not need Cloud integrations, you can just use [OpenFeign](https://github.com/OpenFeign/feign) dependencies directly and set it up on your own.
