### ISSUE TITLE
Reactive Feign

### ISSUE THREAD

**Issue by miguellgramacho96** [spring-cloud/spring-cloud-openfeign#864]
Hi. Probably there's a place to view the roadmap for spring but I could not find. I would like to ask if developing a Reactive version of Feign is in the roadmap or in talks for the near future. Thanks

**Comment by OlgaMaciaszek** [comment]
Hello @miguellgramacho96. This is a duplicate. Closing in favour of gh-668. Please see [this comment](https://github.com/spring-cloud/spring-cloud-openfeign/issues/668#issuecomment-1607854972) for the suggested replacement.
