### ISSUE TITLE
OpenFeign makes new spring-boot-docker-compose module to run service creation twice

### ISSUE THREAD

**Issue by kbaluc** [spring-cloud/spring-cloud-openfeign#865]
**Describe the bug**
Running `spring-boot-docker-compose` dependency alongside `spring-cloud-starter-openfeign` makes docker-compose service creation to run twice. It produces `The bean 'jdbcConnectionDetailsForXXXXDb1' could not be registered. A bean with that name has already been defined and overriding is disabled.`

**Sample**
[demo1.zip](https://github.com/spring-cloud/spring-cloud-openfeign/files/11579965/demo1.zip)

**Comment by kbaluc** [comment]
Propably fixed in https://github.com/spring-cloud/spring-cloud-openfeign/pull/398

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by merorafael** [comment]
Hi @OlgaMaciaszek, I had the same problem here. How can I use the `2022.0.4-SNAPSHOT`? It's not published in Maven Central.

**Comment by OlgaMaciaszek** [comment]
Hello @merorafael, you'll need to add  https://repo.spring.io/snapshot and https://repo.spring.io/ui/native/milestone to repositories in your build file.

**Comment by kbaluc** [comment]
I've tested against 2022.0.4-SNAPSHOT and Docker Lifecycle is started only once. Issue doesn't appear. @merorafael example pom attached if you want to check
[spring-cloud-snapshot-test.txt](https://github.com/spring-cloud/spring-cloud-openfeign/files/12181893/spring-cloud-snapshot-test.txt)
