### ISSUE TITLE
@Conditional is invalid on @FeignClient

### ISSUE THREAD

**Issue by LiuFqiang** [spring-cloud/spring-cloud-openfeign#884]
I would like to request a http service interface using feign
`@ConditionalOnProperty("")
@FeignClient(name = "remotePhpTheaterService", url = "${php.xjc.url}")
public interface RemotePhpService {

}`
But @ConditionalOnProperty is invalid
I want to implement this feature and can only override FeignClientsRegistry

**Comment by OlgaMaciaszek** [comment]
Hello, @LiuFqiang , thanks for reporting the issue, however, Spring Cloud OpenFeign is now in maintenance mode (we suggest using Spring Interface Clients instead), and we're now only handling bugs and some minor features. This is not something that we'll be adding to the backlog.

**Comment by LiuFqiang** [comment]
1
