### ISSUE TITLE
Enhancing Apache HttpClient 5 / Http2Client /  OkHttpClient configuration in Spring Cloud OpenFeign

### ISSUE THREAD

**Issue by ernest-gonzales** [spring-cloud/spring-cloud-openfeign#887]
With the removal of support for Apache HttpClient 4 in the recent commit ([d30540d](https://github.com/spring-cloud/spring-cloud-openfeign/commit/d30540d1445afd7acfdf9f30bd8cb3ae654c9fed)), the Spring Cloud OpenFeign project has transitioned to using Apache HttpClient 5 for its HTTP client functionality. As a result, an Apache HttpClient 5 client bean is now automatically generated when the class `ApacheHttp5Client.class` is present on the classpath. This enhancement was achieved by introducing `matchIfMissing = true` on the property condition, for example [here](https://github.com/spring-cloud/spring-cloud-openfeign/commit/d30540d1445afd7acfdf9f30bd8cb3ae654c9fed#diff-ee4c210b66322a680c6f9b56cb651033138f4eddbae7234624dc9579f944a084R255).

To maintain alignment between the codebase and documentation, changes have to be done in the documentation files: [spring-cloud-openfeign.adoc](https://github.com/spring-cloud/spring-cloud-openfeign/blob/main/docs/src/main/asciidoc/spring-cloud-openfeign.adoc?plain=1#L143) and [additional-spring-configuration-metadata.json](https://github.com/spring-cloud/spring-cloud-openfeign/blob/main/spring-cloud-openfeign-core/src/main/resources/META-INF/additional-spring-configuration-metadata.json#L39).

It's important to note that, as of this update, only the Apache HttpClient 5 client is automatically enabled if the necessary class is detected on the classpath. The other two clients, Http2Client and OkHttpClient, require explicit configuration for enabling. It might be beneficial to review the usage of `matchIfMissing = true` for the `spring.cloud.openfeign.httpclient.hc5.enabled` property condition to ensure consistency.

Furthermore, we've identified inconsistent behavior related to the other two clients. Instances such as [this](https://github.com/spring-cloud/spring-cloud-openfeign/blob/main/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignAutoConfiguration.java#L240) and [this](https://github.com/spring-cloud/spring-cloud-openfeign/blob/3fc733f7ade6219dc8e665757d57401e785cdd08/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignAutoConfiguration.java#L395) indicate that property values do not necessarily have to be set to `true` to satisfy the associated conditions.

This observation encourages us to review and potentially revise the usage of `matchIfMissing = true` across various property conditions, ensuring a cohesive and intuitive configuration experience.

Thank you for considering these suggestions and improvements.

**Comment by OlgaMaciaszek** [comment]
Hello @ernest-gonzales, thanks for reporting the issue and the thorough analysis and  description. I will fix the docs. When it comes to the inconsistency between enabling the different modes, you're right, but since the Spring Cloud OpenFeign is now in maintenance mode, we will not be adding this to the backlog. 

When it comes to this bit: 
> Furthermore, we've identified inconsistent behavior related to the other two clients. Instances such as [this](https://github.com/spring-cloud/spring-cloud-openfeign/blob/main/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignAutoConfiguration.java#L240) and [this](https://github.com/spring-cloud/spring-cloud-openfeign/blob/3fc733f7ade6219dc8e665757d57401e785cdd08/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignAutoConfiguration.java#L395) indicate that property values do not necessarily have to be set to true to satisfy the associated conditions.

I'm not sure I understand what you mean. Could you please provide more details and tag me in the comment?

**Comment by OlgaMaciaszek** [comment]
@ernest-gonzales , I'm going to work on the documentation fix within this issue. Please create another issue with more details for the problem quoted in my comment above.

**Comment by ernest-gonzales** [comment]
Hi @OlgaMaciaszek , thank you for your changes to the documentation. I'm sure this will help everyone using OpenFeign in their projects.

> Furthermore, we've identified inconsistent behavior related to the other two clients. Instances such as [this](https://github.com/spring-cloud/spring-cloud-openfeign/blob/main/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignAutoConfiguration.java#L240) and [this](https://github.com/spring-cloud/spring-cloud-openfeign/blob/3fc733f7ade6219dc8e665757d57401e785cdd08/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignAutoConfiguration.java#L395) indicate that property values do not necessarily have to be set to true to satisfy the associated conditions.
What I mean is that `@ConditionalOnProperty("spring.cloud.openfeign.okhttp.enabled")` will be evaluated to `true` for any value different from an empty string and `"false"`, e.g. values like `"dummy"` or `"never"` will enable annotated classes. Please check [Spring documentation](https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/autoconfigure/condition/ConditionalOnProperty.html) for details. I believe it would be better to change conditions I pointed out to `@ConditionalOnProperty(name = "spring.cloud.openfeign.okhttp.enabled", havingValue="true")`

**Comment by OlgaMaciaszek** [comment]
That's right. However, something that could only be changed during a major release to maintain compatibility. At this point, the next major release has not been scheduled.

**Comment by OlgaMaciaszek** [comment]
See new issue: https://github.com/spring-cloud/spring-cloud-openfeign/issues/956

**Comment by ernest-gonzales** [comment]
> See new issue: #956

Great, thank you!
