### ISSUE TITLE
FeignClient  parameter is null

### ISSUE THREAD

**Issue by 1013785085** [spring-cloud/spring-cloud-openfeign#89]
```
@FeignClient(serviceId = "user", path ="/user")
@RestController
@RequestMapping("user")
public interface UserService  {

    @PostMapping("updateByName")
    User updateByName(User user);
}

```
why parameter user is null?

**Comment by ryanjbaxter** [comment]
Because there is no value.  It needs to come from somewhere (the path or body for example).

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by ryanjbaxter** [comment]
Not sure what the means

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
