### ISSUE TITLE
feign client http header can not use json string as header value?

### ISSUE THREAD

**Issue by Gavin16** [spring-cloud/spring-cloud-openfeign#893]
**Describe the bug**
I need to use feign client to make a RPC invoke and use a json string value as http header, 
but I find feign.template.Expressions#create use ":" to split my json string and only use part[0], part[1] to make an Expression. 
for example: "{"source":"Inner", "traceld":"0b34769c298dccc7e1b0a548"'" as a input header value finally we only get
"{"source":"Inner", "traceld"}"

the version I'm using is : spring-cloud-starter-openfeign:3.1.8

**Sample**
for feign client http header key-value
common_header: "{"source":"Inner", "traceld":"0b34769c298dccc7e1b0a548"}"
but receiver only cat receive:
common_header: "{"source":"Inner", "traceld"}"

**Comment by OlgaMaciaszek** [comment]
Hello, @Gavin16. Spring Cloud OpenFeign `3.1.x` is no longer under maintenance. Please upgrade to `4.0.x` or `4.1.x`. Also, the relates to `RequestTemplate` that is part of the [OpenFeign/Feign](https://github.com/spring-cloud/spring-cloud-openfeign) project and not SC OpenFeign. You can start a discussion on it there.
