### ISSUE TITLE
HTTPS SocketFactory registry overriden

### ISSUE THREAD

**Issue by uesleilima** [spring-cloud/spring-cloud-openfeign#91]
Whenever we try to pass a preconfigured RegistryBuilder to be used on creating a new connection manager it is overriding the HTTPS registry socket factory previously set by a default one.

It does not happen to HTTP schema because it has a null verification before it, maybe some additional check needs to be performed on HTTPS before setting it.

https://github.com/spring-cloud/spring-cloud-commons/blob/2515e4540549ef5d2acc5825bc9df0f4f0787f40/spring-cloud-commons/src/main/java/org/springframework/cloud/commons/httpclient/DefaultApacheHttpClientConnectionManagerFactory.java#L64

**Comment by uesleilima** [comment]
> I'm not following, the code you pointed to does use the optional `RegistryBuilder` bean. In either case the problem seems specific to OpenFeign and should be moved to that project.

No matter what we register with id 'https' on RegistryBuilder, it is always overridden by the method on the line I mentioned, so the connection manager created does not use what we pass on a 
 eventual registryBuilder argument.

**Comment by ryanjbaxter** [comment]
The `RegistryBuilder` on that line comes from here https://github.com/spring-cloud/spring-cloud-openfeign/blob/6d4686624e732247cab4ede05ef453783fd6f257/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/ribbon/HttpClientFeignLoadBalancedConfiguration.java#L60

It should be `Autowired` in, are you saying your bean is not?

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by CakeSpork** [comment]
I have just ran into this same issue. I would like to use a client certificate on the apache client's connection for a feign client. The feign client can use an optional RegistryBuilder that I've tried to add in my @Configuration class like this:

`@Bean
    public RegistryBuilder registryBuilder(SSLConnectionSocketFactory sslConnectionSocketFactory) {
        return RegistryBuilder.create()
            .register(HTTP_SCHEME, PlainConnectionSocketFactory.INSTANCE)
            .register(HTTPS_SCHEME, sslConnectionSocketFactory);
    }`

using a custom SSLConnectionSocketFactory @Bean.

However, within the default HttpClientFeignLoadBalancedConfiguration.HttpClientFeignConfiguration.connectionManager() method, a call is made to DefaultApacheHttpClientConnectionManagerFactory.newConnectionManager(), which overrides my RegistryBuilder's sslConnectionSocketFactory with a newly instantiated one:

> registryBuilder.register("https", SSLConnectionSocketFactory.getSocketFactory());

**Comment by CakeSpork** [comment]
I've attempted to see what I could do in a PR to fix this, but I'm encountering a two issues: 1. DefaultApacheHttpClientConnectionManagerFactory is not part of spring-cloud-openfeign (does that mean this issue is in the wrong place?), and 2. I don't see an API in RegistryBuilder to check of something was already registered (i.e. something like RegistryBuilder::isRegistered(String id))
