### ISSUE TITLE
Multiple MediaTypes in produces not working correctly

### ISSUE THREAD

**Issue by jnt0r** [spring-cloud/spring-cloud-openfeign#916]
**Describe the bug**
When I define a feign client with two MediaTypes in produces (produces={MediaType.APPLICATION_PDF_VALUE, MediaType.APPLICATION_JSON_VALUE}), the client only sends the first value in the accept header.

I would expect the client to send both MediaTypes in the Accept header, separated by comma.

**Current workaround**
The current workaround for me is to specify the produces attribute as String:
produces=MediaType.APPLICATION_PDF_VALUE + "," + MediaType.APPLICATION_JSON_VALUE
Then the accept header is send as expected.

**Comment by jnt0r** [comment]
I created a repo with reproducible tests: https://github.com/jnt0r/feign-reproducable

As you can see in test and test2, only the first value of the produces map is send as content of the accept header. When defining produces as a string, the whole value is send.

**Comment by jnt0r** [comment]
@OlgaMaciaszek any update on this?

**Comment by OlgaMaciaszek** [comment]
Hello, @jnt0r, we will post any updates here. At this moment, we're prioritising some relaese-related items in our backlog.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
