### ISSUE TITLE
@MockBean annotation does not find existing bean created through @FeignClient

### ISSUE THREAD

**Issue by trcoelho** [spring-cloud/spring-cloud-openfeign#930]
**Describe the bug**
Opened as requested by https://github.com/spring-projects/spring-boot/issues/38348

Using Spring Boot 3.1.5 version `@MockBean` annotation works charming, however after trying Spring Boot ` 3.2.0-SNAPSHOT` with Spring Cloud `2023.0.0-SNAPSHOT` without any code change, looks like it stopped working as it not mocking `@Autowired` objects anymore.

It looks like it affects FeignClients classes (annotated by `@FeignClient`).

Is this a known issue?

**Sample**
Please find attached a compressed folder which has two projects inside:

mockbean-31 which has 3.1.5 Spring Boot dependencies
mockbean-32 which has 3.2.0-SNAPSHOT Spring Boot dependencies
Either has same code base without any differences.

To run, just go through folder and run:

`mvn test`

Let me know if you have any question.

[mockbeans.zip](https://github.com/spring-cloud/spring-cloud-openfeign/files/13349005/mockbeans.zip)

**Comment by OlgaMaciaszek** [comment]
@trcoelho thanks for reporting the issue.
[This](https://github.com/spring-cloud/spring-cloud-openfeign/blob/ca4de4e703a953504c3bb7b08fa8c69566697953/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientsRegistrar.java#L251-L252) actually is the way the `FactoryBean.OBJECT_TYPE_ATTRIBUTE` should be set for both MockBean and AOT to work correctly; there was, in fact no problem with AOT, but, instead, an over-eager assertion in the AOT tests.  After reverting [this change](https://github.com/spring-cloud/spring-cloud-openfeign/commit/e7c4c6e599d05ade5a1288321cb094362cbd8847) and [fixing the test](https://github.com/spring-cloud/spring-cloud-openfeign/commit/727752ae39ae3bece1d0741fb4b4e9dfcef372f0), the regression is now fixed.
