### ISSUE TITLE
When Feign Service name is a character in http or https，will cause an error！

### ISSUE THREAD

**Issue by OldGong** [spring-cloud/spring-cloud-openfeign#94]
When Feign Service name is a character in http or https，will cause an error！

The reason for the problem is in lines 99-107 in the following file.
[https://github.com/spring-cloud/spring-cloud-openfeign/blob/master/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/ribbon/LoadBalancerFeignClient.java](url)

**Comment by OldGong** [comment]
String newUrl = originalUrl.replaceFirst(host, "");
eg： hosttp
eg:  originalUrl ：http://tp/abc/bcd.json  becomes ht://tp/abc/bcd.json  after replacement.

**Comment by ryanjbaxter** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by SYJJK** [comment]
This is an example [https://github.com/SYJJK/openfeign.git](url)
