### ISSUE TITLE
Can't set request header in json format

### ISSUE THREAD

**Issue by hyfsy** [spring-cloud/spring-cloud-openfeign#941]
**Describe the bug**
when I set request header in json format, I found that the request header was parsed as an expression and then truncated.

**Sample**
![286861862-8e09ffdc-ec62-48b8-9713-71bedd42b3f5](https://github.com/spring-cloud/spring-cloud-openfeign/assets/46069922/0b39489f-3e2a-4bb7-8040-46ca11c4c337)

**Comment by hyfsy** [comment]
spring-cloud-starter-openfeign: 3.1.4

**Comment by OlgaMaciaszek** [comment]
Hello @hyfsy. Spring Cloud OpenFeign `3.1.x` is no longer under maintenance. Please upgrade to  `4.0.x.` or `4.1.x`. Also, the  relates to `RequestTemplate` that is part of the [OpenFeign/Feign](https://github.com/spring-cloud/spring-cloud-openfeign) project and not SC OpenFeign. You can start a discussion on it there.

**Comment by OlgaMaciaszek** [comment]
Also duplicate of https://github.com/spring-cloud/spring-cloud-openfeign/issues/893/.
