### ISSUE TITLE
Reactive (asynchronous) FeignClients

### ISSUE THREAD

**Issue by NadChel** [spring-cloud/spring-cloud-openfeign#942]
`@FeignClient` is a convenient thing, but sometimes you need to perform requests asynchronously. There are some public GitHub repositories ([example](https://github.com/PlaytikaOSS/feign-reactive)) that try to serve this purpose, but as far as I'm aware there's no official Spring solution. Please consider providing one

**Comment by OlgaMaciaszek** [comment]
Hello @NadChel. This is a duplicate. Closing in favour of https://github.com/spring-cloud/spring-cloud-openfeign/issues/668. Please see https://github.com/spring-cloud/spring-cloud-openfeign/issues/668#issuecomment-1607854972 for the suggested replacement.
