### ISSUE TITLE
Performance discussion about default openfeign client config

### ISSUE THREAD

**Issue by raizoor** [spring-cloud/spring-cloud-openfeign#955]
**Resume** 
Discussion about default client performance of spring-cloud-openfeign

**Versions**
Java 17
Springboot 2.7.18
spring-cloud-dependencies 2021.0.8

**Scenario**

During a performance tests in a microservice that contain a 3 feign clients, it was possible to saw a high GC usage (i.e. high cpu utilization as well) in two methods, as we can see at profiler image bellow

![profiler-onlySpringCloudFeign](https://github.com/spring-cloud/spring-cloud-openfeign/assets/44624093/a0062700-a366-42df-bb7c-aa6bda4a74c8)

We have a high tps scenario here - 110tps. The situation was absolutely unstable and we has too much resources to handle with that.

After studying the issue I decided to use lib {io.github.openfeign:feign-httpclient:11.8} and do a new evaluation. To my surprise, we had a significant improvement in resource usage, as feign started using other classes and no longer generated as many objects, as shown bellow

![springCloudFeign-httpClient](https://github.com/spring-cloud/spring-cloud-openfeign/assets/44624093/770c000e-8036-4f05-af7a-0b9157e0a776)

So, my question: Is this the expected behavior of the default implementation or is there something I did incorrectly, because we've a big difference here.

**Code**

I don't have a high customization clients, only a custom decoder and base64 auth, as bellow

```
@FeignClient(value = "...", url = "...",
        configuration = ClientConfig.class)
public interface .. {

    @PostMapping("..")
    SpecificObject post(
            @RequestHeader("..") Boolean ..,
            @RequestBody SpecificObject ..
    );
}
```

![image](https://github.com/spring-cloud/spring-cloud-openfeign/assets/44624093/217b691c-d647-40cd-b97c-c2b68f379d24)

![basicAuthInterceptor](https://github.com/spring-cloud/spring-cloud-openfeign/assets/44624093/880cdd95-e581-4dca-9cc3-936d93a83b7e)

**Comment by OlgaMaciaszek** [comment]
Hello @raizoor, the implementation that seems to be causing the issue is (`Client.Default`) is part of the [OpenFeign/feign ](https://github.com/OpenFeign/feign)project and not Spring Cloud OpenFeign. Please create an issue there to start a discussion.

**Comment by raizoor** [comment]
Thks Olga.
--> https://github.com/OpenFeign/feign/issues/2267
