### ISSUE TITLE
Rest Controller doesn't return exception handler response but instead hangs forever and then returns feign exception unavailable response

### ISSUE THREAD

**Issue by jmoseman01** [spring-cloud/spring-cloud-openfeign#976]
**Describe the bug**
I'm using the following
implementation 'org.springframework.cloud:spring-cloud-starter-openfeign:3.0.7'
implementation 'org.springframework.cloud:spring-cloud-openfeign-core:3.0.7'

There's a controller advice exception handler which runs the logging but at the end it should return a Response Entity with status of 500, but instead the response hangs for 20 min and returns the 503 instead.

**Comment by OlgaMaciaszek** [comment]
Hello @jmoseman01, thanks for reporting the issue. The version you've listed is no longer in OSS support. Please upgrade to `4.1.0` (Spring Cloud `2023.0.0`) and Spring Boot `3.2.x`. If the issue persists, please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by jmoseman01** [comment]
This was not a problem with open feign.  This was a problem with our smtp logger not being configured correctly.
