### ISSUE TITLE
Feign defaults to DefaultClient when own customized Bean CloseableHttpClient is provided.

### ISSUE THREAD

**Issue by algyy** [spring-cloud/spring-cloud-openfeign#98]
Hi,

I have de following dependencies in my project:

> 'org.springframework.cloud:spring-cloud-starter-openfeign'
> 'io.github.openfeign:feign-httpclient'

Also I put this property in application.properties: feign.httpclient.enabled=true

And the documentation says:

> The OkHttpClient and ApacheHttpClient feign clients can be used by setting feign.okhttp.enabled or feign.httpclient.enabled to true, respectively, and having them on the classpath. You can customize the HTTP client used by providing a bean of either ClosableHttpClient when using Apache or OkHttpClient when using OK HTTP.

So the thing is when I provide my own customize bean of CloseableHttpClient, Feign defaults to DefaultClient and not use HttpClient, in my case the bean I provided.
I saw that FeignAutoConfiguration has a config class insde named HttpClientFeignConfiguration, which is annotated with @ConditionalOnMissingBean(CloseableHttpClient.class) so If I provided a bean of CloseableHttpClient this class is not executed and Feign defaults to DefaultClient.

What am I doing wrong? Maybe I don't get it.

**Comment by algyy** [comment]
[feign-test.zip](https://github.com/spring-cloud/spring-cloud-openfeign/files/2692833/feign-test.zip)
Sure, here you are.
When I'm debugging the method SynchronousMethodHandle#executeAndDecode, I can see that the client variable of Client type, it contains a DefaultClient object.

**Comment by ryanjbaxter** [comment]
What I think you want to do is create a Bean of type `ApacheHttpClient`.  When you create the `ApacheHttpClient` you can supply your customized `HttpClient`.

**Comment by algyy** [comment]
Yeah I realized that I can do this by checking `FeignAutoConfiguration`. But is that piece of documentation I posted accurate?
Also If I do what you mentioned I lose the auto configuration that `FeignAutoConfiguration` provides.

**Comment by algyy** [comment]
I mean, if I want to customized the HttpClient with a KeepAliveStrategy or set evictIdleConnection property with a idleTime, I can't do it by using the auto configuration.

**Comment by spencergibb** [comment]
The premise of auto configuration is to provide a sample way to get started and then to back off when user provides customizations

**Comment by algyy** [comment]
So I came to this solution, to have the best of both worlds: auto configuration and custom

```
feign.httpclient.enabled=true
rest.client.conn.max.idle.time=30000
#the following are the default feign values
feign.httpclient.disable-ssl-validation=false
feign.httpclient.maxConnections=200
feign.httpclient.maxConnectionsPerRoute=50
feign.httpclient.timeToLive=900
feign.httpclient.timeToLiveUnit=SECONDS
feign.httpclient.followRedirects=true
feign.httpclient.connectionTimeout=2000
feign.httpclient.connectionTimerRepeat=3000
```

```
@Configuration
public class FeignConfiguration {

    @Value("${rest.client.conn.max.idle.time}")
    private long maxIdleTime;

    @Bean
    public Client feignClient(ApacheHttpClientFactory httpClientFactory,
                              HttpClientConnectionManager httpClientConnectionManager,
                              FeignHttpClientProperties httpClientProperties) {
        RequestConfig defaultRequestConfig = RequestConfig
                                                .custom()
                                                .setConnectTimeout(httpClientProperties.getConnectionTimeout())
                                                .setRedirectsEnabled(httpClientProperties.isFollowRedirects())
                                                .build();
        CloseableHttpClient httpClient = httpClientFactory
                                            .createBuilder()
                                            .setConnectionManager(httpClientConnectionManager)
                                            .setDefaultRequestConfig(defaultRequestConfig)
                                            .evictIdleConnections(maxIdleTime, TimeUnit.MILLISECONDS)
                                            .evictExpiredConnections()
                                            .build();

        return new ApacheHttpClient(httpClient);
    }
}
```

This is an example, what do you think?
Thank you.

**Comment by spencergibb** [comment]
If that works for you great. Do we need to keep this open?

**Comment by algyy** [comment]
Yeah, thank you both for the support. Really appreciate it.
