### ISSUE TITLE
Spring version upgrade broke FeignClient loadbalancing

### ISSUE THREAD

**Issue by tyhennig** [spring-cloud/spring-cloud-openfeign#981]
**Describe the bug**

Hello,
I recently upgraded a project from Spring Boot version 2.6.8 -> 3.1.3 and Spring Cloud version 2021.0.0 -> 2022.0.3

We had been utilizing the Spring Cloud Loadbalancer to provide custom loadbalancing logic to our feign clients with the following configuration (based on code found here https://www.tutorialspoint.com/spring_cloud/spring_cloud_load_balancer.htm).

```
@LoadBalancerClient(name = "my-service", configuration = CustomConfiguration.class)
@FeignClient(name = "my-service")
public interface MyServiceClient
{
   ...
}
```

After completing the version upgrade, it appears the default Round-Robin load balancing is always used as opposed to the `CustomConfiguration.class`. 

I have been unable to find anything in the release notes for either OpenFeign or Cloud Loadbalancer to indicate a breaking change, so I was hoping for some insight here.

Thank you!

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
