### ISSUE TITLE
Integration with resilience4j

### ISSUE THREAD

**Issue by typekpb** [spring-cloud/spring-cloud-openfeign#99]
As hystrix is getting into maintenance mode (see: https://github.com/Netflix/Hystrix):
> Hystrix is no longer in active development, and is currently in maintenance mode.
> ...
>  For the cases where something like Hystrix makes sense, we intend to continue using Hystrix for existing applications, and to leverage open and active projects like resilience4j for new internal projects. We are beginning to recommend others do the same.

Do you plan to provide support that would be hystrix independant, and possibly using the resilience4j as an alternative?

There seems to be an idea for the feign client: https://github.com/resilience4j/resilience4j/issues/196 once that would be available, there should be no blocker for reusing that one.

**Comment by typekpb** [comment]
OK, I just noticed, that implementation on the resilience4j side has already done: https://github.com/resilience4j/resilience4j/issues/196 so there should be no blocker in implementing here, right?

**Comment by ryanjbaxter** [comment]
Turns out I cant transfer issues across orgs, here is the issue I created https://github.com/spring-cloud-incubator/spring-cloud-circuitbreaker/issues/3
